/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_SD_B1_11 (number 19), FlexSPI_SS0/U13[1] */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_SS0_PERIPHERAL                            FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_SS0_SIGNAL                        FLEXSPI_A_SS0_B   /*!< Signal name */

/* GPIO_SD_B1_07 (number 24), FlexSPI_CLK/U13[6] */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_CLK_PERIPHERAL                            FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_CLK_SIGNAL                         FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_B1_08 (number 23), FlexSPI_D0_A/U13[5] */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_D0_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_D0_A_SIGNAL                       FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_B1_10 (number 21), FlexSPI_D1_A/U13[2] */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_D1_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_D1_A_SIGNAL                       FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_B1_09 (number 22), FlexSPI_D2_A/U13[3] */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_D2_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_D2_A_SIGNAL                       FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_B1_06 (number 25), FlexSPI_D3_A/U13[7] */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_D3_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_D3_A_SIGNAL                       FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_AD_B0_05 (number 106), JTAG_nTRST/J16[3]/USER_LED/J17[5] */
/* Routed pin properties */
#define BOARD_INITPINS_RUN_LED_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_RUN_LED_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RUN_LED_CHANNEL                                        5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RUN_LED_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RUN_LED_GPIO_PIN                                       5U   /*!< GPIO pin number */
#define BOARD_INITPINS_RUN_LED_GPIO_PIN_MASK                          (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RUN_LED_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RUN_LED_PIN                                            5U   /*!< PORT pin number */
#define BOARD_INITPINS_RUN_LED_PIN_MASK                               (1U << 5U)   /*!< PORT pin mask */

/* GPIO_AD_B0_03 (number 108), JTAG_TDI/J16[5]/WDOG_B */
/* Routed pin properties */
#define BOARD_INITPINS_WDOG_B_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_WDOG_B_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_WDOG_B_CHANNEL                                         3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_WDOG_B_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_WDOG_B_GPIO_PIN                                        3U   /*!< GPIO pin number */
#define BOARD_INITPINS_WDOG_B_GPIO_PIN_MASK                           (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_WDOG_B_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_WDOG_B_PIN                                             3U   /*!< PORT pin number */
#define BOARD_INITPINS_WDOG_B_PIN_MASK                                (1U << 3U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
