/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MIMXRT1021xxxxx
package_id: MIMXRT1021DAG5A
mcu_data: ksdk2_0
processor_version: 16.3.0
board: MIMXRT1020-EVK
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 8d0b2cc6-2af8-4c3e-8e51-760ce0081e33
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * MPU initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MPU'
- type: 'mpu_utility'
- mode: 'MPU'
- custom_name_enabled: 'false'
- type_id: 'mpu_utility'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'MPU'
- config_sets:
  - mpu_init:
    - mpuInit: 'disabled'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void MPU_init(void) {
} */

/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'edma_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableMinorLoopMapping: 'false'
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'true'
      - ERCA: 'fixedPriority'
      - enableDebugMode: 'false'
    - dma_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
      - 11: []
      - 12: []
      - 13: []
      - 14: []
      - 15: []
    - edma_channels: []
    - errInterruptConfig:
      - enableErrInterrupt: 'false'
      - errorInterrupt:
        - IRQn: 'DMA_ERROR_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t DMA0_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = true,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = false
};

static void DMA0_init(void) {
  /* DMA0 minor loop mapping */
  EDMA_EnableMinorLoopMapping(DMA0_DMA_BASEADDR, false);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * CHARGE_CAN_A initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CHARGE_CAN_A'
- type: 'flexcan'
- mode: 'interrupts'
- custom_name_enabled: 'true'
- type_id: 'flexcan_2.10.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CAN1'
- config_sets:
  - interruptsCfg:
    - messageBufferIrqs: '0xffffffff'
    - messageBufferIrqs2: '0x0000ffff'
    - interruptsEnable: ''
    - enable_irq: 'true'
    - interrupt_shared:
      - IRQn: 'CAN1_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'true'
      - priority: '2'
      - enable_custom_name: 'true'
      - handler_custom_name: 'Charge_CAN_A_IRQhandler'
  - fsl_flexcan:
    - can_config:
      - clockSource: 'kFLEXCAN_ClkSrcOsc'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - wakeupSrc: 'kFLEXCAN_WakeupSrcUnfiltered'
      - baudRate: '250000'
      - maxMbNum: '32'
      - enableLoopBack: 'false'
      - enableTimerSync: 'true'
      - enableSelfWakeup: 'false'
      - enableIndividMask: 'false'
      - disableSelfReception: 'true'
      - enableListenOnlyMode: 'false'
      - enableSupervisorMode: 'true'
      - timingConfig:
        - propSeg: '2'
        - phaseSeg1: '4'
        - phaseSeg2: '3'
        - rJumpwidth: '2'
        - bitTime: []
    - enableRxFIFO: 'false'
    - rxFIFO:
      - idFilterTable: ''
      - idFilterNum: 'num0'
      - idFilterType: 'kFLEXCAN_RxFifoFilterTypeA'
      - priority: 'kFLEXCAN_RxFifoPrioLow'
    - channels:
      - 0:
        - mbID: '0'
        - mbType: 'mbInactive'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 1:
        - mbID: '1'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 2:
        - mbID: '2'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 3:
        - mbID: '3'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 4:
        - mbID: '4'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 5:
        - mbID: '5'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 6:
        - mbID: '6'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 7:
        - mbID: '7'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 8:
        - mbID: '8'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 9:
        - mbID: '9'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 10:
        - mbID: '10'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 11:
        - mbID: '11'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 12:
        - mbID: '12'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 13:
        - mbID: '13'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 14:
        - mbID: '14'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 15:
        - mbID: '15'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 16:
        - mbID: '16'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 17:
        - mbID: '17'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 18:
        - mbID: '18'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 19:
        - mbID: '19'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 20:
        - mbID: '20'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 21:
        - mbID: '21'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 22:
        - mbID: '22'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 23:
        - mbID: '23'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 24:
        - mbID: '24'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 25:
        - mbID: '25'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 26:
        - mbID: '26'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 27:
        - mbID: '27'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 28:
        - mbID: '28'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 29:
        - mbID: '29'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 30:
        - mbID: '30'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 31:
        - mbID: '31'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const flexcan_config_t CHARGE_CAN_A_config = {
  .wakeupSrc = kFLEXCAN_WakeupSrcUnfiltered,
  .bitRate = 250000UL,
  .maxMbNum = 32U,
  .enableLoopBack = false,
  .enableTimerSync = true,
  .enableSelfWakeup = false,
  .enableIndividMask = false,
  .disableSelfReception = true,
  .enableListenOnlyMode = false,
  .enableSupervisorMode = true,
  .timingConfig = {
    .preDivider = 23,
    .propSeg = 1,
    .phaseSeg1 = 3,
    .phaseSeg2 = 2,
    .rJumpwidth = 1
  }
};
/* Message buffer 16 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_16 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 17 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_17 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 18 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_18 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 19 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_19 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 20 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_20 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 21 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_21 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 22 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_22 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 23 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_23 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 24 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_24 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 25 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_25 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 26 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_26 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 27 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_27 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 28 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_28 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 29 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_29 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 30 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_30 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 31 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_31 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};

static void CHARGE_CAN_A_init(void) {
  FLEXCAN_Init(CHARGE_CAN_A_PERIPHERAL, &CHARGE_CAN_A_config, CHARGE_CAN_A_CLOCK_SOURCE);
  /* Message buffer 1 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 1, true);
  /* Message buffer 2 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 2, true);
  /* Message buffer 3 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 3, true);
  /* Message buffer 4 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 4, true);
  /* Message buffer 5 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 5, true);
  /* Message buffer 6 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 6, true);
  /* Message buffer 7 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 7, true);
  /* Message buffer 8 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 8, true);
  /* Message buffer 9 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 9, true);
  /* Message buffer 10 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 10, true);
  /* Message buffer 11 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 11, true);
  /* Message buffer 12 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 12, true);
  /* Message buffer 13 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 13, true);
  /* Message buffer 14 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 14, true);
  /* Message buffer 15 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_A_PERIPHERAL, 15, true);
  /* Message buffer 16 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 16, &CHARGE_CAN_A_rx_mb_config_16, true);
  /* Message buffer 17 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 17, &CHARGE_CAN_A_rx_mb_config_17, true);
  /* Message buffer 18 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 18, &CHARGE_CAN_A_rx_mb_config_18, true);
  /* Message buffer 19 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 19, &CHARGE_CAN_A_rx_mb_config_19, true);
  /* Message buffer 20 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 20, &CHARGE_CAN_A_rx_mb_config_20, true);
  /* Message buffer 21 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 21, &CHARGE_CAN_A_rx_mb_config_21, true);
  /* Message buffer 22 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 22, &CHARGE_CAN_A_rx_mb_config_22, true);
  /* Message buffer 23 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 23, &CHARGE_CAN_A_rx_mb_config_23, true);
  /* Message buffer 24 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 24, &CHARGE_CAN_A_rx_mb_config_24, true);
  /* Message buffer 25 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 25, &CHARGE_CAN_A_rx_mb_config_25, true);
  /* Message buffer 26 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 26, &CHARGE_CAN_A_rx_mb_config_26, true);
  /* Message buffer 27 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 27, &CHARGE_CAN_A_rx_mb_config_27, true);
  /* Message buffer 28 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 28, &CHARGE_CAN_A_rx_mb_config_28, true);
  /* Message buffer 29 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 29, &CHARGE_CAN_A_rx_mb_config_29, true);
  /* Message buffer 30 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 30, &CHARGE_CAN_A_rx_mb_config_30, true);
  /* Message buffer 31 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_A_PERIPHERAL, 31, &CHARGE_CAN_A_rx_mb_config_31, true);
  /* Enable FlexCAN interrupts of message buffers */
  FLEXCAN_EnableMbInterrupts(CHARGE_CAN_A_PERIPHERAL, (0xFFFFULL << 32) | 0xFFFFFFFFULL);
  /* Interrupt vector CAN1_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(CHARGE_CAN_A_FLEXCAN_IRQN, CHARGE_CAN_A_FLEXCAN_IRQ_PRIORITY);
  /* Interrupt CHARGE_CAN_A_FLEXCAN_IRQN request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(CHARGE_CAN_A_FLEXCAN_IRQN); function call. */
}

/***********************************************************************************************************************
 * CHARGE_CAN_B initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CHARGE_CAN_B'
- type: 'flexcan'
- mode: 'interrupts'
- custom_name_enabled: 'true'
- type_id: 'flexcan_2.10.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CAN2'
- config_sets:
  - interruptsCfg:
    - messageBufferIrqs: '0xffffffff'
    - messageBufferIrqs2: '0xffffffff'
    - interruptsEnable: ''
    - enable_irq: 'true'
    - interrupt_shared:
      - IRQn: 'CAN2_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'true'
      - priority: '2'
      - enable_custom_name: 'true'
      - handler_custom_name: 'Charge_CAN_B_IRQhandler'
  - fsl_flexcan:
    - can_config:
      - clockSource: 'kFLEXCAN_ClkSrcOsc'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - wakeupSrc: 'kFLEXCAN_WakeupSrcUnfiltered'
      - baudRate: '250000'
      - maxMbNum: '64'
      - enableLoopBack: 'false'
      - enableTimerSync: 'true'
      - enableSelfWakeup: 'false'
      - enableIndividMask: 'false'
      - disableSelfReception: 'true'
      - enableListenOnlyMode: 'false'
      - enableSupervisorMode: 'true'
      - timingConfig:
        - propSeg: '2'
        - phaseSeg1: '4'
        - phaseSeg2: '3'
        - rJumpwidth: '2'
        - bitTime: []
    - enableRxFIFO: 'false'
    - rxFIFO:
      - idFilterTable: ''
      - idFilterNum: 'num0'
      - idFilterType: 'kFLEXCAN_RxFifoFilterTypeA'
      - priority: 'kFLEXCAN_RxFifoPrioLow'
    - channels:
      - 0:
        - mbID: '32'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 1:
        - mbID: '33'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 2:
        - mbID: '34'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 3:
        - mbID: '35'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 4:
        - mbID: '36'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 5:
        - mbID: '37'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 6:
        - mbID: '38'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 7:
        - mbID: '39'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 8:
        - mbID: '40'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 9:
        - mbID: '41'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 10:
        - mbID: '42'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 11:
        - mbID: '43'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 12:
        - mbID: '44'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 13:
        - mbID: '45'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 14:
        - mbID: '46'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 15:
        - mbID: '47'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 16:
        - mbID: '48'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 17:
        - mbID: '49'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 18:
        - mbID: '50'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 19:
        - mbID: '51'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 20:
        - mbID: '52'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 21:
        - mbID: '53'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 22:
        - mbID: '54'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 23:
        - mbID: '55'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 24:
        - mbID: '56'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 25:
        - mbID: '57'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 26:
        - mbID: '58'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 27:
        - mbID: '59'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 28:
        - mbID: '60'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 29:
        - mbID: '61'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 30:
        - mbID: '62'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 31:
        - mbID: '63'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const flexcan_config_t CHARGE_CAN_B_config = {
  .wakeupSrc = kFLEXCAN_WakeupSrcUnfiltered,
  .bitRate = 250000UL,
  .maxMbNum = 64U,
  .enableLoopBack = false,
  .enableTimerSync = true,
  .enableSelfWakeup = false,
  .enableIndividMask = false,
  .disableSelfReception = true,
  .enableListenOnlyMode = false,
  .enableSupervisorMode = true,
  .timingConfig = {
    .preDivider = 23,
    .propSeg = 1,
    .phaseSeg1 = 3,
    .phaseSeg2 = 2,
    .rJumpwidth = 1
  }
};
/* Message buffer 48 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_48 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 49 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_49 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 50 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_50 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 51 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_51 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 52 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_52 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 53 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_53 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 54 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_54 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 55 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_55 = {
  .id = FLEXCAN_ID_STD(0UL),
  .format = kFLEXCAN_FrameFormatStandard,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 56 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_56 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 57 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_57 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 58 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_58 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 59 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_59 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 60 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_60 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 61 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_61 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 62 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_62 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 63 configuration structure */
const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_63 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};

static void CHARGE_CAN_B_init(void) {
  FLEXCAN_Init(CHARGE_CAN_B_PERIPHERAL, &CHARGE_CAN_B_config, CHARGE_CAN_B_CLOCK_SOURCE);
  /* Message buffer 32 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 32, true);
  /* Message buffer 33 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 33, true);
  /* Message buffer 34 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 34, true);
  /* Message buffer 35 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 35, true);
  /* Message buffer 36 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 36, true);
  /* Message buffer 37 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 37, true);
  /* Message buffer 38 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 38, true);
  /* Message buffer 39 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 39, true);
  /* Message buffer 40 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 40, true);
  /* Message buffer 41 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 41, true);
  /* Message buffer 42 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 42, true);
  /* Message buffer 43 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 43, true);
  /* Message buffer 44 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 44, true);
  /* Message buffer 45 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 45, true);
  /* Message buffer 46 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 46, true);
  /* Message buffer 47 initialization */
  FLEXCAN_SetTxMbConfig(CHARGE_CAN_B_PERIPHERAL, 47, true);
  /* Message buffer 48 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 48, &CHARGE_CAN_B_rx_mb_config_48, true);
  /* Message buffer 49 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 49, &CHARGE_CAN_B_rx_mb_config_49, true);
  /* Message buffer 50 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 50, &CHARGE_CAN_B_rx_mb_config_50, true);
  /* Message buffer 51 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 51, &CHARGE_CAN_B_rx_mb_config_51, true);
  /* Message buffer 52 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 52, &CHARGE_CAN_B_rx_mb_config_52, true);
  /* Message buffer 53 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 53, &CHARGE_CAN_B_rx_mb_config_53, true);
  /* Message buffer 54 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 54, &CHARGE_CAN_B_rx_mb_config_54, true);
  /* Message buffer 55 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 55, &CHARGE_CAN_B_rx_mb_config_55, true);
  /* Message buffer 56 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 56, &CHARGE_CAN_B_rx_mb_config_56, true);
  /* Message buffer 57 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 57, &CHARGE_CAN_B_rx_mb_config_57, true);
  /* Message buffer 58 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 58, &CHARGE_CAN_B_rx_mb_config_58, true);
  /* Message buffer 59 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 59, &CHARGE_CAN_B_rx_mb_config_59, true);
  /* Message buffer 60 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 60, &CHARGE_CAN_B_rx_mb_config_60, true);
  /* Message buffer 61 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 61, &CHARGE_CAN_B_rx_mb_config_61, true);
  /* Message buffer 62 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 62, &CHARGE_CAN_B_rx_mb_config_62, true);
  /* Message buffer 63 initialization */
  FLEXCAN_SetRxMbConfig(CHARGE_CAN_B_PERIPHERAL, 63, &CHARGE_CAN_B_rx_mb_config_63, true);
  /* Enable FlexCAN interrupts of message buffers */
  FLEXCAN_EnableMbInterrupts(CHARGE_CAN_B_PERIPHERAL, (0xFFFFFFFFULL << 32) | 0xFFFFFFFFULL);
  /* Interrupt vector CAN2_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(CHARGE_CAN_B_FLEXCAN_IRQN, CHARGE_CAN_B_FLEXCAN_IRQ_PRIORITY);
  /* Interrupt CHARGE_CAN_B_FLEXCAN_IRQN request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(CHARGE_CAN_B_FLEXCAN_IRQN); function call. */
}

/***********************************************************************************************************************
 * LPUART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART1'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART1'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '9600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1726657927547'
        - eDMAn: '1'
        - eDMA_source: 'kDmaRequestMuxLPUART1Rx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'true'
          - enablePreemptAbility: 'false'
          - channelPriority: '4'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1726657927548'
        - eDMAn: '0'
        - eDMA_source: 'kDmaRequestMuxLPUART1Tx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'true'
          - enablePreemptAbility: 'false'
          - channelPriority: '3'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART_DmaCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART1_config = {
  .baudRate_Bps = 9600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART1_RX_Handle;
edma_handle_t LPUART1_TX_Handle;
lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;

static void LPUART1_init(void) {
  LPUART_Init(LPUART1_PERIPHERAL, &LPUART1_config, LPUART1_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART1Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART1_RX_DMAMUX_BASEADDR, LPUART1_RX_DMA_CHANNEL, LPUART1_RX_DMA_REQUEST);
  /* Enable the channel 1 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART1_RX_DMAMUX_BASEADDR, LPUART1_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART1Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART1_TX_DMAMUX_BASEADDR, LPUART1_TX_DMA_CHANNEL, LPUART1_TX_DMA_REQUEST);
  /* Enable the channel 0 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART1_TX_DMAMUX_BASEADDR, LPUART1_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART1_RX_Handle handle */
  EDMA_CreateHandle(&LPUART1_RX_Handle, LPUART1_RX_DMA_BASEADDR, LPUART1_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART1_TX_Handle handle */
  EDMA_CreateHandle(&LPUART1_TX_Handle, LPUART1_TX_DMA_BASEADDR, LPUART1_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART1_PERIPHERAL, &LPUART1_LPUART_eDMA_Handle, LPUART_DmaCallback, NULL, &LPUART1_TX_Handle, &LPUART1_RX_Handle);
}

/***********************************************************************************************************************
 * EXT_RTC_I2C initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'EXT_RTC_I2C'
- type: 'lpi2c'
- mode: 'master'
- custom_name_enabled: 'true'
- type_id: 'lpi2c_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C3'
- config_sets:
  - main:
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
  - interrupt_vector: []
  - master:
    - mode: 'freertos'
    - config:
      - enableMaster: 'false'
      - enableDoze: 'false'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '100000'
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - edmaRequestSources: 'enableRx enableTx'
    - transfer:
      - enable_custom_handle: 'false'
      - flags: ''
      - slaveAddress: '51'
      - direction: 'kLPI2C_Write'
      - subaddress: '0'
      - subaddressSize: '2'
      - blocking_buffer: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t EXT_RTC_I2C_masterConfig = {
  .enableMaster = false,
  .enableDoze = false,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 100000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
lpi2c_master_transfer_t EXT_RTC_I2C_masterTransfer = {
  .flags = kLPI2C_TransferDefaultFlag,
  .slaveAddress = 51,
  .direction = kLPI2C_Write,
  .subaddress = 0,
  .subaddressSize = 2,
  .data = NULL,
  .dataSize = 0
};
lpi2c_rtos_handle_t EXT_RTC_I2C_masterHandle;

static void EXT_RTC_I2C_init(void) {
  LPI2C_RTOS_Init(&EXT_RTC_I2C_masterHandle, EXT_RTC_I2C_PERIPHERAL, &EXT_RTC_I2C_masterConfig, EXT_RTC_I2C_CLOCK_FREQ);
  /* Enable Leader eDMA request sources: Tx, Rx */
  LPI2C_MasterEnableDMA(EXT_RTC_I2C_PERIPHERAL, true, true);
}

/***********************************************************************************************************************
 * ADC1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC1'
- type: 'adc_12b1msps_sar'
- mode: 'ADC_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'adc_12b1msps_sar_2.0.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC1'
- config_sets:
  - fsl_adc:
    - clockConfig:
      - clockSource: 'kADC_ClockSourceAD'
      - clockSourceFreq: 'custom:10 MHz'
      - clockDriver: 'kADC_ClockDriver1'
      - samplePeriodMode: 'kADC_SamplePeriodShort8Clocks'
      - enableAsynchronousClockOutput: 'true'
    - conversionConfig:
      - resolution: 'kADC_Resolution12Bit'
      - hardwareAverageMode: 'kADC_HardwareAverageCount32'
      - enableHardwareTrigger: 'software'
      - enableHighSpeed: 'false'
      - enableLowPower: 'false'
      - enableContinuousConversion: 'false'
      - enableOverWrite: 'true'
      - enableDma: 'false'
    - resultingTime: []
    - resultCorrection:
      - doAutoCalibration: 'false'
      - offset: '0'
    - hardwareCompareConfiguration:
      - hardwareCompareMode: 'disabled'
      - value1: '0'
      - value2: '0'
    - enableInterrupt: 'false'
    - adc_interrupt:
      - IRQn: 'ADC1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_channels_config:
      - 0:
        - channelNumber: 'IN.10'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
      - 1:
        - channelNumber: 'IN.11'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
      - 2:
        - channelNumber: 'IN.12'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
      - 3:
        - channelNumber: 'IN.13'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
      - 4:
        - channelNumber: 'IN.14'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
      - 5:
        - channelNumber: 'IN.15'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC1_config = {
  .enableOverWrite = true,
  .enableContinuousConversion = false,
  .enableHighSpeed = false,
  .enableLowPower = false,
  .enableLongSample = false,
  .enableAsynchronousClockOutput = true,
  .referenceVoltageSource = kADC_ReferenceVoltageSourceAlt0,
  .samplePeriodMode = kADC_SamplePeriodShort8Clocks,
  .clockSource = kADC_ClockSourceAD,
  .clockDriver = kADC_ClockDriver1,
  .resolution = kADC_Resolution12Bit
};
const adc_channel_config_t ADC1_channels_config[6] = {
  {
    .channelNumber = 10U,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = 11U,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = 12U,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = 13U,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = 14U,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = 15U,
    .enableInterruptOnConversionCompleted = false
  }
};
static void ADC1_init(void) {
  /* Initialize ADC1 peripheral. */
  ADC_Init(ADC1_PERIPHERAL, &ADC1_config);
  /* Configure ADC1 peripheral to average 32 conversions in one measurement. */
  ADC_SetHardwareAverageConfig(ADC1_PERIPHERAL, kADC_HardwareAverageCount32);
}

/***********************************************************************************************************************
 * LPUART2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART2'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART2'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '9600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1726657927553'
        - eDMAn: '3'
        - eDMA_source: 'kDmaRequestMuxLPUART2Rx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1726657927554'
        - eDMAn: '2'
        - eDMA_source: 'kDmaRequestMuxLPUART2Tx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART_DmaCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART2_config = {
  .baudRate_Bps = 9600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART2_RX_Handle;
edma_handle_t LPUART2_TX_Handle;
lpuart_edma_handle_t LPUART2_LPUART_eDMA_Handle;

static void LPUART2_init(void) {
  LPUART_Init(LPUART2_PERIPHERAL, &LPUART2_config, LPUART2_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART2Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART2_RX_DMAMUX_BASEADDR, LPUART2_RX_DMA_CHANNEL, LPUART2_RX_DMA_REQUEST);
  /* Enable the channel 3 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART2_RX_DMAMUX_BASEADDR, LPUART2_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART2Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART2_TX_DMAMUX_BASEADDR, LPUART2_TX_DMA_CHANNEL, LPUART2_TX_DMA_REQUEST);
  /* Enable the channel 2 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART2_TX_DMAMUX_BASEADDR, LPUART2_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART2_RX_Handle handle */
  EDMA_CreateHandle(&LPUART2_RX_Handle, LPUART2_RX_DMA_BASEADDR, LPUART2_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART2_TX_Handle handle */
  EDMA_CreateHandle(&LPUART2_TX_Handle, LPUART2_TX_DMA_BASEADDR, LPUART2_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART2_PERIPHERAL, &LPUART2_LPUART_eDMA_Handle, LPUART_DmaCallback, NULL, &LPUART2_TX_Handle, &LPUART2_RX_Handle);
}

/***********************************************************************************************************************
 * LPUART3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART3'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART3'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '9600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter16'
      - enableTx: 'true'
      - enableRx: 'true'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1726657927555'
        - eDMAn: '5'
        - eDMA_source: 'kDmaRequestMuxLPUART3Rx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1726657927556'
        - eDMAn: '4'
        - eDMA_source: 'kDmaRequestMuxLPUART3Tx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART_DmaCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART3_config = {
  .baudRate_Bps = 9600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter16,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART3_RX_Handle;
edma_handle_t LPUART3_TX_Handle;
lpuart_edma_handle_t LPUART3_LPUART_eDMA_Handle;

static void LPUART3_init(void) {
  LPUART_Init(LPUART3_PERIPHERAL, &LPUART3_config, LPUART3_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART3Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART3_RX_DMAMUX_BASEADDR, LPUART3_RX_DMA_CHANNEL, LPUART3_RX_DMA_REQUEST);
  /* Enable the channel 5 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART3_RX_DMAMUX_BASEADDR, LPUART3_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART3Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART3_TX_DMAMUX_BASEADDR, LPUART3_TX_DMA_CHANNEL, LPUART3_TX_DMA_REQUEST);
  /* Enable the channel 4 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART3_TX_DMAMUX_BASEADDR, LPUART3_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART3_RX_Handle handle */
  EDMA_CreateHandle(&LPUART3_RX_Handle, LPUART3_RX_DMA_BASEADDR, LPUART3_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART3_TX_Handle handle */
  EDMA_CreateHandle(&LPUART3_TX_Handle, LPUART3_TX_DMA_BASEADDR, LPUART3_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART3_PERIPHERAL, &LPUART3_LPUART_eDMA_Handle, LPUART_DmaCallback, NULL, &LPUART3_TX_Handle, &LPUART3_RX_Handle);
}

/***********************************************************************************************************************
 * LPUART4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART4'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART4'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '9600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1726657927557'
        - eDMAn: '7'
        - eDMA_source: 'kDmaRequestMuxLPUART4Rx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1726657927558'
        - eDMAn: '6'
        - eDMA_source: 'kDmaRequestMuxLPUART4Tx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART_DmaCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART4_config = {
  .baudRate_Bps = 9600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART4_RX_Handle;
edma_handle_t LPUART4_TX_Handle;
lpuart_edma_handle_t LPUART4_LPUART_eDMA_Handle;

static void LPUART4_init(void) {
  LPUART_Init(LPUART4_PERIPHERAL, &LPUART4_config, LPUART4_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART4Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART4_RX_DMAMUX_BASEADDR, LPUART4_RX_DMA_CHANNEL, LPUART4_RX_DMA_REQUEST);
  /* Enable the channel 7 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART4_RX_DMAMUX_BASEADDR, LPUART4_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART4Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART4_TX_DMAMUX_BASEADDR, LPUART4_TX_DMA_CHANNEL, LPUART4_TX_DMA_REQUEST);
  /* Enable the channel 6 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART4_TX_DMAMUX_BASEADDR, LPUART4_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART4_RX_Handle handle */
  EDMA_CreateHandle(&LPUART4_RX_Handle, LPUART4_RX_DMA_BASEADDR, LPUART4_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART4_TX_Handle handle */
  EDMA_CreateHandle(&LPUART4_TX_Handle, LPUART4_TX_DMA_BASEADDR, LPUART4_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART4_PERIPHERAL, &LPUART4_LPUART_eDMA_Handle, LPUART_DmaCallback, NULL, &LPUART4_TX_Handle, &LPUART4_RX_Handle);
}

/***********************************************************************************************************************
 * LPUART5 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART5'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART5'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '9600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1726657927559'
        - eDMAn: '9'
        - eDMA_source: 'kDmaRequestMuxLPUART5Rx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1726657927560'
        - eDMAn: '8'
        - eDMA_source: 'kDmaRequestMuxLPUART5Tx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART_DmaCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART5_config = {
  .baudRate_Bps = 9600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART5_RX_Handle;
edma_handle_t LPUART5_TX_Handle;
lpuart_edma_handle_t LPUART5_LPUART_eDMA_Handle;

static void LPUART5_init(void) {
  LPUART_Init(LPUART5_PERIPHERAL, &LPUART5_config, LPUART5_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART5Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART5_RX_DMAMUX_BASEADDR, LPUART5_RX_DMA_CHANNEL, LPUART5_RX_DMA_REQUEST);
  /* Enable the channel 9 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART5_RX_DMAMUX_BASEADDR, LPUART5_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART5Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART5_TX_DMAMUX_BASEADDR, LPUART5_TX_DMA_CHANNEL, LPUART5_TX_DMA_REQUEST);
  /* Enable the channel 8 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART5_TX_DMAMUX_BASEADDR, LPUART5_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART5_RX_Handle handle */
  EDMA_CreateHandle(&LPUART5_RX_Handle, LPUART5_RX_DMA_BASEADDR, LPUART5_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART5_TX_Handle handle */
  EDMA_CreateHandle(&LPUART5_TX_Handle, LPUART5_TX_DMA_BASEADDR, LPUART5_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART5_PERIPHERAL, &LPUART5_LPUART_eDMA_Handle, LPUART_DmaCallback, NULL, &LPUART5_TX_Handle, &LPUART5_RX_Handle);
}

/***********************************************************************************************************************
 * LPUART6 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART6'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART6'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '9600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1726657927561'
        - eDMAn: '11'
        - eDMA_source: 'kDmaRequestMuxLPUART6Rx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1726657927562'
        - eDMAn: '10'
        - eDMA_source: 'kDmaRequestMuxLPUART6Tx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART_DmaCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART6_config = {
  .baudRate_Bps = 9600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART6_RX_Handle;
edma_handle_t LPUART6_TX_Handle;
lpuart_edma_handle_t LPUART6_LPUART_eDMA_Handle;

static void LPUART6_init(void) {
  LPUART_Init(LPUART6_PERIPHERAL, &LPUART6_config, LPUART6_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART6Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART6_RX_DMAMUX_BASEADDR, LPUART6_RX_DMA_CHANNEL, LPUART6_RX_DMA_REQUEST);
  /* Enable the channel 11 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART6_RX_DMAMUX_BASEADDR, LPUART6_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART6Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART6_TX_DMAMUX_BASEADDR, LPUART6_TX_DMA_CHANNEL, LPUART6_TX_DMA_REQUEST);
  /* Enable the channel 10 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART6_TX_DMAMUX_BASEADDR, LPUART6_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART6_RX_Handle handle */
  EDMA_CreateHandle(&LPUART6_RX_Handle, LPUART6_RX_DMA_BASEADDR, LPUART6_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART6_TX_Handle handle */
  EDMA_CreateHandle(&LPUART6_TX_Handle, LPUART6_TX_DMA_BASEADDR, LPUART6_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART6_PERIPHERAL, &LPUART6_LPUART_eDMA_Handle, LPUART_DmaCallback, NULL, &LPUART6_TX_Handle, &LPUART6_RX_Handle);
}

/***********************************************************************************************************************
 * LPUART7 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART7'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART7'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '9600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1726657927563'
        - eDMAn: '13'
        - eDMA_source: 'kDmaRequestMuxLPUART7Rx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1726657927564'
        - eDMAn: '12'
        - eDMA_source: 'kDmaRequestMuxLPUART7Tx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART_DmaCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART7_config = {
  .baudRate_Bps = 9600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART7_RX_Handle;
edma_handle_t LPUART7_TX_Handle;
lpuart_edma_handle_t LPUART7_LPUART_eDMA_Handle;

static void LPUART7_init(void) {
  LPUART_Init(LPUART7_PERIPHERAL, &LPUART7_config, LPUART7_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART7Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART7_RX_DMAMUX_BASEADDR, LPUART7_RX_DMA_CHANNEL, LPUART7_RX_DMA_REQUEST);
  /* Enable the channel 13 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART7_RX_DMAMUX_BASEADDR, LPUART7_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART7Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART7_TX_DMAMUX_BASEADDR, LPUART7_TX_DMA_CHANNEL, LPUART7_TX_DMA_REQUEST);
  /* Enable the channel 12 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART7_TX_DMAMUX_BASEADDR, LPUART7_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART7_RX_Handle handle */
  EDMA_CreateHandle(&LPUART7_RX_Handle, LPUART7_RX_DMA_BASEADDR, LPUART7_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART7_TX_Handle handle */
  EDMA_CreateHandle(&LPUART7_TX_Handle, LPUART7_TX_DMA_BASEADDR, LPUART7_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART7_PERIPHERAL, &LPUART7_LPUART_eDMA_Handle, LPUART_DmaCallback, NULL, &LPUART7_TX_Handle, &LPUART7_RX_Handle);
}

/***********************************************************************************************************************
 * LPUART8 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART8'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART8'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '9600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1726657927565'
        - eDMAn: '15'
        - eDMA_source: 'kDmaRequestMuxLPUART8Rx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1726657927566'
        - eDMAn: '14'
        - eDMA_source: 'kDmaRequestMuxLPUART8Tx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART_DmaCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART8_config = {
  .baudRate_Bps = 9600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART8_RX_Handle;
edma_handle_t LPUART8_TX_Handle;
lpuart_edma_handle_t LPUART8_LPUART_eDMA_Handle;

static void LPUART8_init(void) {
  LPUART_Init(LPUART8_PERIPHERAL, &LPUART8_config, LPUART8_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART8Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART8_RX_DMAMUX_BASEADDR, LPUART8_RX_DMA_CHANNEL, LPUART8_RX_DMA_REQUEST);
  /* Enable the channel 15 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART8_RX_DMAMUX_BASEADDR, LPUART8_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART8Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART8_TX_DMAMUX_BASEADDR, LPUART8_TX_DMA_CHANNEL, LPUART8_TX_DMA_REQUEST);
  /* Enable the channel 14 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART8_TX_DMAMUX_BASEADDR, LPUART8_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART8_RX_Handle handle */
  EDMA_CreateHandle(&LPUART8_RX_Handle, LPUART8_RX_DMA_BASEADDR, LPUART8_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART8_TX_Handle handle */
  EDMA_CreateHandle(&LPUART8_TX_Handle, LPUART8_TX_DMA_BASEADDR, LPUART8_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART8_PERIPHERAL, &LPUART8_LPUART_eDMA_Handle, LPUART_DmaCallback, NULL, &LPUART8_TX_Handle, &LPUART8_RX_Handle);
}

/***********************************************************************************************************************
 * TMR1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TMR1'
- type: 'qtmr'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'qtmr_2.0.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TMR1'
- config_sets:
  - fsl_qtmr:
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - qtmr_channels:
      - 0:
        - channel_prefix_id: 'Channel_0'
        - channel: 'kQTMR_Channel_0'
        - primarySource: 'kQTMR_ClockDivide_2'
        - secondarySource: 'kQTMR_Counter0InputPin'
        - countingMode: 'kQTMR_NoOperation'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'pwmOutput'
        - pwmMode:
          - freq_value_str: '62500'
          - dutyCyclePercent: '50'
          - outputPolarity: 'false'
        - dmaIntMode: 'polling'
      - 1:
        - channel_prefix_id: 'Channel_1'
        - channel: 'kQTMR_Channel_1'
        - primarySource: 'kQTMR_ClockDivide_2'
        - secondarySource: 'kQTMR_Counter0InputPin'
        - countingMode: 'kQTMR_NoOperation'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'pwmOutput'
        - pwmMode:
          - freq_value_str: '62500'
          - dutyCyclePercent: '50'
          - outputPolarity: 'false'
        - dmaIntMode: 'polling'
      - 2:
        - channel_prefix_id: 'Channel_2'
        - channel: 'kQTMR_Channel_2'
        - primarySource: 'kQTMR_ClockDivide_2'
        - secondarySource: 'kQTMR_Counter0InputPin'
        - countingMode: 'kQTMR_NoOperation'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'pwmOutput'
        - pwmMode:
          - freq_value_str: '62500'
          - dutyCyclePercent: '50'
          - outputPolarity: 'false'
        - dmaIntMode: 'polling'
      - 3:
        - channel_prefix_id: 'Channel_3'
        - channel: 'kQTMR_Channel_3'
        - primarySource: 'kQTMR_ClockDivide_2'
        - secondarySource: 'kQTMR_Counter0InputPin'
        - countingMode: 'kQTMR_NoOperation'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'pwmOutput'
        - pwmMode:
          - freq_value_str: '62500'
          - dutyCyclePercent: '50'
          - outputPolarity: 'false'
        - dmaIntMode: 'polling'
    - interruptVector:
      - enable_irq: 'false'
      - interrupt:
        - IRQn: 'TMR1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const qtmr_config_t TMR1_Channel_0_config = {
  .primarySource = kQTMR_ClockDivide_2,
  .secondarySource = kQTMR_Counter0InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};
const qtmr_config_t TMR1_Channel_1_config = {
  .primarySource = kQTMR_ClockDivide_2,
  .secondarySource = kQTMR_Counter0InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};
const qtmr_config_t TMR1_Channel_2_config = {
  .primarySource = kQTMR_ClockDivide_2,
  .secondarySource = kQTMR_Counter0InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};
const qtmr_config_t TMR1_Channel_3_config = {
  .primarySource = kQTMR_ClockDivide_2,
  .secondarySource = kQTMR_Counter0InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};

static void TMR1_init(void) {
  /* Quad timer channel Channel_0 peripheral initialization */
  QTMR_Init(TMR1_PERIPHERAL, TMR1_CHANNEL_0_CHANNEL, &TMR1_Channel_0_config);
  /* Setup the PWM mode of the timer channel */
  QTMR_SetupPwm(TMR1_PERIPHERAL, TMR1_CHANNEL_0_CHANNEL, 1000UL, 50U, false, TMR1_CHANNEL_0_CLOCK_SOURCE);
  /* Quad timer channel Channel_1 peripheral initialization */
  QTMR_Init(TMR1_PERIPHERAL, TMR1_CHANNEL_1_CHANNEL, &TMR1_Channel_1_config);
  /* Setup the PWM mode of the timer channel */
  QTMR_SetupPwm(TMR1_PERIPHERAL, TMR1_CHANNEL_1_CHANNEL, 1000UL, 50U, false, TMR1_CHANNEL_1_CLOCK_SOURCE);
  /* Quad timer channel Channel_2 peripheral initialization */
  QTMR_Init(TMR1_PERIPHERAL, TMR1_CHANNEL_2_CHANNEL, &TMR1_Channel_2_config);
  /* Setup the PWM mode of the timer channel */
  QTMR_SetupPwm(TMR1_PERIPHERAL, TMR1_CHANNEL_2_CHANNEL, 1000UL, 50U, false, TMR1_CHANNEL_2_CLOCK_SOURCE);
  /* Quad timer channel Channel_3 peripheral initialization */
  QTMR_Init(TMR1_PERIPHERAL, TMR1_CHANNEL_3_CHANNEL, &TMR1_Channel_3_config);
  /* Setup the PWM mode of the timer channel */
  QTMR_SetupPwm(TMR1_PERIPHERAL, TMR1_CHANNEL_3_CHANNEL, 1000UL, 50U, false, TMR1_CHANNEL_3_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * TMR2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TMR2'
- type: 'qtmr'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'qtmr_2.0.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TMR2'
- config_sets:
  - fsl_qtmr:
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - qtmr_channels:
      - 0:
        - channel_prefix_id: 'Channel_0'
        - channel: 'kQTMR_Channel_0'
        - primarySource: 'kQTMR_ClockDivide_2'
        - secondarySource: 'kQTMR_Counter0InputPin'
        - countingMode: 'kQTMR_NoOperation'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'pwmOutput'
        - pwmMode:
          - freq_value_str: '62500'
          - dutyCyclePercent: '50'
          - outputPolarity: 'false'
        - dmaIntMode: 'polling'
      - 1:
        - channel_prefix_id: 'Channel_1'
        - channel: 'kQTMR_Channel_1'
        - primarySource: 'kQTMR_ClockDivide_2'
        - secondarySource: 'kQTMR_Counter0InputPin'
        - countingMode: 'kQTMR_NoOperation'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'pwmOutput'
        - pwmMode:
          - freq_value_str: '62500'
          - dutyCyclePercent: '50'
          - outputPolarity: 'false'
        - dmaIntMode: 'polling'
      - 2:
        - channel_prefix_id: 'Channel_2'
        - channel: 'kQTMR_Channel_2'
        - primarySource: 'kQTMR_ClockDivide_2'
        - secondarySource: 'kQTMR_Counter0InputPin'
        - countingMode: 'kQTMR_NoOperation'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'pwmOutput'
        - pwmMode:
          - freq_value_str: '3125'
          - dutyCyclePercent: '50'
          - outputPolarity: 'false'
        - dmaIntMode: 'polling'
    - interruptVector:
      - enable_irq: 'false'
      - interrupt:
        - IRQn: 'TMR2_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const qtmr_config_t TMR2_Channel_0_config = {
  .primarySource = kQTMR_ClockDivide_2,
  .secondarySource = kQTMR_Counter0InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};
const qtmr_config_t TMR2_Channel_1_config = {
  .primarySource = kQTMR_ClockDivide_2,
  .secondarySource = kQTMR_Counter0InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};
const qtmr_config_t TMR2_Channel_2_config = {
  .primarySource = kQTMR_ClockDivide_2,
  .secondarySource = kQTMR_Counter0InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};

static void TMR2_init(void) {
  /* Quad timer channel Channel_0 peripheral initialization */
  QTMR_Init(TMR2_PERIPHERAL, TMR2_CHANNEL_0_CHANNEL, &TMR2_Channel_0_config);
  /* Setup the PWM mode of the timer channel */
  QTMR_SetupPwm(TMR2_PERIPHERAL, TMR2_CHANNEL_0_CHANNEL, 1000UL, 50U, false, TMR2_CHANNEL_0_CLOCK_SOURCE);
  /* Quad timer channel Channel_1 peripheral initialization */
  QTMR_Init(TMR2_PERIPHERAL, TMR2_CHANNEL_1_CHANNEL, &TMR2_Channel_1_config);
  /* Setup the PWM mode of the timer channel */
  QTMR_SetupPwm(TMR2_PERIPHERAL, TMR2_CHANNEL_1_CHANNEL, 1000UL, 50U, false, TMR2_CHANNEL_1_CLOCK_SOURCE);
  /* Quad timer channel Channel_2 peripheral initialization */
  QTMR_Init(TMR2_PERIPHERAL, TMR2_CHANNEL_2_CHANNEL, &TMR2_Channel_2_config);
  /* Setup the PWM mode of the timer channel */
  QTMR_SetupPwm(TMR2_PERIPHERAL, TMR2_CHANNEL_2_CHANNEL, 20000UL, 50U, false, TMR2_CHANNEL_2_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * EEPROM_I2C initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'EEPROM_I2C'
- type: 'lpi2c'
- mode: 'master'
- custom_name_enabled: 'true'
- type_id: 'lpi2c_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C1'
- config_sets:
  - main:
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
  - interrupt_vector: []
  - master:
    - mode: 'freertos'
    - config:
      - enableMaster: 'false'
      - enableDoze: 'false'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '100000'
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - edmaRequestSources: 'enableRx enableTx'
    - transfer:
      - enable_custom_handle: 'false'
      - flags: ''
      - slaveAddress: '80'
      - direction: 'kLPI2C_Write'
      - subaddress: '0'
      - subaddressSize: '2'
      - blocking_buffer: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t EEPROM_I2C_masterConfig = {
  .enableMaster = false,
  .enableDoze = false,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 100000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
lpi2c_master_transfer_t EEPROM_I2C_masterTransfer = {
  .flags = kLPI2C_TransferDefaultFlag,
  .slaveAddress = 80,
  .direction = kLPI2C_Write,
  .subaddress = 0,
  .subaddressSize = 2,
  .data = NULL,
  .dataSize = 0
};
lpi2c_rtos_handle_t EEPROM_I2C_masterHandle;

void EEPROM_I2C_init(void) {
  LPI2C_RTOS_Init(&EEPROM_I2C_masterHandle, EEPROM_I2C_PERIPHERAL, &EEPROM_I2C_masterConfig, EEPROM_I2C_CLOCK_FREQ);
  /* Enable Leader eDMA request sources: Tx, Rx */
  LPI2C_MasterEnableDMA(EEPROM_I2C_PERIPHERAL, true, true);
}

/***********************************************************************************************************************
 * lwIP initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'lwIP'
- type: 'lwip'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lwip_2.2.1-rev1'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - lwip_config:
    - mode: 'freertos'
    - LWIP_NETIF_API: 'true'
    - LWIP_NETCONN: 'true'
    - LWIP_SOCKET: 'true'
    - LWIP_SO_RCVTIMEO: 'true'
    - LWIP_TCPIP_CORE_LOCKING: 'true'
    - MEM_SIZE: '(12 * 1024)'
    - MEMP_NUM_PBUF: '16'
    - MEMP_NUM_UDP_PCB: '6'
    - MEMP_NUM_TCP_PCB: '10'
    - MEMP_NUM_TCP_PCB_LISTEN: '10'
    - MEMP_NUM_TCP_SEG: '22'
    - MEMP_NUM_SYS_TIMEOUT: '5'
    - MEMP_NUM_REASSDATA: '2'
    - PBUF_POOL_SIZE: '10'
    - LWIP_SINGLE_NETIF: 'true'
    - LWIP_IPV4: 'true'
    - IP_FORWARD: 'false'
    - IP_REASSEMBLY: 'true'
    - IP_REASS_MAX_PBUFS: '4'
    - IP_FRAG: 'true'
    - IP_DEFAULT_TTL: '255'
    - LWIP_ARP: 'true'
    - LWIP_ICMP: 'true'
    - ICMP_TTL: 'IP_DEFAULT_TTL'
    - LWIP_BROADCAST_PING: 'true'
    - LWIP_MULTICAST_PING: 'true'
    - LWIP_IGMP: 'false'
    - LWIP_DHCP: 'false'
    - LWIP_DHCP_DOES_ACD_CHECK: 'true'
    - LWIP_IPV6: 'false'
    - LWIP_IPV6_NUM_ADDRESSES: '3'
    - LWIP_IPV6_AUTOCONFIG: 'true'
    - LWIP_IPV6_DHCP6: 'false'
    - LWIP_RAW: 'false'
    - RAW_TTL: 'IP_DEFAULT_TTL'
    - LWIP_TCP: 'true'
    - TCP_TTL: 'IP_DEFAULT_TTL'
    - TCP_QUEUE_OOSEQ: 'false'
    - TCP_MSS: '(1500 - 40)'
    - TCP_SND_BUF: '(6 * TCP_MSS)'
    - TCP_SND_QUEUELEN: '(3 * TCP_SND_BUF) / TCP_MSS'
    - TCP_WND: '(6 * TCP_MSS)'
    - TCP_LISTEN_BACKLOG: 'true'
    - TCP_DEFAULT_LISTEN_BACKLOG: '5'
    - LWIP_UDP: 'false'
    - UDP_TTL: 'IP_DEFAULT_TTL'
    - LWIP_STATS: 'false'
    - LWIP_PROVIDE_ERRNO: 'true'
    - CHECKSUM_BY_HARDWARE: 'true'
    - LWIP_DEBUG: 'false'
    - DEFAULT_THREAD_STACKSIZE: '512'
    - DEFAULT_THREAD_PRIO: '3'
    - TCPIP_MBOX_SIZE: '32'
    - TCPIP_THREAD_STACKSIZE: '1024'
    - TCPIP_THREAD_PRIO: '8'
    - DEFAULT_TCP_RECVMBOX_SIZE: '12'
    - DEFAULT_ACCEPTMBOX_SIZE: '12'
    - custom_opts: ''
    - modules_include: ''
    - mpu_init:
      - mpu_init_component: 'MPU'
    - user_preinit: 'false'
    - user_init:
      - initFunctionID: 'lwIP_interface_init'
    - lwip_init: 'false'
    - ifConfig:
      - 0:
        - ethernetif_config_struct: []
        - netif_id: 'netif0'
        - interface: 'enet'
        - netif_mode: 'ipv4'
        - ip_assignment: 'static'
        - ipv4Config:
          - ip_addr:
            - addr: '172.168.1.151'
          - netmask:
            - addr: '255.255.255.0'
          - gateway:
            - addr: '172.168.1.1'
        - netif_function_name: 'defaultFn'
        - netif_input_function_name: 'defaultInputFn'
        - mac_address:
          - useSiliconId: 'true'
          - addr: 'FF-FF-FF-FF-FF-FF'
        - link_timeout: '5000'
        - phyConfig:
          - phy_driver: 'phyksz8081'
          - phy_addr: '0x02'
          - mdioConfig:
            - mdioResources: []
            - MDIO_init: 'true'
            - mdio_write: 'MDIO_Write'
            - mdio_read: 'MDIO_Read'
            - enetConfig:
              - peripheralSelect: 'ENET'
              - timing:
                - globalClockConfig:
                  - clockSource: 'GlobalClock'
                  - clockSourceFreq: 'ClocksTool_DefaultInit'
              - enet_config:
                - phyTiming:
                  - refClockConfig:
                    - clockSource: 'EnetRefClock'
                    - clockSourceFreq: 'ClocksTool_DefaultInit'
              - enableUserInit: 'false'
              - user_init:
                - initFunctionID: 'hal_enet_init'
    - lwip_codegenerator: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* IPv4 adress, netmask and gateway handle */
ip4_addr_t lwIP_netif0_ipaddr, lwIP_netif0_netmask, lwIP_netif0_gw;
/* Network interface structure */
struct netif lwIP_netif0;
/* PHY handle */
static phy_handle_t lwIP_netif0_phy_handle;
phy_ksz8081_resource_t lwIP_netif0_phy_resource = {
  .write = MDIO_Write,
  .read = MDIO_Read
};

ethernetif_config_t lwIP_netif0_enet_config = {
  .phyHandle = &lwIP_netif0_phy_handle,
  .phyAddr = LWIP_NETIF0_PHY_ADDRESS,
  .phyOps = LWIP_NETIF0_PHY_OPS,
  .phyResource = LWIP_NETIF0_PHY_RESOURCE,
  .srcClockHz = LWIP_NETIF0_ENET_PERIPHERAL_CLK_FREQ,
#ifdef LWIP_NETIF0_MAC_ADDRESS
  .macAddress = LWIP_NETIF0_MAC_ADDRESS,
#endif
};

static void lwIP_init(void) {
  /* lwIP IP address initialization */
  IP4_ADDR(&lwIP_netif0_ipaddr, LWIP_NETIF0_IPADDR0, LWIP_NETIF0_IPADDR1, LWIP_NETIF0_IPADDR2, LWIP_NETIF0_IPADDR3);
  /* lwIP netmask initialization */
  IP4_ADDR(&lwIP_netif0_netmask, LWIP_NETIF0_NETMASK0, LWIP_NETIF0_NETMASK1, LWIP_NETIF0_NETMASK2, LWIP_NETIF0_NETMASK3);
  /* lwIP gateway initialization */
  IP4_ADDR(&lwIP_netif0_gw, LWIP_NETIF0_GW0, LWIP_NETIF0_GW1, LWIP_NETIF0_GW2, LWIP_NETIF0_GW3);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  ARM_MPU_Disable();
  DMAMUX_Init(DMA0_DMAMUX_BASEADDR);
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);

  /* Initialize components */
  DMA0_init();
  CHARGE_CAN_A_init();
  CHARGE_CAN_B_init();
  LPUART1_init();
  EXT_RTC_I2C_init();
  ADC1_init();
  LPUART2_init();
  LPUART3_init();
  LPUART4_init();
  LPUART5_init();
  LPUART6_init();
  LPUART7_init();
  LPUART8_init();
  TMR1_init();
  TMR2_init();
  EEPROM_I2C_init();
  lwIP_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}

void ReconfigUart6(void)
{
	LPUART6_init();
}
void ReconfigUart7(void)
{
	LPUART7_init();
}
