/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "fsl_flexcan.h"
#include "fsl_clock.h"
#include "fsl_lpuart.h"
#include "fsl_lpuart_edma.h"
#include "fsl_lpi2c.h"
#include "fsl_lpi2c_freertos.h"
#include "fsl_adc.h"
#include "fsl_qtmr.h"
#include "lwip/opt.h"
#include "lwip/netifapi.h"
#include "lwip/sys.h"
#include "lwip/sockets.h"
#include "lwip/api.h"
#include "lwip/icmp.h"
#include "lwip/errno.h"
#include "ethernetif.h"
#include "fsl_enet.h"
#include "fsl_phyksz8081.h"
#include "fsl_silicon_id.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA0_DMAMUX_BASEADDR DMAMUX
/* Definition of peripheral ID */
#define CHARGE_CAN_A_PERIPHERAL CAN1
/* Definition of the clock source frequency */
#define CHARGE_CAN_A_CLOCK_SOURCE 60000000UL
/* CHARGE_CAN_A interrupt vector ID (number). */
#define CHARGE_CAN_A_FLEXCAN_IRQN CAN1_IRQn
/* CHARGE_CAN_A interrupt vector priority. */
#define CHARGE_CAN_A_FLEXCAN_IRQ_PRIORITY 2
/* CHARGE_CAN_A interrupt handler identifier. */
#define Charge_CAN_A_IRQhandler CAN1_IRQHandler
/* Definition of peripheral ID */
#define CHARGE_CAN_B_PERIPHERAL CAN2
/* Definition of the clock source frequency */
#define CHARGE_CAN_B_CLOCK_SOURCE 60000000UL
/* CHARGE_CAN_B interrupt vector ID (number). */
#define CHARGE_CAN_B_FLEXCAN_IRQN CAN2_IRQn
/* CHARGE_CAN_B interrupt vector priority. */
#define CHARGE_CAN_B_FLEXCAN_IRQ_PRIORITY 2
/* CHARGE_CAN_B interrupt handler identifier. */
#define Charge_CAN_B_IRQhandler CAN2_IRQHandler
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART1_CLOCK_SOURCE 80000000UL
/* LPUART1 eDMA source request. */
#define LPUART1_RX_DMA_REQUEST kDmaRequestMuxLPUART1Rx
/* Selected eDMA channel number. */
#define LPUART1_RX_DMA_CHANNEL 1
/* DMAMUX device that is used for muxing of the request. */
#define LPUART1_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART1_RX_DMA_BASEADDR DMA0
/* LPUART1 eDMA source request. */
#define LPUART1_TX_DMA_REQUEST kDmaRequestMuxLPUART1Tx
/* Selected eDMA channel number. */
#define LPUART1_TX_DMA_CHANNEL 0
/* DMAMUX device that is used for muxing of the request. */
#define LPUART1_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART1_TX_DMA_BASEADDR DMA0
/* BOARD_InitPeripherals defines for LPI2C3 */
/* Definition of peripheral ID */
#define EXT_RTC_I2C_PERIPHERAL LPI2C3
/* Definition of clock source */
#define EXT_RTC_I2C_CLOCK_FREQ 60000000UL
/* Definition of follower address */
#define EXT_RTC_I2C_MASTER_SLAVE_ADDRESS 51
/* BOARD_InitPeripherals defines for ADC1 */
/* Definition of peripheral ID */
#define ADC1_PERIPHERAL ADC1
/* Definition of special channel interconnected with ADC_ETC which takes real channel to be measured from ADC_ETC. */
#define ADC1_CHANNEL_DRIVEN_BY_ADC_ETC 16U
/* Channel 0 (IN.10) conversion control group. */
#define ADC1_CH0_CONTROL_GROUP 0U
/* Channel 1 (IN.11) conversion control group. */
#define ADC1_CH1_CONTROL_GROUP 0U
/* Channel 2 (IN.12) conversion control group. */
#define ADC1_CH2_CONTROL_GROUP 0U
/* Channel 3 (IN.13) conversion control group. */
#define ADC1_CH3_CONTROL_GROUP 0U
/* Channel 4 (IN.14) conversion control group. */
#define ADC1_CH4_CONTROL_GROUP 0U
/* Channel 5 (IN.15) conversion control group. */
#define ADC1_CH5_CONTROL_GROUP 0U
/* Definition of peripheral ID */
#define LPUART2_PERIPHERAL LPUART2
/* Definition of the clock source frequency */
#define LPUART2_CLOCK_SOURCE 80000000UL
/* LPUART2 eDMA source request. */
#define LPUART2_RX_DMA_REQUEST kDmaRequestMuxLPUART2Rx
/* Selected eDMA channel number. */
#define LPUART2_RX_DMA_CHANNEL 3
/* DMAMUX device that is used for muxing of the request. */
#define LPUART2_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART2_RX_DMA_BASEADDR DMA0
/* LPUART2 eDMA source request. */
#define LPUART2_TX_DMA_REQUEST kDmaRequestMuxLPUART2Tx
/* Selected eDMA channel number. */
#define LPUART2_TX_DMA_CHANNEL 2
/* DMAMUX device that is used for muxing of the request. */
#define LPUART2_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART2_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define LPUART3_PERIPHERAL LPUART3
/* Definition of the clock source frequency */
#define LPUART3_CLOCK_SOURCE 80000000UL
/* LPUART3 eDMA source request. */
#define LPUART3_RX_DMA_REQUEST kDmaRequestMuxLPUART3Rx
/* Selected eDMA channel number. */
#define LPUART3_RX_DMA_CHANNEL 5
/* DMAMUX device that is used for muxing of the request. */
#define LPUART3_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART3_RX_DMA_BASEADDR DMA0
/* LPUART3 eDMA source request. */
#define LPUART3_TX_DMA_REQUEST kDmaRequestMuxLPUART3Tx
/* Selected eDMA channel number. */
#define LPUART3_TX_DMA_CHANNEL 4
/* DMAMUX device that is used for muxing of the request. */
#define LPUART3_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART3_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define LPUART4_PERIPHERAL LPUART4
/* Definition of the clock source frequency */
#define LPUART4_CLOCK_SOURCE 80000000UL
/* LPUART4 eDMA source request. */
#define LPUART4_RX_DMA_REQUEST kDmaRequestMuxLPUART4Rx
/* Selected eDMA channel number. */
#define LPUART4_RX_DMA_CHANNEL 7
/* DMAMUX device that is used for muxing of the request. */
#define LPUART4_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART4_RX_DMA_BASEADDR DMA0
/* LPUART4 eDMA source request. */
#define LPUART4_TX_DMA_REQUEST kDmaRequestMuxLPUART4Tx
/* Selected eDMA channel number. */
#define LPUART4_TX_DMA_CHANNEL 6
/* DMAMUX device that is used for muxing of the request. */
#define LPUART4_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART4_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define LPUART5_PERIPHERAL LPUART5
/* Definition of the clock source frequency */
#define LPUART5_CLOCK_SOURCE 80000000UL
/* LPUART5 eDMA source request. */
#define LPUART5_RX_DMA_REQUEST kDmaRequestMuxLPUART5Rx
/* Selected eDMA channel number. */
#define LPUART5_RX_DMA_CHANNEL 9
/* DMAMUX device that is used for muxing of the request. */
#define LPUART5_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART5_RX_DMA_BASEADDR DMA0
/* LPUART5 eDMA source request. */
#define LPUART5_TX_DMA_REQUEST kDmaRequestMuxLPUART5Tx
/* Selected eDMA channel number. */
#define LPUART5_TX_DMA_CHANNEL 8
/* DMAMUX device that is used for muxing of the request. */
#define LPUART5_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART5_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define LPUART6_PERIPHERAL LPUART6
/* Definition of the clock source frequency */
#define LPUART6_CLOCK_SOURCE 80000000UL
/* LPUART6 eDMA source request. */
#define LPUART6_RX_DMA_REQUEST kDmaRequestMuxLPUART6Rx
/* Selected eDMA channel number. */
#define LPUART6_RX_DMA_CHANNEL 11
/* DMAMUX device that is used for muxing of the request. */
#define LPUART6_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART6_RX_DMA_BASEADDR DMA0
/* LPUART6 eDMA source request. */
#define LPUART6_TX_DMA_REQUEST kDmaRequestMuxLPUART6Tx
/* Selected eDMA channel number. */
#define LPUART6_TX_DMA_CHANNEL 10
/* DMAMUX device that is used for muxing of the request. */
#define LPUART6_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART6_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define LPUART7_PERIPHERAL LPUART7
/* Definition of the clock source frequency */
#define LPUART7_CLOCK_SOURCE 80000000UL
/* LPUART7 eDMA source request. */
#define LPUART7_RX_DMA_REQUEST kDmaRequestMuxLPUART7Rx
/* Selected eDMA channel number. */
#define LPUART7_RX_DMA_CHANNEL 13
/* DMAMUX device that is used for muxing of the request. */
#define LPUART7_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART7_RX_DMA_BASEADDR DMA0
/* LPUART7 eDMA source request. */
#define LPUART7_TX_DMA_REQUEST kDmaRequestMuxLPUART7Tx
/* Selected eDMA channel number. */
#define LPUART7_TX_DMA_CHANNEL 12
/* DMAMUX device that is used for muxing of the request. */
#define LPUART7_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART7_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define LPUART8_PERIPHERAL LPUART8
/* Definition of the clock source frequency */
#define LPUART8_CLOCK_SOURCE 80000000UL
/* LPUART8 eDMA source request. */
#define LPUART8_RX_DMA_REQUEST kDmaRequestMuxLPUART8Rx
/* Selected eDMA channel number. */
#define LPUART8_RX_DMA_CHANNEL 15
/* DMAMUX device that is used for muxing of the request. */
#define LPUART8_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART8_RX_DMA_BASEADDR DMA0
/* LPUART8 eDMA source request. */
#define LPUART8_TX_DMA_REQUEST kDmaRequestMuxLPUART8Tx
/* Selected eDMA channel number. */
#define LPUART8_TX_DMA_CHANNEL 14
/* DMAMUX device that is used for muxing of the request. */
#define LPUART8_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART8_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define TMR1_PERIPHERAL TMR1
/* Definition of the timer channel Channel_0. */
#define TMR1_CHANNEL_0_CHANNEL kQTMR_Channel_0
/* Definition of the timer channel Channel_1. */
#define TMR1_CHANNEL_1_CHANNEL kQTMR_Channel_1
/* Definition of the timer channel Channel_2. */
#define TMR1_CHANNEL_2_CHANNEL kQTMR_Channel_2
/* Definition of the timer channel Channel_3. */
#define TMR1_CHANNEL_3_CHANNEL kQTMR_Channel_3
/* Definition of the timer channel Channel_0 clock source frequency. */
#define TMR1_CHANNEL_0_CLOCK_SOURCE 62500000UL
/* Definition of the timer channel Channel_1 clock source frequency. */
#define TMR1_CHANNEL_1_CLOCK_SOURCE 62500000UL
/* Definition of the timer channel Channel_2 clock source frequency. */
#define TMR1_CHANNEL_2_CLOCK_SOURCE 62500000UL
/* Definition of the timer channel Channel_3 clock source frequency. */
#define TMR1_CHANNEL_3_CLOCK_SOURCE 62500000UL
/* Definition of peripheral ID */
#define TMR2_PERIPHERAL TMR2
/* Definition of the timer channel Channel_0. */
#define TMR2_CHANNEL_0_CHANNEL kQTMR_Channel_0
/* Definition of the timer channel Channel_1. */
#define TMR2_CHANNEL_1_CHANNEL kQTMR_Channel_1
/* Definition of the timer channel Channel_2. */
#define TMR2_CHANNEL_2_CHANNEL kQTMR_Channel_2
/* Definition of the timer channel Channel_0 clock source frequency. */
#define TMR2_CHANNEL_0_CLOCK_SOURCE 62500000UL
/* Definition of the timer channel Channel_1 clock source frequency. */
#define TMR2_CHANNEL_1_CLOCK_SOURCE 62500000UL
/* Definition of the timer channel Channel_2 clock source frequency. */
#define TMR2_CHANNEL_2_CLOCK_SOURCE 62500000UL
/* BOARD_InitPeripherals defines for LPI2C1 */
/* Definition of peripheral ID */
#define EEPROM_I2C_PERIPHERAL LPI2C1
/* Definition of clock source */
#define EEPROM_I2C_CLOCK_FREQ 60000000UL
/* Definition of follower address */
#define EEPROM_I2C_MASTER_SLAVE_ADDRESS 80
/* @TEST_ANCHOR */
/* Definition of peripheral ID */
#define LWIP_NETIF0_ENET_PERIPHERAL ENET
/* Ethernet peripheral clock frequency */
#define LWIP_NETIF0_ENET_PERIPHERAL_CLK_FREQ 125000000UL
/* IP address definitions */
#ifndef LWIP_NETIF0_IPADDR0
#define LWIP_NETIF0_IPADDR0 172U
#endif
#ifndef LWIP_NETIF0_IPADDR1
#define LWIP_NETIF0_IPADDR1 168U
#endif
#ifndef LWIP_NETIF0_IPADDR2
#define LWIP_NETIF0_IPADDR2 1U
#endif
#ifndef LWIP_NETIF0_IPADDR3
#define LWIP_NETIF0_IPADDR3 151U
#endif
/* Subnet mask definitions */
#ifndef LWIP_NETIF0_NETMASK0
#define LWIP_NETIF0_NETMASK0 255U
#endif
#ifndef LWIP_NETIF0_NETMASK1
#define LWIP_NETIF0_NETMASK1 255U
#endif
#ifndef LWIP_NETIF0_NETMASK2
#define LWIP_NETIF0_NETMASK2 255U
#endif
#ifndef LWIP_NETIF0_NETMASK3
#define LWIP_NETIF0_NETMASK3 0U
#endif
/* Default gateway definitions */
#ifndef LWIP_NETIF0_GW0
#define LWIP_NETIF0_GW0 172U
#endif
#ifndef LWIP_NETIF0_GW1
#define LWIP_NETIF0_GW1 168U
#endif
#ifndef LWIP_NETIF0_GW2
#define LWIP_NETIF0_GW2 1U
#endif
#ifndef LWIP_NETIF0_GW3
#define LWIP_NETIF0_GW3 1U
#endif
/* PHY address definition */
#ifndef LWIP_NETIF0_PHY_ADDRESS
#define LWIP_NETIF0_PHY_ADDRESS 0x02
#endif
/* PHY options definition */
#define LWIP_NETIF0_PHY_OPS &phyksz8081_ops
/* PHY resource definition */
#define LWIP_NETIF0_PHY_RESOURCE &lwIP_netif0_phy_resource

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA0_config;
extern const flexcan_config_t CHARGE_CAN_A_config;
/* Message buffer 16 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_16;
/* Message buffer 17 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_17;
/* Message buffer 18 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_18;
/* Message buffer 19 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_19;
/* Message buffer 20 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_20;
/* Message buffer 21 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_21;
/* Message buffer 22 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_22;
/* Message buffer 23 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_23;
/* Message buffer 24 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_24;
/* Message buffer 25 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_25;
/* Message buffer 26 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_26;
/* Message buffer 27 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_27;
/* Message buffer 28 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_28;
/* Message buffer 29 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_29;
/* Message buffer 30 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_30;
/* Message buffer 31 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_A_rx_mb_config_31;
extern const flexcan_config_t CHARGE_CAN_B_config;
/* Message buffer 48 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_48;
/* Message buffer 49 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_49;
/* Message buffer 50 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_50;
/* Message buffer 51 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_51;
/* Message buffer 52 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_52;
/* Message buffer 53 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_53;
/* Message buffer 54 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_54;
/* Message buffer 55 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_55;
/* Message buffer 56 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_56;
/* Message buffer 57 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_57;
/* Message buffer 58 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_58;
/* Message buffer 59 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_59;
/* Message buffer 60 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_60;
/* Message buffer 61 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_61;
/* Message buffer 62 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_62;
/* Message buffer 63 configuration structure */
extern const flexcan_rx_mb_config_t CHARGE_CAN_B_rx_mb_config_63;
extern const lpuart_config_t LPUART1_config;
extern edma_handle_t LPUART1_RX_Handle;
extern edma_handle_t LPUART1_TX_Handle;
extern lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;
extern const lpi2c_master_config_t EXT_RTC_I2C_masterConfig;
extern lpi2c_master_transfer_t EXT_RTC_I2C_masterTransfer;
extern lpi2c_rtos_handle_t EXT_RTC_I2C_masterHandle;
extern const adc_config_t ADC1_config;
extern const adc_channel_config_t ADC1_channels_config[6];
extern const lpuart_config_t LPUART2_config;
extern edma_handle_t LPUART2_RX_Handle;
extern edma_handle_t LPUART2_TX_Handle;
extern lpuart_edma_handle_t LPUART2_LPUART_eDMA_Handle;
extern const lpuart_config_t LPUART3_config;
extern edma_handle_t LPUART3_RX_Handle;
extern edma_handle_t LPUART3_TX_Handle;
extern lpuart_edma_handle_t LPUART3_LPUART_eDMA_Handle;
extern const lpuart_config_t LPUART4_config;
extern edma_handle_t LPUART4_RX_Handle;
extern edma_handle_t LPUART4_TX_Handle;
extern lpuart_edma_handle_t LPUART4_LPUART_eDMA_Handle;
extern const lpuart_config_t LPUART5_config;
extern edma_handle_t LPUART5_RX_Handle;
extern edma_handle_t LPUART5_TX_Handle;
extern lpuart_edma_handle_t LPUART5_LPUART_eDMA_Handle;
extern const lpuart_config_t LPUART6_config;
extern edma_handle_t LPUART6_RX_Handle;
extern edma_handle_t LPUART6_TX_Handle;
extern lpuart_edma_handle_t LPUART6_LPUART_eDMA_Handle;
extern const lpuart_config_t LPUART7_config;
extern edma_handle_t LPUART7_RX_Handle;
extern edma_handle_t LPUART7_TX_Handle;
extern lpuart_edma_handle_t LPUART7_LPUART_eDMA_Handle;
extern const lpuart_config_t LPUART8_config;
extern edma_handle_t LPUART8_RX_Handle;
extern edma_handle_t LPUART8_TX_Handle;
extern lpuart_edma_handle_t LPUART8_LPUART_eDMA_Handle;
extern const qtmr_config_t TMR1_Channel_0_config;
extern const qtmr_config_t TMR1_Channel_1_config;
extern const qtmr_config_t TMR1_Channel_2_config;
extern const qtmr_config_t TMR1_Channel_3_config;
extern const qtmr_config_t TMR2_Channel_0_config;
extern const qtmr_config_t TMR2_Channel_1_config;
extern const qtmr_config_t TMR2_Channel_2_config;
extern const lpi2c_master_config_t EEPROM_I2C_masterConfig;
extern lpi2c_master_transfer_t EEPROM_I2C_masterTransfer;
extern lpi2c_rtos_handle_t EEPROM_I2C_masterHandle;
/* Network interface structure */
extern struct netif lwIP_netif0;
/* Ethernet interface configuration */
extern ethernetif_config_t lwIP_netif0_enet_config;
/* IPv4 adress handle */
extern ip4_addr_t lwIP_netif0_ipaddr;
/* IPv4 netmask handle */
extern ip4_addr_t lwIP_netif0_netmask;
/* IPv4 gateway handle */
extern ip4_addr_t lwIP_netif0_gw;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* LPUART eDMA callback function for the LPUART1 component (init. function BOARD_InitPeripherals)*/
extern void LPUART_DmaCallback(LPUART_Type *,lpuart_edma_handle_t *,status_t ,void *);
/* LPUART eDMA callback function for the LPUART2 component (init. function BOARD_InitPeripherals)*/
extern void LPUART_DmaCallback(LPUART_Type *,lpuart_edma_handle_t *,status_t ,void *);
/* LPUART eDMA callback function for the LPUART3 component (init. function BOARD_InitPeripherals)*/
extern void LPUART_DmaCallback(LPUART_Type *,lpuart_edma_handle_t *,status_t ,void *);
/* LPUART eDMA callback function for the LPUART4 component (init. function BOARD_InitPeripherals)*/
extern void LPUART_DmaCallback(LPUART_Type *,lpuart_edma_handle_t *,status_t ,void *);
/* LPUART eDMA callback function for the LPUART5 component (init. function BOARD_InitPeripherals)*/
extern void LPUART_DmaCallback(LPUART_Type *,lpuart_edma_handle_t *,status_t ,void *);
/* LPUART eDMA callback function for the LPUART6 component (init. function BOARD_InitPeripherals)*/
extern void LPUART_DmaCallback(LPUART_Type *,lpuart_edma_handle_t *,status_t ,void *);
/* LPUART eDMA callback function for the LPUART7 component (init. function BOARD_InitPeripherals)*/
extern void LPUART_DmaCallback(LPUART_Type *,lpuart_edma_handle_t *,status_t ,void *);
/* LPUART eDMA callback function for the LPUART8 component (init. function BOARD_InitPeripherals)*/
extern void LPUART_DmaCallback(LPUART_Type *,lpuart_edma_handle_t *,status_t ,void *);
/* MDIO write callback function*/
extern status_t MDIO_Write(uint8_t phyAddr, uint8_t regAddr, uint16_t data);
/* MDIO read callback function*/
extern status_t MDIO_Read(uint8_t phyAddr, uint8_t regAddr, uint16_t *data);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);
void EEPROM_I2C_init(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);
void ReconfigUart6(void);
void ReconfigUart7(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
