/*
 * hal_sys_IF.h
 *
 *  Created on: 2024年9月5日
 *      Author: Bono
 */

#ifndef HAL_HAL_SYS_HAL_SYS_IF_H_
#define HAL_HAL_SYS_HAL_SYS_IF_H_

#include "clock_config.h"
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "pin_mux.h"
#include "SignalManage.h"
#include "PublicDefine.h"



#define LOGIC_LED_ON            (0U)
#define LOGIC_LED_OFF           (1U)
#define WATCHDOG_INTERVAL_MS    (10U)   // 喂狗周期10ms
#ifndef USER_LED_GPIO
#define USER_LED_GPIO GPIO1
#endif
#ifndef USER_LED_GPIO_PIN
#define USER_LED_GPIO_PIN       (5U)
#endif



#define USER_LED_ON()		    GPIO_PortClear(USER_LED_GPIO, 1U << USER_LED_GPIO_PIN)
#define USER_LED_OFF()		    GPIO_PortSet(USER_LED_GPIO, 1U << USER_LED_GPIO_PIN)
#define USER_LED_TOGGLE()	    GPIO_PinWrite(USER_LED_GPIO, USER_LED_GPIO_PIN, 0x1 ^ GPIO_PinRead(USER_LED_GPIO, USER_LED_GPIO_PIN))

#define LED1_ON()			    GPIO_PortClear(BOARD_INITPINS_LED1_GPIO, 1U << BOARD_INITPINS_LED1_GPIO_PIN)
#define LED1_OFF()			    GPIO_PortSet(BOARD_INITPINS_LED1_GPIO, 1U << BOARD_INITPINS_LED1_GPIO_PIN)
#define LED1_TOGGLE()		    GPIO_PinWrite(BOARD_INITPINS_LED1_GPIO, BOARD_INITPINS_LED1_GPIO_PIN, 0x1 ^ GPIO_PinRead(BOARD_INITPINS_LED1_GPIO, BOARD_INITPINS_LED1_GPIO_PIN))

#define LED2_ON()			    GPIO_PortClear(BOARD_INITPINS_LED2_GPIO, 1U << BOARD_INITPINS_LED2_GPIO_PIN)
#define LED2_OFF()			    GPIO_PortSet(BOARD_INITPINS_LED2_GPIO, 1U << BOARD_INITPINS_LED2_GPIO_PIN)
#define LED2_TOGGLE()		    GPIO_PinWrite(BOARD_INITPINS_LED2_GPIO, BOARD_INITPINS_LED2_GPIO_PIN, 0x1 ^ GPIO_PinRead(BOARD_INITPINS_LED2_GPIO, BOARD_INITPINS_LED2_GPIO_PIN))

#define LED3_ON()			    GPIO_PortClear(BOARD_INITPINS_LED3_GPIO, 1U << BOARD_INITPINS_LED3_GPIO_PIN)
#define LED3_OFF()			    GPIO_PortSet(BOARD_INITPINS_LED3_GPIO, 1U << BOARD_INITPINS_LED3_GPIO_PIN)
#define LED3_TOGGLE()		    GPIO_PinWrite(BOARD_INITPINS_LED3_GPIO, BOARD_INITPINS_LED3_GPIO_PIN, 0x1 ^ GPIO_PinRead(BOARD_INITPINS_LED3_GPIO, BOARD_INITPINS_LED3_GPIO_PIN))

#define RS485_EN1_ENABLE()	    GPIO_PortSet(BOARD_INITPINS_RS485_EN1_GPIO, 1U << BOARD_INITPINS_RS485_EN1_GPIO_PIN)
#define RS485_EN1_DISABLE()	    GPIO_PortClear(BOARD_INITPINS_RS485_EN1_GPIO, 1U << BOARD_INITPINS_RS485_EN1_GPIO_PIN)

#define RS485_EN2_ENABLE()	    GPIO_PortSet(BOARD_INITPINS_RS485_EN2_GPIO, 1U << BOARD_INITPINS_RS485_EN2_GPIO_PIN)
#define RS485_EN2_DISABLE()	    GPIO_PortClear(BOARD_INITPINS_RS485_EN2_GPIO, 1U << BOARD_INITPINS_RS485_EN2_GPIO_PIN)

#define RS485_EN3_ENABLE()	    GPIO_PortSet(BOARD_INITPINS_RS485_EN3_GPIO, 1U << BOARD_INITPINS_RS485_EN3_GPIO_PIN)
#define RS485_EN3_DISABLE()	    GPIO_PortClear(BOARD_INITPINS_RS485_EN3_GPIO, 1U << BOARD_INITPINS_RS485_EN3_GPIO_PIN)

#define RS485_EN4_ENABLE()	    GPIO_PortSet(BOARD_INITPINS_RS485_EN4_GPIO, 1U << BOARD_INITPINS_RS485_EN4_GPIO_PIN)
#define RS485_EN4_DISABLE()	    GPIO_PortClear(BOARD_INITPINS_RS485_EN4_GPIO, 1U << BOARD_INITPINS_RS485_EN4_GPIO_PIN)

#define WDOG_WDI_TOGGLE()	    GPIO_PinWrite(BOARD_INITPINS_WDOG_B_GPIO, BOARD_INITPINS_WDOG_B_GPIO_PIN, 0x1 ^ GPIO_PinRead(BOARD_INITPINS_WDOG_B_GPIO, BOARD_INITPINS_WDOG_B_GPIO_PIN))

/***************Relay******************/
#define K1_ENABLE()			    GPIO_PortSet(BOARD_INITPINS_K1_GPIO, 1U << BOARD_INITPINS_K1_GPIO_PIN)
#define K1_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K1_GPIO, 1U << BOARD_INITPINS_K1_GPIO_PIN)

#define K2_ENABLE()			    GPIO_PortSet(BOARD_INITPINS_K2_GPIO, 1U << BOARD_INITPINS_K2_GPIO_PIN)
#define K2_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K2_GPIO, 1U << BOARD_INITPINS_K2_GPIO_PIN)

#define K3_ENABLE()			    GPIO_PortSet(BOARD_INITPINS_K3_GPIO, 1U << BOARD_INITPINS_K3_GPIO_PIN)
#define K3_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K3_GPIO, 1U << BOARD_INITPINS_K3_GPIO_PIN)

#define K4_ENABLE()			    GPIO_PortSet(BOARD_INITPINS_K4_GPIO, 1U << BOARD_INITPINS_K4_GPIO_PIN)
#define K4_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K4_GPIO, 1U << BOARD_INITPINS_K4_GPIO_PIN)

#define K5_ENABLE()			    GPIO_PortSet(BOARD_INITPINS_K5_GPIO, 1U << BOARD_INITPINS_K5_GPIO_PIN)
#define K5_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K5_GPIO, 1U << BOARD_INITPINS_K5_GPIO_PIN)

#define K6_ENABLE()			    GPIO_PortSet(BOARD_INITPINS_K6_GPIO, 1U << BOARD_INITPINS_K6_GPIO_PIN)
#define K6_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K6_GPIO, 1U << BOARD_INITPINS_K6_GPIO_PIN)

#define K7_ENABLE()			    GPIO_PortSet(BOARD_INITPINS_K7_GPIO, 1U << BOARD_INITPINS_K7_GPIO_PIN)
#define K7_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K7_GPIO, 1U << BOARD_INITPINS_K7_GPIO_PIN)

#define K8_ENABLE()			    GPIO_PortSet(BOARD_INITPINS_K8_GPIO, 1U << BOARD_INITPINS_K8_GPIO_PIN)
#define K8_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K8_GPIO, 1U << BOARD_INITPINS_K8_GPIO_PIN)

#define K9_ENABLE()			    GPIO_PortSet(BOARD_INITPINS_K9_GPIO, 1U << BOARD_INITPINS_K9_GPIO_PIN)
#define K9_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K9_GPIO, 1U << BOARD_INITPINS_K9_GPIO_PIN)

#define K10_ENABLE()		    GPIO_PortSet(BOARD_INITPINS_K10_GPIO, 1U << BOARD_INITPINS_K10_GPIO_PIN)
#define K10_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K10_GPIO, 1U << BOARD_INITPINS_K10_GPIO_PIN)

#define K11_ENABLE()		    GPIO_PortSet(BOARD_INITPINS_K11_GPIO, 1U << BOARD_INITPINS_K11_GPIO_PIN)
#define K11_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K11_GPIO, 1U << BOARD_INITPINS_K11_GPIO_PIN)

#define K12_ENABLE()		    GPIO_PortSet(BOARD_INITPINS_K12_GPIO, 1U << BOARD_INITPINS_K12_GPIO_PIN)
#define K12_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K12_GPIO, 1U << BOARD_INITPINS_K12_GPIO_PIN)

#define K13_ENABLE()		    GPIO_PortSet(BOARD_INITPINS_K13_GPIO, 1U << BOARD_INITPINS_K13_GPIO_PIN)
#define K13_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K13_GPIO, 1U << BOARD_INITPINS_K13_GPIO_PIN)

#define K14_ENABLE()		    GPIO_PortSet(BOARD_INITPINS_K14_GPIO, 1U << BOARD_INITPINS_K14_GPIO_PIN)
#define K14_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K14_GPIO, 1U << BOARD_INITPINS_K14_GPIO_PIN)

#define K15_ENABLE()		    GPIO_PortSet(BOARD_INITPINS_K15_GPIO, 1U << BOARD_INITPINS_K15_GPIO_PIN)
#define K15_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K15_GPIO, 1U << BOARD_INITPINS_K15_GPIO_PIN)

#define K16_ENABLE()		    GPIO_PortSet(BOARD_INITPINS_K16_GPIO, 1U << BOARD_INITPINS_K16_GPIO_PIN)
#define K16_DISABLE()		    GPIO_PortClear(BOARD_INITPINS_K16_GPIO, 1U << BOARD_INITPINS_K16_GPIO_PIN)

/***************DI******************/
#define GET_K1_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K1_GPIO, BOARD_INITPINS_DI_K1_GPIO_PIN)
#define GET_K2_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K2_GPIO, BOARD_INITPINS_DI_K2_GPIO_PIN)
#define GET_K3_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K3_GPIO, BOARD_INITPINS_DI_K3_GPIO_PIN)
#define GET_K4_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K4_GPIO, BOARD_INITPINS_DI_K4_GPIO_PIN)
#define GET_K5_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K5_GPIO, BOARD_INITPINS_DI_K5_GPIO_PIN)
#define GET_K6_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K6_GPIO, BOARD_INITPINS_DI_K6_GPIO_PIN)
#define GET_K7_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K7_GPIO, BOARD_INITPINS_DI_K7_GPIO_PIN)
#define GET_K8_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K8_GPIO, BOARD_INITPINS_DI_K8_GPIO_PIN)
#define GET_K9_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K9_GPIO, BOARD_INITPINS_DI_K9_GPIO_PIN)
#define GET_K10_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K10_GPIO, BOARD_INITPINS_DI_K10_GPIO_PIN)
#define GET_K11_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K11_GPIO, BOARD_INITPINS_DI_K11_GPIO_PIN)
#define GET_K12_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K12_GPIO, BOARD_INITPINS_DI_K12_GPIO_PIN)
#define GET_K13_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K13_GPIO, BOARD_INITPINS_DI_K13_GPIO_PIN)
#define GET_K14_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K14_GPIO, BOARD_INITPINS_DI_K14_GPIO_PIN)
#define GET_K15_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K15_GPIO, BOARD_INITPINS_DI_K15_GPIO_PIN)
#define GET_K16_DI_STATUS()	    GPIO_PinRead(BOARD_INITPINS_DI_K16_GPIO, BOARD_INITPINS_DI_K16_GPIO_PIN)
#define GET_ADDR1_STATUS()	    GPIO_PinRead(BOARD_INITPINS_IO_ADD1_GPIO, BOARD_INITPINS_IO_ADD1_GPIO_PIN)
#define GET_ADDR2_STATUS()	    GPIO_PinRead(BOARD_INITPINS_IO_ADD2_GPIO, BOARD_INITPINS_IO_ADD2_GPIO_PIN)
#define GET_ADDR3_STATUS()	    GPIO_PinRead(BOARD_INITPINS_IO_ADD3_GPIO, BOARD_INITPINS_IO_ADD3_GPIO_PIN)
#define GET_ADDR4_STATUS()	    GPIO_PinRead(BOARD_INITPINS_IO_ADD4_GPIO, BOARD_INITPINS_IO_ADD4_GPIO_PIN)
#define GET_VER1_STATUS()	    GPIO_PinRead(BOARD_INITPINS_VER_SEL_1_GPIO, BOARD_INITPINS_VER_SEL_1_GPIO_PIN)
#define GET_VER2_STATUS()	    GPIO_PinRead(BOARD_INITPINS_VER_SEL_2_GPIO, BOARD_INITPINS_VER_SEL_2_GPIO_PIN)
#define GET_WDIPFO_STATUS()	    GPIO_PinRead(BOARD_INITPINS_WDI_PFO_GPIO, BOARD_INITPINS_WDI_PFO_GPIO_PIN)
#define GET_USERLED_STATUS()    GPIO_PinRead(USER_LED_GPIO, USER_LED_GPIO_PIN)



extern SemaphoreHandle_t g_LedTaskSync_Binary_Semaphore;

extern void Hal_InitEnetModuleClock(void);
extern void Hal_I2c_Init(void);
extern void ctrl_relay_cmd(U8 relay_pos, BOOL cmd);
extern void ctrl_led_cmd(U8 led_pos, BOOL cmd);
extern void AllLedToggle(void);
extern void AllLedOn(void);
extern void AllLedOff(void);
extern void FeedWatchDog(void);
extern void WatchDogFeedFunc(void);
extern void LedBlinkFunc(void);
extern void vLedTaskDelay(U32 delay_ms);

extern SYS_WORKING_STATYS GetSysRunModeFg(void);
extern void SetSysNormalModeFg(void);
extern void SetSysShuttingDownModeFg(void);
extern void SetSysPowerOffModeFg(void);
extern void InitRelayCtrlTimes(void);
extern void SaveRealyCtrlTimes(void);

#endif /* HAL_HAL_SYS_HAL_SYS_IF_H_ */
