/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "fsl_flexcan.h"
#include "fsl_clock.h"
#include "fsl_lpuart.h"
#include "fsl_lpuart_edma.h"
#include "fsl_adc.h"
#include "fsl_lpi2c.h"
#include "fsl_lpi2c_freertos.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA0_DMAMUX_BASEADDR DMAMUX
/* Definition of peripheral ID */
#define PDU_CAN_PERIPHERAL CAN1
/* Definition of the clock source frequency */
#define PDU_CAN_CLOCK_SOURCE 60000000UL
/* PDU_CAN interrupt vector ID (number). */
#define PDU_CAN_FLEXCAN_IRQN CAN1_IRQn
/* PDU_CAN interrupt vector priority. */
#define PDU_CAN_FLEXCAN_IRQ_PRIORITY 5
/* PDU_CAN interrupt handler identifier. */
#define CAN1_IRQhandler CAN1_IRQHandler
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART1_CLOCK_SOURCE 80000000UL
/* LPUART1 eDMA source request. */
#define LPUART1_RX_DMA_REQUEST kDmaRequestMuxLPUART1Rx
/* Selected eDMA channel number. */
#define LPUART1_RX_DMA_CHANNEL 1
/* DMAMUX device that is used for muxing of the request. */
#define LPUART1_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART1_RX_DMA_BASEADDR DMA0
/* LPUART1 eDMA source request. */
#define LPUART1_TX_DMA_REQUEST kDmaRequestMuxLPUART1Tx
/* Selected eDMA channel number. */
#define LPUART1_TX_DMA_CHANNEL 0
/* DMAMUX device that is used for muxing of the request. */
#define LPUART1_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART1_TX_DMA_BASEADDR DMA0
/* BOARD_InitPeripherals defines for ADC1 */
/* Definition of peripheral ID */
#define ADC1_PERIPHERAL ADC1
/* Definition of special channel interconnected with ADC_ETC which takes real channel to be measured from ADC_ETC. */
#define ADC1_CHANNEL_DRIVEN_BY_ADC_ETC 16U
/* Channel 0 (IN.0) conversion control group. */
#define ADC1_CH0_CONTROL_GROUP 0U
/* Channel 1 (IN.2) conversion control group. */
#define ADC1_CH1_CONTROL_GROUP 0U
/* BOARD_InitPeripherals defines for LPI2C3 */
/* Definition of peripheral ID */
#define EEPROM_I2C_PERIPHERAL LPI2C3
/* Definition of clock source */
#define EEPROM_I2C_CLOCK_FREQ 60000000UL
/* Definition of follower address */
#define EEPROM_I2C_MASTER_SLAVE_ADDRESS 80
/* BOARD_InitPeripherals defines for ADC2 */
/* Definition of peripheral ID */
#define ADC2_PERIPHERAL ADC2
/* Definition of special channel interconnected with ADC_ETC which takes real channel to be measured from ADC_ETC. */
#define ADC2_CHANNEL_DRIVEN_BY_ADC_ETC 16U
/* Channel 0 (IN.0) conversion control group. */
#define ADC2_CH0_CONTROL_GROUP 0U
/* Channel 1 (IN.1) conversion control group. */
#define ADC2_CH1_CONTROL_GROUP 0U

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA0_config;
extern const flexcan_config_t PDU_CAN_config;
/* Message buffer 16 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_16;
/* Message buffer 17 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_17;
/* Message buffer 18 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_18;
/* Message buffer 19 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_19;
/* Message buffer 20 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_20;
/* Message buffer 21 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_21;
/* Message buffer 22 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_22;
/* Message buffer 23 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_23;
/* Message buffer 24 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_24;
/* Message buffer 25 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_25;
/* Message buffer 26 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_26;
/* Message buffer 27 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_27;
/* Message buffer 28 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_28;
/* Message buffer 29 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_29;
/* Message buffer 30 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_30;
/* Message buffer 31 configuration structure */
extern const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_31;
extern const lpuart_config_t LPUART1_config;
extern edma_handle_t LPUART1_RX_Handle;
extern edma_handle_t LPUART1_TX_Handle;
extern lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;
extern const adc_config_t ADC1_config;
extern const adc_channel_config_t ADC1_channels_config[2];
extern const lpi2c_master_config_t EEPROM_I2C_masterConfig;
extern lpi2c_master_transfer_t EEPROM_I2C_masterTransfer;
extern lpi2c_rtos_handle_t EEPROM_I2C_masterHandle;
extern const adc_config_t ADC2_config;
extern const adc_channel_config_t ADC2_channels_config[2];

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* LPUART eDMA callback function for the LPUART1 component (init. function BOARD_InitPeripherals)*/
extern void LPUART_DmaCallback(LPUART_Type *,lpuart_edma_handle_t *,status_t ,void *);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
