/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MIMXRT1021xxxxx
package_id: MIMXRT1021DAG5A
mcu_data: ksdk2_0
processor_version: 16.3.0
board: MIMXRT1020-EVK
external_user_signals: {}
pin_labels:
- {pin_num: '14', pin_signal: GPIO_EMC_04, label: LED_OUT1, identifier: PWM_OUT1;LED_OUT1}
- {pin_num: '18', pin_signal: GPIO_EMC_00, label: DI_Scram, identifier: SEMC_D0;DI_Scram}
- {pin_num: '17', pin_signal: GPIO_EMC_01, label: DI_SPD, identifier: SEMC_D1;DI_SPD}
- {pin_num: '16', pin_signal: GPIO_EMC_02, label: 'SEMC_D2/U14[5]', identifier: IIC1_SCL}
- {pin_num: '15', pin_signal: GPIO_EMC_03, label: 'SEMC_D3/U14[7]', identifier: IIC1_SDA}
- {pin_num: '13', pin_signal: GPIO_EMC_05, label: LED_OUT2, identifier: SEMC_D5;PWM_OUT2;LED_OUT2}
- {pin_num: '12', pin_signal: GPIO_EMC_06, label: 'SEMC_D6/U14[11]', identifier: UART3_TX}
- {pin_num: '10', pin_signal: GPIO_EMC_07, label: 'SEMC_D7/U14[13]', identifier: UART3_RX}
- {pin_num: '9', pin_signal: GPIO_EMC_08, label: CAN2_TX, identifier: SEMC_DM0;CAN2_TX}
- {pin_num: '8', pin_signal: GPIO_EMC_09, label: CAN2_RX, identifier: SEMC_WE;CAN2_RX}
- {pin_num: '7', pin_signal: GPIO_EMC_10, label: LED_OUT3, identifier: SEMC_CAS;PWM_OUT3;LED_OUT3}
- {pin_num: '4', pin_signal: GPIO_EMC_11, label: LED_OUT4, identifier: SEMC_RAS;PWM_OUT4;LED_OUT4}
- {pin_num: '3', pin_signal: GPIO_EMC_12, label: 'SEMC_CS0/U14[19]', identifier: UART6_TX}
- {pin_num: '2', pin_signal: GPIO_EMC_13, label: 'SEMC_BA0/U14[20]', identifier: UART6_RX}
- {pin_num: '1', pin_signal: GPIO_EMC_14, label: HW_VER, identifier: HW_VER2}
- {pin_num: '143', pin_signal: GPIO_EMC_15, label: HW_VER, identifier: HW_VER1}
- {pin_num: '142', pin_signal: GPIO_EMC_16, label: K8, identifier: SEMC_A0;K8}
- {pin_num: '141', pin_signal: GPIO_EMC_17, label: K7, identifier: SEMC_A1;K7}
- {pin_num: '140', pin_signal: GPIO_EMC_18, label: LED_OUT5, identifier: SEMC_A2;PWM_OUT5;LED_OUT5}
- {pin_num: '139', pin_signal: GPIO_EMC_19, label: LED_OUT6, identifier: SEMC_A3;PWM_OUT6;LED_OUT6}
- {pin_num: '138', pin_signal: GPIO_EMC_20, label: K6, identifier: K6}
- {pin_num: '137', pin_signal: GPIO_EMC_21, label: K5, identifier: K5}
- {pin_num: '136', pin_signal: GPIO_EMC_22, label: CD4052B_CHA, identifier: UART2_TX;CD4052_CHA}
- {pin_num: '133', pin_signal: GPIO_EMC_23, label: CD4052B_CHB, identifier: UART2_RX;CD4052_CHB}
- {pin_num: '132', pin_signal: GPIO_EMC_24, label: K4, identifier: K4}
- {pin_num: '131', pin_signal: GPIO_EMC_25, label: K3, identifier: K3}
- {pin_num: '130', pin_signal: GPIO_EMC_26, label: K2, identifier: K2}
- {pin_num: '129', pin_signal: GPIO_EMC_27, label: K1, identifier: K1}
- {pin_num: '128', pin_signal: GPIO_EMC_28, label: IO_ADD1}
- {pin_num: '127', pin_signal: GPIO_EMC_29, label: IO_ADD2, identifier: SEMC_CKE;IO_ADD2}
- {pin_num: '126', pin_signal: GPIO_EMC_30, label: IO_ADD3, identifier: SEMC_CLK;IO_ADD3}
- {pin_num: '125', pin_signal: GPIO_EMC_31, label: IO_ADD4, identifier: SEMC_DM1;IO_ADD4}
- {pin_num: '124', pin_signal: GPIO_EMC_32, label: 'SEMC_D8/U14[42]', identifier: UART4_TX}
- {pin_num: '123', pin_signal: GPIO_EMC_33, label: 'SEMC_D9/U14[44]', identifier: UART4_RX}
- {pin_num: '122', pin_signal: GPIO_EMC_34, label: 'SEMC_D10/U14[45]', identifier: WDI_PFO}
- {pin_num: '121', pin_signal: GPIO_EMC_35, label: DI_Hit, identifier: SEMC_D11;DI_Hit}
- {pin_num: '120', pin_signal: GPIO_EMC_36, label: DI_Water, identifier: SEMC_D12;DI_Water}
- {pin_num: '119', pin_signal: GPIO_EMC_37, label: DI_Door, identifier: SEMC_D13;DI_Door}
- {pin_num: '118', pin_signal: GPIO_EMC_38, label: 'SEMC_D14/U14[51]', identifier: UART5_TX}
- {pin_num: '117', pin_signal: GPIO_EMC_39, label: 'SEMC_D15/U14[53]', identifier: UART5_RX}
- {pin_num: '109', pin_signal: GPIO_AD_B0_02, label: GND, identifier: RS485_EN1}
- {pin_num: '108', pin_signal: GPIO_AD_B0_03, label: 'JTAG_TDI/J16[5]/WDOG_B', identifier: WDOG_B}
- {pin_num: '107', pin_signal: GPIO_AD_B0_04, label: 'JTAG_TDO/J16[13]/ENET_RST/U11[32]', identifier: ENET_RST;PHY_RST}
- {pin_num: '106', pin_signal: GPIO_AD_B0_05, label: USER_LED, identifier: RUN_LED}
- {pin_num: '100', pin_signal: GPIO_AD_B0_08, label: 'ENET_TX_CLK/U11[9]', identifier: ENET_TX_CLK}
- {pin_num: '99', pin_signal: GPIO_AD_B0_09, label: 'ENET_RXD1/U11[15]/J17[3]', identifier: ENET_RXD1}
- {pin_num: '92', pin_signal: GPIO_AD_B1_00, label: DI_FU1_FB, identifier: DI_FU1_FB}
- {pin_num: '91', pin_signal: GPIO_AD_B1_01, label: DI_FU2_FB, identifier: DI_FU2_FB}
- {pin_num: '90', pin_signal: GPIO_AD_B1_02, label: DI_K1_FB, identifier: DI_K1_FB}
- {pin_num: '89', pin_signal: GPIO_AD_B1_03, label: DI_K2_FB, identifier: DI_K2_FB}
- {pin_num: '88', pin_signal: GPIO_AD_B1_04, label: DI_K3_FB, identifier: DI_K3_FB}
- {pin_num: '87', pin_signal: GPIO_AD_B1_05, label: DI_K4_FB, identifier: DI_K4_FB}
- {pin_num: '84', pin_signal: GPIO_AD_B1_06, label: 'ENET_INT/U11[21]/J17[8]', identifier: ENET_INT;PHY_INT}
- {pin_num: '83', pin_signal: GPIO_AD_B1_07, label: DI_MCB, identifier: DI_MCB}
- {pin_num: '80', pin_signal: GPIO_AD_B1_10, label: 'USB_OTG1_PWR/J18[1]', identifier: ADCY}
- {pin_num: '79', pin_signal: GPIO_AD_B1_11, label: 'USB_OTG1_ID/J18[2]', identifier: ADCX}
- {pin_num: '78', pin_signal: GPIO_AD_B1_12, label: 'USB_OTG1_OC/J18[3]', identifier: ADC_G1_T1}
- {pin_num: '76', pin_signal: GPIO_AD_B1_13, label: 'CAN_STBY/J18[4]', identifier: ADC_G1_T2}
- {pin_num: '75', pin_signal: GPIO_AD_B1_14, label: 'I2C1_SCL/U10[17]/J18[6]', identifier: ADC_G2_T1}
- {pin_num: '74', pin_signal: GPIO_AD_B1_15, label: 'I2C1_SDA/U10[18]/J18[5]', identifier: ADC_G2_T2}
- {pin_num: '48', pin_signal: GPIO_SD_B0_00, label: RS485_EN2, identifier: IIC3_SCL;RS485_EN2}
- {pin_num: '47', pin_signal: GPIO_SD_B0_01, label: FAN, identifier: IIC3_SDA;FAN}
- {pin_num: '46', pin_signal: GPIO_SD_B0_02, label: DI_GUN1_FB, identifier: SD1_CMD;DI_GUN1_FB}
- {pin_num: '45', pin_signal: GPIO_SD_B0_03, label: DI_GUN2_FB, identifier: SD1_CLK;DI_GUN2_FB}
- {pin_num: '43', pin_signal: GPIO_SD_B0_04, label: 'SD1_D0/J15[7]', identifier: UART7_TX}
- {pin_num: '42', pin_signal: GPIO_SD_B0_05, label: 'SD1_D1/J15[8]', identifier: UART7_RX}
- {pin_num: '41', pin_signal: GPIO_SD_B0_06, label: RS485_EN3, identifier: RS485_EN2;RS485_EN3}
- {pin_num: '30', pin_signal: GPIO_SD_B1_02, label: I2C4_SCL, identifier: UART8_TX}
- {pin_num: '26', pin_signal: GPIO_SD_B1_05, label: RS485_EN2, identifier: RS485_EN3}
- {pin_num: '27', pin_signal: GPIO_SD_B1_04, label: RS485_EN4, identifier: RS485_EN4}
- {pin_num: '28', pin_signal: GPIO_SD_B1_03, label: I2C4_SDA, identifier: UART8_RX}
- {pin_num: '81', pin_signal: GPIO_AD_B1_09, label: 'SEMC_A7/U14[32]/BT_CFG[5]', identifier: CD4052_CHB;UART2_RX}
- {pin_num: '82', pin_signal: GPIO_AD_B1_08, label: 'SEMC_A6/U14[31]/BT_CFG[4]', identifier: CD4052_CHA;UART2_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_xbara.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '106', peripheral: GPIO1, signal: 'gpio_io, 05', pin_signal: GPIO_AD_B0_05, direction: OUTPUT, pull_keeper_enable: Disable}
  - {pin_num: '105', peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_06, pull_keeper_enable: Disable}
  - {pin_num: '101', peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_07, pull_keeper_enable: Disable}
  - {pin_num: '136', peripheral: GPIO2, signal: 'gpio_io, 22', pin_signal: GPIO_EMC_22, identifier: CD4052_CHA, direction: OUTPUT, pull_keeper_enable: Disable}
  - {pin_num: '133', peripheral: GPIO2, signal: 'gpio_io, 23', pin_signal: GPIO_EMC_23, identifier: CD4052_CHB, direction: OUTPUT, pull_keeper_enable: Disable}
  - {pin_num: '12', peripheral: LPUART3, signal: TX, pin_signal: GPIO_EMC_06, pull_keeper_enable: Disable}
  - {pin_num: '10', peripheral: LPUART3, signal: RX, pin_signal: GPIO_EMC_07, pull_keeper_enable: Disable}
  - {pin_num: '123', peripheral: LPUART4, signal: RX, pin_signal: GPIO_EMC_33, pull_keeper_enable: Disable}
  - {pin_num: '124', peripheral: LPUART4, signal: TX, pin_signal: GPIO_EMC_32, pull_keeper_enable: Disable}
  - {pin_num: '117', peripheral: LPUART5, signal: RX, pin_signal: GPIO_EMC_39, pull_keeper_enable: Disable}
  - {pin_num: '118', peripheral: LPUART5, signal: TX, pin_signal: GPIO_EMC_38, pull_keeper_enable: Disable}
  - {pin_num: '2', peripheral: LPUART6, signal: RX, pin_signal: GPIO_EMC_13, pull_keeper_enable: Disable}
  - {pin_num: '3', peripheral: LPUART6, signal: TX, pin_signal: GPIO_EMC_12, pull_keeper_enable: Disable}
  - {pin_num: '42', peripheral: LPUART7, signal: RX, pin_signal: GPIO_SD_B0_05, pull_keeper_enable: Disable}
  - {pin_num: '43', peripheral: LPUART7, signal: TX, pin_signal: GPIO_SD_B0_04, pull_keeper_enable: Disable}
  - {pin_num: '30', peripheral: LPUART8, signal: TX, pin_signal: GPIO_SD_B1_02, pull_keeper_select: Keeper, pull_keeper_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '28', peripheral: LPUART8, signal: RX, pin_signal: GPIO_SD_B1_03, pull_keeper_select: Pull, pull_keeper_enable: Enable, pull_up_down_config: Pull_Up_47K_Ohm}
  - {pin_num: '48', peripheral: GPIO3, signal: 'gpio_io, 13', pin_signal: GPIO_SD_B0_00, identifier: RS485_EN2, direction: OUTPUT, software_input_on: Disable, open_drain: Disable,
    pull_keeper_select: Pull, pull_keeper_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '47', peripheral: TMR2, signal: 'TIMER_OUTPUT, 2', pin_signal: GPIO_SD_B0_01, identifier: FAN, software_input_on: Disable, open_drain: Disable, pull_keeper_select: Keeper,
    pull_keeper_enable: Enable, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '16', peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_EMC_02, software_input_on: Enable, open_drain: Enable, pull_keeper_select: Keeper, pull_keeper_enable: Enable,
    pull_up_down_config: Pull_Up_22K_Ohm}
  - {pin_num: '15', peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_EMC_03, software_input_on: Enable, open_drain: Enable, pull_keeper_select: Keeper, pull_keeper_enable: Enable,
    pull_up_down_config: Pull_Up_22K_Ohm}
  - {pin_num: '32', peripheral: CAN1, signal: RX, pin_signal: GPIO_SD_B1_01, pull_keeper_enable: Disable}
  - {pin_num: '33', peripheral: CAN1, signal: TX, pin_signal: GPIO_SD_B1_00, pull_keeper_enable: Disable}
  - {pin_num: '8', peripheral: CAN2, signal: RX, pin_signal: GPIO_EMC_09, identifier: CAN2_RX, pull_keeper_enable: Disable}
  - {pin_num: '9', peripheral: CAN2, signal: TX, pin_signal: GPIO_EMC_08, identifier: CAN2_TX, pull_keeper_enable: Disable}
  - {pin_num: '109', peripheral: GPIO1, signal: 'gpio_io, 02', pin_signal: GPIO_AD_B0_02, direction: OUTPUT, drive_strength: R0_6, pull_keeper_select: Pull, pull_keeper_enable: Disable,
    pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '41', peripheral: GPIO3, signal: 'gpio_io, 19', pin_signal: GPIO_SD_B0_06, identifier: RS485_EN3, direction: OUTPUT, drive_strength: R0_6, pull_keeper_select: Pull,
    pull_keeper_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '27', peripheral: GPIO3, signal: 'gpio_io, 24', pin_signal: GPIO_SD_B1_04, direction: OUTPUT, pull_keeper_select: Pull, pull_keeper_enable: Disable}
  - {pin_num: '116', peripheral: ENET, signal: enet_mdio, pin_signal: GPIO_EMC_40, slew_rate: Fast, speed: MHZ_200, drive_strength: R0_5, pull_keeper_select: Pull,
    pull_keeper_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '115', peripheral: ENET, signal: enet_mdc, pin_signal: GPIO_EMC_41, slew_rate: Fast, speed: MHZ_200, drive_strength: R0_5, pull_keeper_select: Pull,
    pull_keeper_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '82', peripheral: LPUART2, signal: TX, pin_signal: GPIO_AD_B1_08, identifier: UART2_TX, pull_keeper_enable: Disable}
  - {pin_num: '81', peripheral: LPUART2, signal: RX, pin_signal: GPIO_AD_B1_09, identifier: UART2_RX, pull_keeper_enable: Disable}
  - {pin_num: '100', peripheral: ENET, signal: enet_ref_clk, pin_signal: GPIO_AD_B0_08, slew_rate: Fast, software_input_on: Enable, speed: MHZ_200, drive_strength: R0_5,
    pull_keeper_select: Pull, pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '98', peripheral: ENET, signal: 'enet_rx_data, 0', pin_signal: GPIO_AD_B0_10, slew_rate: Fast, speed: MHZ_200, drive_strength: R0_5, pull_keeper_select: Pull,
    pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '99', peripheral: ENET, signal: 'enet_rx_data, 1', pin_signal: GPIO_AD_B0_09, slew_rate: Fast, speed: MHZ_200, drive_strength: R0_5, pull_keeper_select: Pull,
    pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '97', peripheral: ENET, signal: enet_rx_en, pin_signal: GPIO_AD_B0_11, slew_rate: Fast, speed: MHZ_200, drive_strength: R0_5, pull_keeper_select: Pull,
    pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '96', peripheral: ENET, signal: enet_rx_er, pin_signal: GPIO_AD_B0_12, slew_rate: Fast, speed: MHZ_200, drive_strength: R0_5, pull_keeper_select: Pull,
    pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '94', peripheral: ENET, signal: 'enet_tx_data, 0', pin_signal: GPIO_AD_B0_14, slew_rate: Fast, speed: MHZ_200, drive_strength: R0_5, pull_keeper_select: Pull,
    pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '93', peripheral: ENET, signal: 'enet_tx_data, 1', pin_signal: GPIO_AD_B0_15, slew_rate: Fast, speed: MHZ_200, drive_strength: R0_5, pull_keeper_select: Pull,
    pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '95', peripheral: ENET, signal: enet_tx_en, pin_signal: GPIO_AD_B0_13, slew_rate: Fast, speed: MHZ_200, drive_strength: R0_5, pull_keeper_select: Pull,
    pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '107', peripheral: GPIO1, signal: 'gpio_io, 04', pin_signal: GPIO_AD_B0_04, identifier: PHY_RST, direction: OUTPUT, gpio_init_state: 'true', drive_strength: R0_5,
    pull_keeper_select: Pull}
  - {pin_num: '84', peripheral: GPIO1, signal: 'gpio_io, 22', pin_signal: GPIO_AD_B1_06, identifier: PHY_INT, direction: INPUT, gpio_interrupt: kGPIO_IntLowLevel,
    slew_rate: Fast, drive_strength: R0_5, pull_keeper_select: Pull, pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '79', peripheral: ADC1, signal: 'IN, 11', pin_signal: GPIO_AD_B1_11}
  - {pin_num: '80', peripheral: ADC1, signal: 'IN, 10', pin_signal: GPIO_AD_B1_10}
  - {pin_num: '78', peripheral: ADC1, signal: 'IN, 12', pin_signal: GPIO_AD_B1_12}
  - {pin_num: '76', peripheral: ADC1, signal: 'IN, 13', pin_signal: GPIO_AD_B1_13}
  - {pin_num: '75', peripheral: ADC1, signal: 'IN, 14', pin_signal: GPIO_AD_B1_14}
  - {pin_num: '74', peripheral: ADC1, signal: 'IN, 15', pin_signal: GPIO_AD_B1_15}
  - {pin_num: '129', peripheral: GPIO2, signal: 'gpio_io, 27', pin_signal: GPIO_EMC_27, direction: OUTPUT, pull_keeper_select: Keeper, pull_keeper_enable: Disable,
    pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '130', peripheral: GPIO2, signal: 'gpio_io, 26', pin_signal: GPIO_EMC_26, direction: OUTPUT, pull_keeper_select: Keeper, pull_keeper_enable: Disable,
    pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '131', peripheral: GPIO2, signal: 'gpio_io, 25', pin_signal: GPIO_EMC_25, direction: OUTPUT, pull_keeper_select: Keeper, pull_keeper_enable: Disable}
  - {pin_num: '132', peripheral: GPIO2, signal: 'gpio_io, 24', pin_signal: GPIO_EMC_24, direction: OUTPUT, pull_keeper_select: Keeper, pull_keeper_enable: Disable}
  - {pin_num: '137', peripheral: GPIO2, signal: 'gpio_io, 21', pin_signal: GPIO_EMC_21, direction: OUTPUT, pull_keeper_select: Keeper, pull_keeper_enable: Disable}
  - {pin_num: '138', peripheral: GPIO2, signal: 'gpio_io, 20', pin_signal: GPIO_EMC_20, direction: OUTPUT, pull_keeper_select: Keeper, pull_keeper_enable: Disable}
  - {pin_num: '141', peripheral: GPIO2, signal: 'gpio_io, 17', pin_signal: GPIO_EMC_17, identifier: K7, direction: OUTPUT, pull_keeper_select: Keeper, pull_keeper_enable: Disable}
  - {pin_num: '142', peripheral: GPIO2, signal: 'gpio_io, 16', pin_signal: GPIO_EMC_16, identifier: K8, direction: OUTPUT, pull_keeper_select: Keeper, pull_keeper_enable: Disable}
  - {pin_num: '92', peripheral: GPIO1, signal: 'gpio_io, 16', pin_signal: GPIO_AD_B1_00, direction: INPUT}
  - {pin_num: '91', peripheral: GPIO1, signal: 'gpio_io, 17', pin_signal: GPIO_AD_B1_01, direction: INPUT}
  - {pin_num: '90', peripheral: GPIO1, signal: 'gpio_io, 18', pin_signal: GPIO_AD_B1_02, direction: INPUT}
  - {pin_num: '89', peripheral: GPIO1, signal: 'gpio_io, 19', pin_signal: GPIO_AD_B1_03, direction: INPUT}
  - {pin_num: '88', peripheral: GPIO1, signal: 'gpio_io, 20', pin_signal: GPIO_AD_B1_04, direction: INPUT}
  - {pin_num: '87', peripheral: GPIO1, signal: 'gpio_io, 21', pin_signal: GPIO_AD_B1_05, direction: INPUT}
  - {pin_num: '46', peripheral: GPIO3, signal: 'gpio_io, 15', pin_signal: GPIO_SD_B0_02, identifier: DI_GUN1_FB, direction: INPUT}
  - {pin_num: '45', peripheral: GPIO3, signal: 'gpio_io, 16', pin_signal: GPIO_SD_B0_03, identifier: DI_GUN2_FB, direction: INPUT}
  - {pin_num: '83', peripheral: GPIO1, signal: 'gpio_io, 23', pin_signal: GPIO_AD_B1_07, direction: INPUT}
  - {pin_num: '119', peripheral: GPIO3, signal: 'gpio_io, 05', pin_signal: GPIO_EMC_37, identifier: DI_Door, direction: INPUT}
  - {pin_num: '120', peripheral: GPIO3, signal: 'gpio_io, 04', pin_signal: GPIO_EMC_36, identifier: DI_Water, direction: INPUT}
  - {pin_num: '121', peripheral: GPIO3, signal: 'gpio_io, 03', pin_signal: GPIO_EMC_35, identifier: DI_Hit, direction: INPUT}
  - {pin_num: '122', peripheral: GPIO3, signal: 'gpio_io, 02', pin_signal: GPIO_EMC_34, direction: INPUT, pull_keeper_select: Pull, pull_up_down_config: Pull_Up_47K_Ohm}
  - {pin_num: '18', peripheral: GPIO2, signal: 'gpio_io, 00', pin_signal: GPIO_EMC_00, identifier: DI_Scram, direction: INPUT}
  - {pin_num: '17', peripheral: GPIO2, signal: 'gpio_io, 01', pin_signal: GPIO_EMC_01, identifier: DI_SPD, direction: INPUT}
  - {pin_num: '108', peripheral: GPIO1, signal: 'gpio_io, 03', pin_signal: GPIO_AD_B0_03, direction: OUTPUT, pull_keeper_select: Keeper, pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '14', peripheral: TMR1, signal: 'TIMER_OUTPUT, 0', pin_signal: GPIO_EMC_04, identifier: LED_OUT1}
  - {pin_num: '13', peripheral: TMR1, signal: 'TIMER_OUTPUT, 1', pin_signal: GPIO_EMC_05, identifier: LED_OUT2}
  - {pin_num: '7', peripheral: TMR1, signal: 'TIMER_OUTPUT, 2', pin_signal: GPIO_EMC_10, identifier: LED_OUT3}
  - {pin_num: '4', peripheral: TMR1, signal: 'TIMER_OUTPUT, 3', pin_signal: GPIO_EMC_11, identifier: LED_OUT4}
  - {pin_num: '140', peripheral: TMR2, signal: 'TIMER_OUTPUT, 0', pin_signal: GPIO_EMC_18, identifier: LED_OUT5}
  - {pin_num: '139', peripheral: TMR2, signal: 'TIMER_OUTPUT, 1', pin_signal: GPIO_EMC_19, identifier: LED_OUT6}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           
  CLOCK_EnableClock(kCLOCK_Xbar1);            

  /* GPIO configuration of RS485_EN1 on GPIO_AD_B0_02 (pin 109) */
  gpio_pin_config_t RS485_EN1_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_02 (pin 109) */
  GPIO_PinInit(GPIO1, 2U, &RS485_EN1_config);

  /* GPIO configuration of WDOG_B on GPIO_AD_B0_03 (pin 108) */
  gpio_pin_config_t WDOG_B_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_03 (pin 108) */
  GPIO_PinInit(GPIO1, 3U, &WDOG_B_config);

  /* GPIO configuration of LED_OUT1 on GPIO_EMC_04 (pin 14) */
  gpio_pin_config_t LED_OUT1_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_04 (pin 14) */
  GPIO_PinInit(GPIO1, 4U, &LED_OUT1_config);

  /* GPIO configuration of LED_OUT2 on GPIO_EMC_05 (pin 13) */
  gpio_pin_config_t LED_OUT2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_05 (pin 13) */
  GPIO_PinInit(GPIO1, 5U, &LED_OUT2_config);

  /* GPIO configuration of LED_OUT5 on GPIO_EMC_18 (pin 140) */
  gpio_pin_config_t LED_OUT5_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_18 (pin 140) */
  GPIO_PinInit(GPIO1, 16U, &LED_OUT5_config);

  /* GPIO configuration of LED_OUT6 on GPIO_EMC_19 (pin 139) */
  gpio_pin_config_t LED_OUT6_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_19 (pin 139) */
  GPIO_PinInit(GPIO1, 17U, &LED_OUT6_config);

  /* GPIO configuration of DI_K1_FB on GPIO_AD_B1_02 (pin 90) */
  gpio_pin_config_t DI_K1_FB_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_02 (pin 90) */
  GPIO_PinInit(GPIO1, 18U, &DI_K1_FB_config);

  /* GPIO configuration of DI_K2_FB on GPIO_AD_B1_03 (pin 89) */
  gpio_pin_config_t DI_K2_FB_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_03 (pin 89) */
  GPIO_PinInit(GPIO1, 19U, &DI_K2_FB_config);

  /* GPIO configuration of DI_K3_FB on GPIO_AD_B1_04 (pin 88) */
  gpio_pin_config_t DI_K3_FB_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_04 (pin 88) */
  GPIO_PinInit(GPIO1, 20U, &DI_K3_FB_config);

  /* GPIO configuration of DI_K4_FB on GPIO_AD_B1_05 (pin 87) */
  gpio_pin_config_t DI_K4_FB_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_05 (pin 87) */
  GPIO_PinInit(GPIO1, 21U, &DI_K4_FB_config);

  /* GPIO configuration of PHY_INT on GPIO_AD_B1_06 (pin 84) */
  gpio_pin_config_t PHY_INT_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntLowLevel
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_06 (pin 84) */
  GPIO_PinInit(GPIO1, 22U, &PHY_INT_config);
  /* Enable GPIO pin interrupt on GPIO_AD_B1_06 (pin 84) */
  GPIO_PortEnableInterrupts(GPIO1, 1U << 22U);

  /* GPIO configuration of DI_MCB on GPIO_AD_B1_07 (pin 83) */
  gpio_pin_config_t DI_MCB_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_07 (pin 83) */
  GPIO_PinInit(GPIO1, 23U, &DI_MCB_config);

  /* GPIO configuration of DI_Scram on GPIO_EMC_00 (pin 18) */
  gpio_pin_config_t DI_Scram_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_00 (pin 18) */
  GPIO_PinInit(GPIO2, 0U, &DI_Scram_config);

  /* GPIO configuration of DI_SPD on GPIO_EMC_01 (pin 17) */
  gpio_pin_config_t DI_SPD_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_01 (pin 17) */
  GPIO_PinInit(GPIO2, 1U, &DI_SPD_config);

  /* GPIO configuration of K8 on GPIO_EMC_16 (pin 142) */
  gpio_pin_config_t K8_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_16 (pin 142) */
  GPIO_PinInit(GPIO2, 16U, &K8_config);

  /* GPIO configuration of K7 on GPIO_EMC_17 (pin 141) */
  gpio_pin_config_t K7_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_17 (pin 141) */
  GPIO_PinInit(GPIO2, 17U, &K7_config);

  /* GPIO configuration of K6 on GPIO_EMC_20 (pin 138) */
  gpio_pin_config_t K6_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_20 (pin 138) */
  GPIO_PinInit(GPIO2, 20U, &K6_config);

  /* GPIO configuration of K5 on GPIO_EMC_21 (pin 137) */
  gpio_pin_config_t K5_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_21 (pin 137) */
  GPIO_PinInit(GPIO2, 21U, &K5_config);

  /* GPIO configuration of CD4052_CHA on GPIO_EMC_22 (pin 136) */
  gpio_pin_config_t CD4052_CHA_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_22 (pin 136) */
  GPIO_PinInit(GPIO2, 22U, &CD4052_CHA_config);

  /* GPIO configuration of CD4052_CHB on GPIO_EMC_23 (pin 133) */
  gpio_pin_config_t CD4052_CHB_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_23 (pin 133) */
  GPIO_PinInit(GPIO2, 23U, &CD4052_CHB_config);

  /* GPIO configuration of K4 on GPIO_EMC_24 (pin 132) */
  gpio_pin_config_t K4_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_24 (pin 132) */
  GPIO_PinInit(GPIO2, 24U, &K4_config);

  /* GPIO configuration of K3 on GPIO_EMC_25 (pin 131) */
  gpio_pin_config_t K3_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_25 (pin 131) */
  GPIO_PinInit(GPIO2, 25U, &K3_config);

  /* GPIO configuration of K2 on GPIO_EMC_26 (pin 130) */
  gpio_pin_config_t K2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_26 (pin 130) */
  GPIO_PinInit(GPIO2, 26U, &K2_config);

  /* GPIO configuration of K1 on GPIO_EMC_27 (pin 129) */
  gpio_pin_config_t K1_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_27 (pin 129) */
  GPIO_PinInit(GPIO2, 27U, &K1_config);

  /* GPIO configuration of WDI_PFO on GPIO_EMC_34 (pin 122) */
  gpio_pin_config_t WDI_PFO_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_34 (pin 122) */
  GPIO_PinInit(GPIO3, 2U, &WDI_PFO_config);

  /* GPIO configuration of DI_Hit on GPIO_EMC_35 (pin 121) */
  gpio_pin_config_t DI_Hit_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_35 (pin 121) */
  GPIO_PinInit(GPIO3, 3U, &DI_Hit_config);

  /* GPIO configuration of DI_Water on GPIO_EMC_36 (pin 120) */
  gpio_pin_config_t DI_Water_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_36 (pin 120) */
  GPIO_PinInit(GPIO3, 4U, &DI_Water_config);

  /* GPIO configuration of DI_Door on GPIO_EMC_37 (pin 119) */
  gpio_pin_config_t DI_Door_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_37 (pin 119) */
  GPIO_PinInit(GPIO3, 5U, &DI_Door_config);

  /* GPIO configuration of RS485_EN2 on GPIO_SD_B0_00 (pin 48) */
  gpio_pin_config_t RS485_EN2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B0_00 (pin 48) */
  GPIO_PinInit(GPIO3, 13U, &RS485_EN2_config);

  /* GPIO configuration of DI_GUN1_FB on GPIO_SD_B0_02 (pin 46) */
  gpio_pin_config_t DI_GUN1_FB_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B0_02 (pin 46) */
  GPIO_PinInit(GPIO3, 15U, &DI_GUN1_FB_config);

  /* GPIO configuration of DI_GUN2_FB on GPIO_SD_B0_03 (pin 45) */
  gpio_pin_config_t DI_GUN2_FB_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B0_03 (pin 45) */
  GPIO_PinInit(GPIO3, 16U, &DI_GUN2_FB_config);

  /* GPIO configuration of RS485_EN3 on GPIO_SD_B0_06 (pin 41) */
  gpio_pin_config_t RS485_EN3_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B0_06 (pin 41) */
  GPIO_PinInit(GPIO3, 19U, &RS485_EN3_config);

  /* GPIO configuration of RS485_EN4 on GPIO_SD_B1_04 (pin 27) */
  gpio_pin_config_t RS485_EN4_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_04 (pin 27) */
  GPIO_PinInit(GPIO3, 24U, &RS485_EN4_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_04_GPIO1_IO04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_05_GPIO1_IO05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_06_LPUART1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_07_LPUART1_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_08_ENET_REF_CLK1, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_09_ENET_RDATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_10_ENET_RDATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_11_ENET_RX_EN, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_ENET_RX_ER, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_ENET_TX_EN, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_14_ENET_TDATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_15_ENET_TDATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_00_GPIO1_IO16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_01_GPIO1_IO17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_GPIO1_IO18, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_GPIO1_IO19, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_04_GPIO1_IO20, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_05_GPIO1_IO21, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_LPUART2_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_09_LPUART2_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_GPIO1_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_GPIO1_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_12_GPIO1_IO28, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_13_GPIO1_IO29, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_14_GPIO1_IO30, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_15_GPIO1_IO31, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_00_GPIO2_IO00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_01_GPIO2_IO01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_02_LPI2C1_SCL, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_03_LPI2C1_SDA, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_04_XBAR1_INOUT04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_05_XBAR1_INOUT05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_06_LPUART3_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_07_LPUART3_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_08_FLEXCAN2_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_09_FLEXCAN2_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_10_XBAR1_INOUT10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_11_XBAR1_INOUT11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_12_LPUART6_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_13_LPUART6_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_16_GPIO2_IO16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_17_GPIO2_IO17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_18_XBAR1_INOUT16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_19_XBAR1_INOUT17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_20_GPIO2_IO20, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_21_GPIO2_IO21, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_22_GPIO2_IO22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_23_GPIO2_IO23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_24_GPIO2_IO24, 1U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_25_GPIO2_IO25, 1U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_26_GPIO2_IO26, 1U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_27_GPIO2_IO27, 1U);
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_32_LPUART4_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_33_LPUART4_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_34_GPIO3_IO02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_35_GPIO3_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_36_GPIO3_IO04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_37_GPIO3_IO05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_38_LPUART5_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_39_LPUART5_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_40_ENET_MDIO, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_41_ENET_MDC, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_00_GPIO3_IO13, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_01_XBAR1_INOUT15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_02_GPIO3_IO15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_03_GPIO3_IO16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_04_LPUART7_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_05_LPUART7_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_06_GPIO3_IO19, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_00_FLEXCAN1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_01_FLEXCAN1_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_02_LPUART8_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_03_LPUART8_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_04_GPIO3_IO24, 0U); 
  IOMUXC_GPR->GPR6 = ((IOMUXC_GPR->GPR6 &
    (~(IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_4_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_5_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_10_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_11_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_15_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_16_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_17_MASK))) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_4(0x01U) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_5(0x01U) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_10(0x01U) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_11(0x01U) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_15(0x01U) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_16(0x01U) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_17(0x01U) 
    );
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputQtimer1Tmr0, kXBARA1_OutputIomuxXbarInout04); 
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputQtimer1Tmr1, kXBARA1_OutputIomuxXbarInout05); 
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputQtimer1Tmr2, kXBARA1_OutputIomuxXbarInout10); 
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputQtimer1Tmr3, kXBARA1_OutputIomuxXbarInout11); 
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputQtimer2Tmr2, kXBARA1_OutputIomuxXbarInout15); 
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputQtimer2Tmr0, kXBARA1_OutputIomuxXbarInout16); 
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputQtimer2Tmr1, kXBARA1_OutputIomuxXbarInout17); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0x20B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0x10A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_04_GPIO1_IO04, 0xB0A9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_05_GPIO1_IO05, 0x60A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_06_LPUART1_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_07_LPUART1_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_08_ENET_REF_CLK1, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_09_ENET_RDATA01, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_10_ENET_RDATA00, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_11_ENET_RX_EN, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_12_ENET_RX_ER, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_13_ENET_TX_EN, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_14_ENET_TDATA00, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_15_ENET_TDATA01, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0xB0A9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_08_LPUART2_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_09_LPUART2_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_02_LPI2C1_SCL, 0xD8B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_03_LPI2C1_SDA, 0xD8B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_06_LPUART3_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_07_LPUART3_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_08_FLEXCAN2_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_09_FLEXCAN2_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_12_LPUART6_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_13_LPUART6_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_16_GPIO2_IO16, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_17_GPIO2_IO17, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_20_GPIO2_IO20, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_21_GPIO2_IO21, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_22_GPIO2_IO22, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_23_GPIO2_IO23, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_24_GPIO2_IO24, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_25_GPIO2_IO25, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_26_GPIO2_IO26, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_27_GPIO2_IO27, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_32_LPUART4_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_33_LPUART4_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_34_GPIO3_IO02, 0x70B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_38_LPUART5_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_39_LPUART5_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_40_ENET_MDIO, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_41_ENET_MDC, 0xB0E9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_00_GPIO3_IO13, 0x20B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_01_XBAR1_INOUT15, 0x10B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_04_LPUART7_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_05_LPUART7_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_06_GPIO3_IO19, 0x20B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_00_FLEXCAN1_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_01_FLEXCAN1_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_02_LPUART8_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_03_LPUART8_RX, 0x70B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_04_GPIO3_IO24, 0x20B0U); 
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
