/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_06 (number 105), UART1_TXD/J17[6] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_AD_B0_07 (number 101), UART1_RXD/J17[4] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_SD_B0_00 (number 48), SD1_D2/J15[1] */
/* Routed pin properties */
#define BOARD_INITPINS_IIC3_SCL_PERIPHERAL                                LPI2C3   /*!< Peripheral name */
#define BOARD_INITPINS_IIC3_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_SD_B0_01 (number 47), SD1_D3/J15[2] */
/* Routed pin properties */
#define BOARD_INITPINS_IIC3_SDA_PERIPHERAL                                LPI2C3   /*!< Peripheral name */
#define BOARD_INITPINS_IIC3_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_SD_B1_01 (number 32), CAN1_RX/U9[4] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN1_RX_PERIPHERAL                                   CAN1   /*!< Peripheral name */
#define BOARD_INITPINS_CAN1_RX_SIGNAL                                         RX   /*!< Signal name */

/* GPIO_SD_B1_00 (number 33), CAN1_TX/U9[1] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN1_TX_PERIPHERAL                                   CAN1   /*!< Peripheral name */
#define BOARD_INITPINS_CAN1_TX_SIGNAL                                         TX   /*!< Signal name */

/* GPIO_AD_B0_02 (number 109), GND */
/* Routed pin properties */
#define BOARD_INITPINS_RS485_EN1_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_RS485_EN1_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RS485_EN1_CHANNEL                                      2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS485_EN1_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RS485_EN1_INIT_GPIO_VALUE                              0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_RS485_EN1_GPIO_PIN                                     2U   /*!< GPIO pin number */
#define BOARD_INITPINS_RS485_EN1_GPIO_PIN_MASK                        (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RS485_EN1_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RS485_EN1_PIN                                          2U   /*!< PORT pin number */
#define BOARD_INITPINS_RS485_EN1_PIN_MASK                             (1U << 2U)   /*!< PORT pin mask */

/* GPIO_EMC_34 (number 122), SEMC_D10/U14[45] */
/* Routed pin properties */
#define BOARD_INITPINS_WDI_PFO_PERIPHERAL                                  GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_WDI_PFO_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_WDI_PFO_CHANNEL                                        2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_WDI_PFO_GPIO                                        GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_WDI_PFO_GPIO_PIN                                       2U   /*!< GPIO pin number */
#define BOARD_INITPINS_WDI_PFO_GPIO_PIN_MASK                          (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_WDI_PFO_PORT                                        GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_WDI_PFO_PIN                                            2U   /*!< PORT pin number */
#define BOARD_INITPINS_WDI_PFO_PIN_MASK                               (1U << 2U)   /*!< PORT pin mask */

/* GPIO_EMC_00 (number 18), DI_K1 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K1_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K1_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K1_CHANNEL                                          0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K1_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K1_GPIO_PIN                                         0U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K1_GPIO_PIN_MASK                            (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K1_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K1_PIN                                              0U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K1_PIN_MASK                                 (1U << 0U)   /*!< PORT pin mask */

/* GPIO_EMC_01 (number 17), DI_K2 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K2_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K2_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K2_CHANNEL                                          1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K2_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K2_GPIO_PIN                                         1U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K2_GPIO_PIN_MASK                            (1U << 1U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K2_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K2_PIN                                              1U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K2_PIN_MASK                                 (1U << 1U)   /*!< PORT pin mask */

/* GPIO_AD_B0_03 (number 108), JTAG_TDI/J16[5]/WDOG_B */
/* Routed pin properties */
#define BOARD_INITPINS_WDOG_B_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_WDOG_B_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_WDOG_B_CHANNEL                                         3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_WDOG_B_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_WDOG_B_INIT_GPIO_VALUE                                 0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_WDOG_B_GPIO_PIN                                        3U   /*!< GPIO pin number */
#define BOARD_INITPINS_WDOG_B_GPIO_PIN_MASK                           (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_WDOG_B_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_WDOG_B_PIN                                             3U   /*!< PORT pin number */
#define BOARD_INITPINS_WDOG_B_PIN_MASK                                (1U << 3U)   /*!< PORT pin mask */

/* GPIO_EMC_14 (number 1), DI_K15 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K15_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K15_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K15_CHANNEL                                        14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K15_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K15_GPIO_PIN                                       14U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K15_GPIO_PIN_MASK                          (1U << 14U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K15_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K15_PIN                                            14U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K15_PIN_MASK                               (1U << 14U)   /*!< PORT pin mask */

/* GPIO_EMC_13 (number 2), DI_K14 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K14_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K14_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K14_CHANNEL                                        13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K14_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K14_GPIO_PIN                                       13U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K14_GPIO_PIN_MASK                          (1U << 13U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K14_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K14_PIN                                            13U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K14_PIN_MASK                               (1U << 13U)   /*!< PORT pin mask */

/* GPIO_EMC_12 (number 3), DI_K13 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K13_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K13_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K13_CHANNEL                                        12U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K13_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K13_GPIO_PIN                                       12U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K13_GPIO_PIN_MASK                          (1U << 12U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K13_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K13_PIN                                            12U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K13_PIN_MASK                               (1U << 12U)   /*!< PORT pin mask */

/* GPIO_EMC_11 (number 4), DI_K12 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K12_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K12_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K12_CHANNEL                                        11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K12_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K12_GPIO_PIN                                       11U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K12_GPIO_PIN_MASK                          (1U << 11U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K12_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K12_PIN                                            11U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K12_PIN_MASK                               (1U << 11U)   /*!< PORT pin mask */

/* GPIO_EMC_15 (number 143), DI_K16 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K16_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K16_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K16_CHANNEL                                        15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K16_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K16_GPIO_PIN                                       15U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K16_GPIO_PIN_MASK                          (1U << 15U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K16_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K16_PIN                                            15U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K16_PIN_MASK                               (1U << 15U)   /*!< PORT pin mask */

/* GPIO_EMC_10 (number 7), DI_K11 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K11_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K11_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K11_CHANNEL                                        10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K11_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K11_GPIO_PIN                                       10U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K11_GPIO_PIN_MASK                          (1U << 10U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K11_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K11_PIN                                            10U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K11_PIN_MASK                               (1U << 10U)   /*!< PORT pin mask */

/* GPIO_EMC_09 (number 8), DI_K10 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K10_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K10_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K10_CHANNEL                                         9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K10_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K10_GPIO_PIN                                        9U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K10_GPIO_PIN_MASK                           (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K10_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K10_PIN                                             9U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K10_PIN_MASK                                (1U << 9U)   /*!< PORT pin mask */

/* GPIO_EMC_08 (number 9), DI_K9 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K9_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K9_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K9_CHANNEL                                          8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K9_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K9_GPIO_PIN                                         8U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K9_GPIO_PIN_MASK                            (1U << 8U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K9_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K9_PIN                                              8U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K9_PIN_MASK                                 (1U << 8U)   /*!< PORT pin mask */

/* GPIO_EMC_07 (number 10), DI_K8 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K8_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K8_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K8_CHANNEL                                          7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K8_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K8_GPIO_PIN                                         7U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K8_GPIO_PIN_MASK                            (1U << 7U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K8_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K8_PIN                                              7U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K8_PIN_MASK                                 (1U << 7U)   /*!< PORT pin mask */

/* GPIO_EMC_06 (number 12), DI_K7 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K7_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K7_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K7_CHANNEL                                          6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K7_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K7_GPIO_PIN                                         6U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K7_GPIO_PIN_MASK                            (1U << 6U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K7_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K7_PIN                                              6U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K7_PIN_MASK                                 (1U << 6U)   /*!< PORT pin mask */

/* GPIO_EMC_05 (number 13), DI_K6 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K6_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K6_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K6_CHANNEL                                          5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K6_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K6_GPIO_PIN                                         5U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K6_GPIO_PIN_MASK                            (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K6_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K6_PIN                                              5U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K6_PIN_MASK                                 (1U << 5U)   /*!< PORT pin mask */

/* GPIO_EMC_04 (number 14), DI_K5 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K5_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K5_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K5_CHANNEL                                          4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K5_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K5_GPIO_PIN                                         4U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K5_GPIO_PIN_MASK                            (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K5_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K5_PIN                                              4U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K5_PIN_MASK                                 (1U << 4U)   /*!< PORT pin mask */

/* GPIO_EMC_03 (number 15), DI_K4 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K4_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K4_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K4_CHANNEL                                          3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K4_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K4_GPIO_PIN                                         3U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K4_GPIO_PIN_MASK                            (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K4_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K4_PIN                                              3U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K4_PIN_MASK                                 (1U << 3U)   /*!< PORT pin mask */

/* GPIO_EMC_02 (number 16), DI_K3 */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K3_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K3_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K3_CHANNEL                                          2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K3_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K3_GPIO_PIN                                         2U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K3_GPIO_PIN_MASK                            (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K3_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K3_PIN                                              2U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K3_PIN_MASK                                 (1U << 2U)   /*!< PORT pin mask */

/* GPIO_EMC_33 (number 123), VER_SEL_2 */
/* Routed pin properties */
#define BOARD_INITPINS_VER_SEL_2_PERIPHERAL                                GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_VER_SEL_2_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_VER_SEL_2_CHANNEL                                      1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_VER_SEL_2_GPIO                                      GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_VER_SEL_2_GPIO_PIN                                     1U   /*!< GPIO pin number */
#define BOARD_INITPINS_VER_SEL_2_GPIO_PIN_MASK                        (1U << 1U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_VER_SEL_2_PORT                                      GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_VER_SEL_2_PIN                                          1U   /*!< PORT pin number */
#define BOARD_INITPINS_VER_SEL_2_PIN_MASK                             (1U << 1U)   /*!< PORT pin mask */

/* GPIO_EMC_32 (number 124), VER_SEL_1 */
/* Routed pin properties */
#define BOARD_INITPINS_VER_SEL_1_PERIPHERAL                                GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_VER_SEL_1_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_VER_SEL_1_CHANNEL                                      0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_VER_SEL_1_GPIO                                      GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_VER_SEL_1_GPIO_PIN                                     0U   /*!< GPIO pin number */
#define BOARD_INITPINS_VER_SEL_1_GPIO_PIN_MASK                        (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_VER_SEL_1_PORT                                      GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_VER_SEL_1_PIN                                          0U   /*!< PORT pin number */
#define BOARD_INITPINS_VER_SEL_1_PIN_MASK                             (1U << 0U)   /*!< PORT pin mask */

/* GPIO_EMC_31 (number 125), IO_ADD4 */
/* Routed pin properties */
#define BOARD_INITPINS_IO_ADD4_PERIPHERAL                                  GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_IO_ADD4_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_IO_ADD4_CHANNEL                                       31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IO_ADD4_GPIO                                        GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_IO_ADD4_GPIO_PIN                                      31U   /*!< GPIO pin number */
#define BOARD_INITPINS_IO_ADD4_GPIO_PIN_MASK                         (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_IO_ADD4_PORT                                        GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_IO_ADD4_PIN                                           31U   /*!< PORT pin number */
#define BOARD_INITPINS_IO_ADD4_PIN_MASK                              (1U << 31U)   /*!< PORT pin mask */

/* GPIO_EMC_30 (number 126), IO_ADD3 */
/* Routed pin properties */
#define BOARD_INITPINS_IO_ADD3_PERIPHERAL                                  GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_IO_ADD3_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_IO_ADD3_CHANNEL                                       30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IO_ADD3_GPIO                                        GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_IO_ADD3_GPIO_PIN                                      30U   /*!< GPIO pin number */
#define BOARD_INITPINS_IO_ADD3_GPIO_PIN_MASK                         (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_IO_ADD3_PORT                                        GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_IO_ADD3_PIN                                           30U   /*!< PORT pin number */
#define BOARD_INITPINS_IO_ADD3_PIN_MASK                              (1U << 30U)   /*!< PORT pin mask */

/* GPIO_EMC_29 (number 127), IO_ADD2 */
/* Routed pin properties */
#define BOARD_INITPINS_IO_ADD2_PERIPHERAL                                  GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_IO_ADD2_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_IO_ADD2_CHANNEL                                       29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IO_ADD2_GPIO                                        GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_IO_ADD2_GPIO_PIN                                      29U   /*!< GPIO pin number */
#define BOARD_INITPINS_IO_ADD2_GPIO_PIN_MASK                         (1U << 29U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_IO_ADD2_PORT                                        GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_IO_ADD2_PIN                                           29U   /*!< PORT pin number */
#define BOARD_INITPINS_IO_ADD2_PIN_MASK                              (1U << 29U)   /*!< PORT pin mask */

/* GPIO_EMC_28 (number 128), IO_ADD1 */
/* Routed pin properties */
#define BOARD_INITPINS_IO_ADD1_PERIPHERAL                                  GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_IO_ADD1_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_IO_ADD1_CHANNEL                                       28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IO_ADD1_GPIO                                        GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_IO_ADD1_GPIO_PIN                                      28U   /*!< GPIO pin number */
#define BOARD_INITPINS_IO_ADD1_GPIO_PIN_MASK                         (1U << 28U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_IO_ADD1_PORT                                        GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_IO_ADD1_PIN                                           28U   /*!< PORT pin number */
#define BOARD_INITPINS_IO_ADD1_PIN_MASK                              (1U << 28U)   /*!< PORT pin mask */

/* GPIO_AD_B0_15 (number 93), PCB_TEM1 */
/* Routed pin properties */
#define BOARD_INITPINS_PCB_TEM1_PERIPHERAL                                  ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_PCB_TEM1_SIGNAL                                        IN   /*!< Signal name */
#define BOARD_INITPINS_PCB_TEM1_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_AD_B0_13 (number 95), DCP_TEMP */
/* Routed pin properties */
#define BOARD_INITPINS_DCP_TEMP_PERIPHERAL                                  ADC2   /*!< Peripheral name */
#define BOARD_INITPINS_DCP_TEMP_SIGNAL                                        IN   /*!< Signal name */
#define BOARD_INITPINS_DCP_TEMP_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_AD_B0_12 (number 96), DCN_TEMP */
/* Routed pin properties */
#define BOARD_INITPINS_DCN_TEMP_PERIPHERAL                                  ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_DCN_TEMP_SIGNAL                                        IN   /*!< Signal name */
#define BOARD_INITPINS_DCN_TEMP_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_AD_B1_15 (number 74), K1 */
/* Routed pin properties */
#define BOARD_INITPINS_K1_PERIPHERAL                                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K1_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K1_CHANNEL                                            31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K1_GPIO                                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K1_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K1_GPIO_PIN                                           31U   /*!< GPIO pin number */
#define BOARD_INITPINS_K1_GPIO_PIN_MASK                              (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K1_PORT                                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K1_PIN                                                31U   /*!< PORT pin number */
#define BOARD_INITPINS_K1_PIN_MASK                                   (1U << 31U)   /*!< PORT pin mask */

/* GPIO_AD_B1_14 (number 75), K2 */
/* Routed pin properties */
#define BOARD_INITPINS_K2_PERIPHERAL                                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K2_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K2_CHANNEL                                            30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K2_GPIO                                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K2_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K2_GPIO_PIN                                           30U   /*!< GPIO pin number */
#define BOARD_INITPINS_K2_GPIO_PIN_MASK                              (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K2_PORT                                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K2_PIN                                                30U   /*!< PORT pin number */
#define BOARD_INITPINS_K2_PIN_MASK                                   (1U << 30U)   /*!< PORT pin mask */

/* GPIO_AD_B1_13 (number 76), K3 */
/* Routed pin properties */
#define BOARD_INITPINS_K3_PERIPHERAL                                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K3_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K3_CHANNEL                                            29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K3_GPIO                                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K3_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K3_GPIO_PIN                                           29U   /*!< GPIO pin number */
#define BOARD_INITPINS_K3_GPIO_PIN_MASK                              (1U << 29U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K3_PORT                                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K3_PIN                                                29U   /*!< PORT pin number */
#define BOARD_INITPINS_K3_PIN_MASK                                   (1U << 29U)   /*!< PORT pin mask */

/* GPIO_AD_B1_12 (number 78), K4 */
/* Routed pin properties */
#define BOARD_INITPINS_K4_PERIPHERAL                                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K4_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K4_CHANNEL                                            28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K4_GPIO                                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K4_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K4_GPIO_PIN                                           28U   /*!< GPIO pin number */
#define BOARD_INITPINS_K4_GPIO_PIN_MASK                              (1U << 28U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K4_PORT                                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K4_PIN                                                28U   /*!< PORT pin number */
#define BOARD_INITPINS_K4_PIN_MASK                                   (1U << 28U)   /*!< PORT pin mask */

/* GPIO_AD_B1_11 (number 79), K5 */
/* Routed pin properties */
#define BOARD_INITPINS_K5_PERIPHERAL                                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K5_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K5_CHANNEL                                            27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K5_GPIO                                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K5_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K5_GPIO_PIN                                           27U   /*!< GPIO pin number */
#define BOARD_INITPINS_K5_GPIO_PIN_MASK                              (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K5_PORT                                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K5_PIN                                                27U   /*!< PORT pin number */
#define BOARD_INITPINS_K5_PIN_MASK                                   (1U << 27U)   /*!< PORT pin mask */

/* GPIO_AD_B1_10 (number 80), K6 */
/* Routed pin properties */
#define BOARD_INITPINS_K6_PERIPHERAL                                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K6_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K6_CHANNEL                                            26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K6_GPIO                                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K6_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K6_GPIO_PIN                                           26U   /*!< GPIO pin number */
#define BOARD_INITPINS_K6_GPIO_PIN_MASK                              (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K6_PORT                                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K6_PIN                                                26U   /*!< PORT pin number */
#define BOARD_INITPINS_K6_PIN_MASK                                   (1U << 26U)   /*!< PORT pin mask */

/* GPIO_AD_B1_09 (number 81), K7 */
/* Routed pin properties */
#define BOARD_INITPINS_K7_PERIPHERAL                                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K7_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K7_CHANNEL                                            25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K7_GPIO                                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K7_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K7_GPIO_PIN                                           25U   /*!< GPIO pin number */
#define BOARD_INITPINS_K7_GPIO_PIN_MASK                              (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K7_PORT                                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K7_PIN                                                25U   /*!< PORT pin number */
#define BOARD_INITPINS_K7_PIN_MASK                                   (1U << 25U)   /*!< PORT pin mask */

/* GPIO_AD_B1_08 (number 82), K8 */
/* Routed pin properties */
#define BOARD_INITPINS_K8_PERIPHERAL                                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K8_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K8_CHANNEL                                            24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K8_GPIO                                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K8_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K8_GPIO_PIN                                           24U   /*!< GPIO pin number */
#define BOARD_INITPINS_K8_GPIO_PIN_MASK                              (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K8_PORT                                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K8_PIN                                                24U   /*!< PORT pin number */
#define BOARD_INITPINS_K8_PIN_MASK                                   (1U << 24U)   /*!< PORT pin mask */

/* GPIO_AD_B1_07 (number 83), K9 */
/* Routed pin properties */
#define BOARD_INITPINS_K9_PERIPHERAL                                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K9_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K9_CHANNEL                                            23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K9_GPIO                                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K9_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K9_GPIO_PIN                                           23U   /*!< GPIO pin number */
#define BOARD_INITPINS_K9_GPIO_PIN_MASK                              (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K9_PORT                                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K9_PIN                                                23U   /*!< PORT pin number */
#define BOARD_INITPINS_K9_PIN_MASK                                   (1U << 23U)   /*!< PORT pin mask */

/* GPIO_AD_B1_05 (number 87), K11 */
/* Routed pin properties */
#define BOARD_INITPINS_K11_PERIPHERAL                                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K11_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K11_CHANNEL                                           21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K11_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K11_INIT_GPIO_VALUE                                    0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K11_GPIO_PIN                                          21U   /*!< GPIO pin number */
#define BOARD_INITPINS_K11_GPIO_PIN_MASK                             (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K11_PORT                                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K11_PIN                                               21U   /*!< PORT pin number */
#define BOARD_INITPINS_K11_PIN_MASK                                  (1U << 21U)   /*!< PORT pin mask */

/* GPIO_AD_B1_04 (number 88), K12 */
/* Routed pin properties */
#define BOARD_INITPINS_K12_PERIPHERAL                                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K12_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K12_CHANNEL                                           20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K12_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K12_INIT_GPIO_VALUE                                    0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K12_GPIO_PIN                                          20U   /*!< GPIO pin number */
#define BOARD_INITPINS_K12_GPIO_PIN_MASK                             (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K12_PORT                                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K12_PIN                                               20U   /*!< PORT pin number */
#define BOARD_INITPINS_K12_PIN_MASK                                  (1U << 20U)   /*!< PORT pin mask */

/* GPIO_AD_B1_03 (number 89), K13 */
/* Routed pin properties */
#define BOARD_INITPINS_K13_PERIPHERAL                                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K13_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K13_CHANNEL                                           19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K13_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K13_INIT_GPIO_VALUE                                    0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K13_GPIO_PIN                                          19U   /*!< GPIO pin number */
#define BOARD_INITPINS_K13_GPIO_PIN_MASK                             (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K13_PORT                                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K13_PIN                                               19U   /*!< PORT pin number */
#define BOARD_INITPINS_K13_PIN_MASK                                  (1U << 19U)   /*!< PORT pin mask */

/* GPIO_AD_B1_02 (number 90), K14 */
/* Routed pin properties */
#define BOARD_INITPINS_K14_PERIPHERAL                                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K14_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K14_CHANNEL                                           18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K14_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K14_INIT_GPIO_VALUE                                    0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K14_GPIO_PIN                                          18U   /*!< GPIO pin number */
#define BOARD_INITPINS_K14_GPIO_PIN_MASK                             (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K14_PORT                                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K14_PIN                                               18U   /*!< PORT pin number */
#define BOARD_INITPINS_K14_PIN_MASK                                  (1U << 18U)   /*!< PORT pin mask */

/* GPIO_AD_B1_01 (number 91), K15 */
/* Routed pin properties */
#define BOARD_INITPINS_K15_PERIPHERAL                                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K15_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K15_CHANNEL                                           17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K15_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K15_INIT_GPIO_VALUE                                    0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K15_GPIO_PIN                                          17U   /*!< GPIO pin number */
#define BOARD_INITPINS_K15_GPIO_PIN_MASK                             (1U << 17U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K15_PORT                                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K15_PIN                                               17U   /*!< PORT pin number */
#define BOARD_INITPINS_K15_PIN_MASK                                  (1U << 17U)   /*!< PORT pin mask */

/* GPIO_AD_B1_00 (number 92), K16 */
/* Routed pin properties */
#define BOARD_INITPINS_K16_PERIPHERAL                                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K16_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K16_CHANNEL                                           16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K16_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K16_INIT_GPIO_VALUE                                    0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K16_GPIO_PIN                                          16U   /*!< GPIO pin number */
#define BOARD_INITPINS_K16_GPIO_PIN_MASK                             (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K16_PORT                                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K16_PIN                                               16U   /*!< PORT pin number */
#define BOARD_INITPINS_K16_PIN_MASK                                  (1U << 16U)   /*!< PORT pin mask */

/* GPIO_AD_B1_06 (number 84), K10 */
/* Routed pin properties */
#define BOARD_INITPINS_K10_PERIPHERAL                                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_K10_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K10_CHANNEL                                           22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K10_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K10_INIT_GPIO_VALUE                                    0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_K10_GPIO_PIN                                          22U   /*!< GPIO pin number */
#define BOARD_INITPINS_K10_GPIO_PIN_MASK                             (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K10_PORT                                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K10_PIN                                               22U   /*!< PORT pin number */
#define BOARD_INITPINS_K10_PIN_MASK                                  (1U << 22U)   /*!< PORT pin mask */

/* GPIO_AD_B0_05 (number 106), USER_LED */
/* Routed pin properties */
#define BOARD_INITPINS_RUN_LED_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_RUN_LED_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RUN_LED_CHANNEL                                        5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RUN_LED_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RUN_LED_INIT_GPIO_VALUE                                0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_RUN_LED_GPIO_PIN                                       5U   /*!< GPIO pin number */
#define BOARD_INITPINS_RUN_LED_GPIO_PIN_MASK                          (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RUN_LED_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RUN_LED_PIN                                            5U   /*!< PORT pin number */
#define BOARD_INITPINS_RUN_LED_PIN_MASK                               (1U << 5U)   /*!< PORT pin mask */

/* GPIO_AD_B0_14 (number 94), PCB_TEM2 */
/* Routed pin properties */
#define BOARD_INITPINS_PCB_TEM2_PERIPHERAL                                  ADC2   /*!< Peripheral name */
#define BOARD_INITPINS_PCB_TEM2_SIGNAL                                        IN   /*!< Signal name */
#define BOARD_INITPINS_PCB_TEM2_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_AD_B0_10 (number 98), ENET_RXD0/U11[16]/J19[6] */
/* Routed pin properties */
#define BOARD_INITPINS_LED1_PERIPHERAL                                     GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LED1_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED1_CHANNEL                                          10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED1_GPIO                                           GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED1_INIT_GPIO_VALUE                                   0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_LED1_GPIO_PIN                                         10U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED1_GPIO_PIN_MASK                            (1U << 10U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED1_PORT                                           GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED1_PIN                                              10U   /*!< PORT pin number */
#define BOARD_INITPINS_LED1_PIN_MASK                                 (1U << 10U)   /*!< PORT pin mask */

/* GPIO_AD_B0_09 (number 99), ENET_RXD1/U11[15]/J17[3] */
/* Routed pin properties */
#define BOARD_INITPINS_LED2_PERIPHERAL                                     GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LED2_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED2_CHANNEL                                           9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED2_GPIO                                           GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED2_INIT_GPIO_VALUE                                   0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_LED2_GPIO_PIN                                          9U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED2_GPIO_PIN_MASK                             (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED2_PORT                                           GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED2_PIN                                               9U   /*!< PORT pin number */
#define BOARD_INITPINS_LED2_PIN_MASK                                  (1U << 9U)   /*!< PORT pin mask */

/* GPIO_AD_B0_08 (number 100), ENET_TX_CLK/U11[9] */
/* Routed pin properties */
#define BOARD_INITPINS_LED3_PERIPHERAL                                     GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LED3_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED3_CHANNEL                                           8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED3_GPIO                                           GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED3_INIT_GPIO_VALUE                                   0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_LED3_GPIO_PIN                                          8U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED3_GPIO_PIN_MASK                             (1U << 8U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED3_PORT                                           GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED3_PIN                                               8U   /*!< PORT pin number */
#define BOARD_INITPINS_LED3_PIN_MASK                                  (1U << 8U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
