/*
 * hal_sys_IF.h
 *
 *  Created on: 2024年9月5日
 *      Author: Bono
 */

#ifndef HAL_HAL_SYS_HAL_SYS_IF_H_
#define HAL_HAL_SYS_HAL_SYS_IF_H_

#include "clock_config.h"
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "pin_mux.h"
#include "SignalManage.h"
#include "PublicDefine.h"



#define LOGIC_LED_ON  (0U)
#define LOGIC_LED_OFF (1U)
#ifndef USER_LED_GPIO
#define USER_LED_GPIO GPIO1
#endif
#ifndef USER_LED_GPIO_PIN
#define USER_LED_GPIO_PIN (5U)
#endif



#define USER_LED_ON()		GPIO_PortClear(USER_LED_GPIO, 1U << USER_LED_GPIO_PIN)
#define USER_LED_OFF()		GPIO_PortSet(USER_LED_GPIO, 1U << USER_LED_GPIO_PIN)
#define USER_LED_TOGGLE()	GPIO_PinWrite(USER_LED_GPIO, USER_LED_GPIO_PIN, 0x1 ^ GPIO_PinRead(USER_LED_GPIO, USER_LED_GPIO_PIN))

#define RS485_EN1_ENABLE()	GPIO_PortSet(BOARD_INITPINS_RS485_EN1_GPIO, 1U << BOARD_INITPINS_RS485_EN1_GPIO_PIN)
#define RS485_EN1_DISABLE()	GPIO_PortClear(BOARD_INITPINS_RS485_EN1_GPIO, 1U << BOARD_INITPINS_RS485_EN1_GPIO_PIN)

#define RS485_EN2_ENABLE()	GPIO_PortSet(BOARD_INITPINS_RS485_EN2_GPIO, 1UL << BOARD_INITPINS_RS485_EN2_GPIO_PIN)
#define RS485_EN2_DISABLE()	GPIO_PortClear(BOARD_INITPINS_RS485_EN2_GPIO, 1UL << BOARD_INITPINS_RS485_EN2_GPIO_PIN)

#define RS485_EN3_ENABLE()	GPIO_PortSet(BOARD_INITPINS_RS485_EN3_GPIO, 1UL << BOARD_INITPINS_RS485_EN3_GPIO_PIN)
#define RS485_EN3_DISABLE()	GPIO_PortClear(BOARD_INITPINS_RS485_EN3_GPIO, 1UL << BOARD_INITPINS_RS485_EN3_GPIO_PIN)

#define RS485_EN4_ENABLE()	GPIO_PortSet(BOARD_INITPINS_RS485_EN4_GPIO, 1UL << BOARD_INITPINS_RS485_EN4_GPIO_PIN)
#define RS485_EN4_DISABLE()	GPIO_PortClear(BOARD_INITPINS_RS485_EN4_GPIO, 1UL << BOARD_INITPINS_RS485_EN4_GPIO_PIN)

#define WDOG_WDI_TOGGLE()	GPIO_PinWrite(BOARD_INITPINS_WDOG_B_GPIO, BOARD_INITPINS_WDOG_B_GPIO_PIN, 0x1 ^ GPIO_PinRead(BOARD_INITPINS_WDOG_B_GPIO, BOARD_INITPINS_WDOG_B_GPIO_PIN))

/***************Relay******************/
#define POSITIVE_RELAY_A_ON()	GPIO_PortSet(BOARD_INITPINS_K1_GPIO, 1UL << BOARD_INITPINS_K1_GPIO_PIN)
#define POSITIVE_RELAY_A_OFF()	GPIO_PortClear(BOARD_INITPINS_K1_GPIO, 1UL << BOARD_INITPINS_K1_GPIO_PIN)

#define NEGATIVE_RELAY_A_ON()	GPIO_PortSet(BOARD_INITPINS_K2_GPIO, 1UL << BOARD_INITPINS_K2_GPIO_PIN)
#define NEGATIVE_RELAY_A_OFF()	GPIO_PortClear(BOARD_INITPINS_K2_GPIO, 1UL << BOARD_INITPINS_K2_GPIO_PIN)

#define POSITIVE_RELAY_B_ON()	GPIO_PortSet(BOARD_INITPINS_K3_GPIO, 1UL << BOARD_INITPINS_K3_GPIO_PIN)
#define POSITIVE_RELAY_B_OFF()	GPIO_PortClear(BOARD_INITPINS_K3_GPIO, 1UL << BOARD_INITPINS_K3_GPIO_PIN)

#define NEGATIVE_RELAY_B_ON()	GPIO_PortSet(BOARD_INITPINS_K4_GPIO, 1UL << BOARD_INITPINS_K4_GPIO_PIN)
#define NEGATIVE_RELAY_B_OFF()	GPIO_PortClear(BOARD_INITPINS_K4_GPIO, 1UL << BOARD_INITPINS_K4_GPIO_PIN)

#define PRECHARGE_RELAY_A_ON()	GPIO_PortSet(BOARD_INITPINS_K5_GPIO, 1UL << BOARD_INITPINS_K5_GPIO_PIN)
#define PRECHARGE_RELAY_A_OFF()	GPIO_PortClear(BOARD_INITPINS_K5_GPIO, 1UL << BOARD_INITPINS_K5_GPIO_PIN)

#define PRECHARGE_RELAY_B_ON()	GPIO_PortSet(BOARD_INITPINS_K6_GPIO, 1UL << BOARD_INITPINS_K6_GPIO_PIN)
#define PRECHARGE_RELAY_B_OFF()	GPIO_PortClear(BOARD_INITPINS_K6_GPIO, 1UL << BOARD_INITPINS_K6_GPIO_PIN)
//硬件上做了电平反向，K7继电器更改电平方向，
#define HMI_LIGHT_RELAY_OFF()	GPIO_PortSet(BOARD_INITPINS_K7_GPIO, 1UL << BOARD_INITPINS_K7_GPIO_PIN)
#define HMI_LIGHT_RELAY_ON()	GPIO_PortClear(BOARD_INITPINS_K7_GPIO, 1UL << BOARD_INITPINS_K7_GPIO_PIN)

#define FAN_RELAY_ON()			GPIO_PortSet(BOARD_INITPINS_K8_GPIO, 1UL << BOARD_INITPINS_K8_GPIO_PIN)
#define FAN_RELAY_OFF()			GPIO_PortClear(BOARD_INITPINS_K8_GPIO, 1UL << BOARD_INITPINS_K8_GPIO_PIN)

/***************DI******************/
#define GET_FU1_FB_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_FU1_FB_GPIO, BOARD_INITPINS_DI_FU1_FB_GPIO_PIN)
#define GET_FU2_FB_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_FU2_FB_GPIO, BOARD_INITPINS_DI_FU2_FB_GPIO_PIN)
#define GET_POSITIVE_RELAY_A_FB_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_K1_FB_GPIO, BOARD_INITPINS_DI_K1_FB_GPIO_PIN)
#define GET_NEGATIVE_RELAY_A_FB_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_K2_FB_GPIO, BOARD_INITPINS_DI_K2_FB_GPIO_PIN)
#define GET_POSITIVE_RELAY_B_FB_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_K3_FB_GPIO, BOARD_INITPINS_DI_K3_FB_GPIO_PIN)
#define GET_NEGATIVE_RELAY_B_FB_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_K4_FB_GPIO, BOARD_INITPINS_DI_K4_FB_GPIO_PIN)
#define GET_GUN1_FB_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_GUN1_FB_GPIO, BOARD_INITPINS_DI_GUN1_FB_GPIO_PIN)
#define GET_GUN2_FB_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_GUN2_FB_GPIO, BOARD_INITPINS_DI_GUN2_FB_GPIO_PIN)

#define GET_DI_SCRAM_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_Scram_GPIO, BOARD_INITPINS_DI_Scram_GPIO_PIN)
#define GET_DI_SPD_STATUS()		GPIO_PinRead(BOARD_INITPINS_DI_SPD_GPIO, BOARD_INITPINS_DI_SPD_GPIO_PIN)
#define GET_DI_HIT_STATUS()		GPIO_PinRead(BOARD_INITPINS_DI_Hit_GPIO, BOARD_INITPINS_DI_Hit_GPIO_PIN)
#define GET_DI_WATER_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_Water_GPIO, BOARD_INITPINS_DI_Water_GPIO_PIN)
#define GET_DI_DOOR_STATUS()	GPIO_PinRead(BOARD_INITPINS_DI_Door_GPIO, BOARD_INITPINS_DI_Door_GPIO_PIN)
#define GET_DI_MCB_STATUS()		GPIO_PinRead(BOARD_INITPINS_DI_MCB_GPIO, BOARD_INITPINS_DI_MCB_GPIO_PIN)
#define GET_WDI_PFO_STATUS()	GPIO_PinRead(BOARD_INITPINS_WDI_PFO_GPIO, BOARD_INITPINS_WDI_PFO_GPIO_PIN)

#define LED_RED_A_ON()		GPIO_PortSet(BOARD_INITPINS_LED_OUT1_GPIO, 1U << BOARD_INITPINS_LED_OUT1_GPIO_PIN)
#define LED_RED_A_OFF()		GPIO_PortClear(BOARD_INITPINS_LED_OUT1_GPIO, 1U << BOARD_INITPINS_LED_OUT1_GPIO_PIN)
#define LED_GREEN_A_ON()	GPIO_PortSet(BOARD_INITPINS_LED_OUT2_GPIO, 1U << BOARD_INITPINS_LED_OUT2_GPIO_PIN)
#define LED_GREEN_A_OFF()	GPIO_PortClear(BOARD_INITPINS_LED_OUT2_GPIO, 1U << BOARD_INITPINS_LED_OUT2_GPIO_PIN)
#define LED_BLUE_A_ON()		GPIO_PortSet(BOARD_INITPINS_LED_OUT3_GPIO, 1U << BOARD_INITPINS_LED_OUT3_GPIO_PIN)
#define LED_BLUE_A_OFF()	GPIO_PortClear(BOARD_INITPINS_LED_OUT3_GPIO, 1U << BOARD_INITPINS_LED_OUT3_GPIO_PIN)

#define LED_RED_B_ON()		GPIO_PortSet(BOARD_INITPINS_LED_OUT4_GPIO, 1U << BOARD_INITPINS_LED_OUT4_GPIO_PIN)
#define LED_RED_B_OFF()		GPIO_PortClear(BOARD_INITPINS_LED_OUT4_GPIO, 1U << BOARD_INITPINS_LED_OUT4_GPIO_PIN)
#define LED_GREEN_B_ON()	GPIO_PortSet(BOARD_INITPINS_LED_OUT5_GPIO, 1U << BOARD_INITPINS_LED_OUT5_GPIO_PIN)
#define LED_GREEN_B_OFF()	GPIO_PortClear(BOARD_INITPINS_LED_OUT5_GPIO, 1U << BOARD_INITPINS_LED_OUT5_GPIO_PIN)
#define LED_BLUE_B_ON()		GPIO_PortSet(BOARD_INITPINS_LED_OUT6_GPIO, 1U << BOARD_INITPINS_LED_OUT6_GPIO_PIN)
#define LED_BLUE_B_OFF()	GPIO_PortClear(BOARD_INITPINS_LED_OUT6_GPIO, 1U << BOARD_INITPINS_LED_OUT6_GPIO_PIN)

extern void Hal_InitEnetModuleClock(void);
extern void Hal_I2c_Init(void);
extern void ctrl_relay_cmd(U8 cmd);
void AllLedToggle(void);
void FeedWatchDog(void);
void SetSysShuttingDownModeFg(void);
void SetSysNormalModeFg(void);
void SetSysPowerOffModeFg(void);

#endif /* HAL_HAL_SYS_HAL_SYS_IF_H_ */
