/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_05 (number 106), USER_LED */
/* Routed pin properties */
#define BOARD_INITPINS_RUN_LED_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_RUN_LED_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RUN_LED_CHANNEL                                        5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RUN_LED_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RUN_LED_GPIO_PIN                                       5U   /*!< GPIO pin number */
#define BOARD_INITPINS_RUN_LED_GPIO_PIN_MASK                          (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RUN_LED_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RUN_LED_PIN                                            5U   /*!< PORT pin number */
#define BOARD_INITPINS_RUN_LED_PIN_MASK                               (1U << 5U)   /*!< PORT pin mask */

/* GPIO_AD_B0_06 (number 105), UART1_TXD/J17[6] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_AD_B0_07 (number 101), UART1_RXD/J17[4] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_EMC_22 (number 136), CD4052B_CHA */
/* Routed pin properties */
#define BOARD_INITPINS_CD4052_CHA_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_CD4052_CHA_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_CD4052_CHA_CHANNEL                                    22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CD4052_CHA_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_CD4052_CHA_GPIO_PIN                                   22U   /*!< GPIO pin number */
#define BOARD_INITPINS_CD4052_CHA_GPIO_PIN_MASK                      (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_CD4052_CHA_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_CD4052_CHA_PIN                                        22U   /*!< PORT pin number */
#define BOARD_INITPINS_CD4052_CHA_PIN_MASK                           (1U << 22U)   /*!< PORT pin mask */

/* GPIO_EMC_23 (number 133), CD4052B_CHB */
/* Routed pin properties */
#define BOARD_INITPINS_CD4052_CHB_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_CD4052_CHB_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_CD4052_CHB_CHANNEL                                    23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CD4052_CHB_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_CD4052_CHB_GPIO_PIN                                   23U   /*!< GPIO pin number */
#define BOARD_INITPINS_CD4052_CHB_GPIO_PIN_MASK                      (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_CD4052_CHB_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_CD4052_CHB_PIN                                        23U   /*!< PORT pin number */
#define BOARD_INITPINS_CD4052_CHB_PIN_MASK                           (1U << 23U)   /*!< PORT pin mask */

/* GPIO_EMC_06 (number 12), SEMC_D6/U14[11] */
/* Routed pin properties */
#define BOARD_INITPINS_UART3_TX_PERIPHERAL                               LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_UART3_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_EMC_07 (number 10), SEMC_D7/U14[13] */
/* Routed pin properties */
#define BOARD_INITPINS_UART3_RX_PERIPHERAL                               LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_UART3_RX_SIGNAL                                        RX   /*!< Signal name */

/* GPIO_EMC_33 (number 123), SEMC_D9/U14[44] */
/* Routed pin properties */
#define BOARD_INITPINS_UART4_RX_PERIPHERAL                               LPUART4   /*!< Peripheral name */
#define BOARD_INITPINS_UART4_RX_SIGNAL                                        RX   /*!< Signal name */

/* GPIO_EMC_32 (number 124), SEMC_D8/U14[42] */
/* Routed pin properties */
#define BOARD_INITPINS_UART4_TX_PERIPHERAL                               LPUART4   /*!< Peripheral name */
#define BOARD_INITPINS_UART4_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_EMC_39 (number 117), SEMC_D15/U14[53] */
/* Routed pin properties */
#define BOARD_INITPINS_UART5_RX_PERIPHERAL                               LPUART5   /*!< Peripheral name */
#define BOARD_INITPINS_UART5_RX_SIGNAL                                        RX   /*!< Signal name */

/* GPIO_EMC_38 (number 118), SEMC_D14/U14[51] */
/* Routed pin properties */
#define BOARD_INITPINS_UART5_TX_PERIPHERAL                               LPUART5   /*!< Peripheral name */
#define BOARD_INITPINS_UART5_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_EMC_13 (number 2), SEMC_BA0/U14[20] */
/* Routed pin properties */
#define BOARD_INITPINS_UART6_RX_PERIPHERAL                               LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_UART6_RX_SIGNAL                                        RX   /*!< Signal name */

/* GPIO_EMC_12 (number 3), SEMC_CS0/U14[19] */
/* Routed pin properties */
#define BOARD_INITPINS_UART6_TX_PERIPHERAL                               LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_UART6_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_SD_B0_05 (number 42), SD1_D1/J15[8] */
/* Routed pin properties */
#define BOARD_INITPINS_UART7_RX_PERIPHERAL                               LPUART7   /*!< Peripheral name */
#define BOARD_INITPINS_UART7_RX_SIGNAL                                        RX   /*!< Signal name */

/* GPIO_SD_B0_04 (number 43), SD1_D0/J15[7] */
/* Routed pin properties */
#define BOARD_INITPINS_UART7_TX_PERIPHERAL                               LPUART7   /*!< Peripheral name */
#define BOARD_INITPINS_UART7_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_SD_B1_02 (number 30), I2C4_SCL */
/* Routed pin properties */
#define BOARD_INITPINS_UART8_TX_PERIPHERAL                               LPUART8   /*!< Peripheral name */
#define BOARD_INITPINS_UART8_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_SD_B1_03 (number 28), I2C4_SDA */
/* Routed pin properties */
#define BOARD_INITPINS_UART8_RX_PERIPHERAL                               LPUART8   /*!< Peripheral name */
#define BOARD_INITPINS_UART8_RX_SIGNAL                                        RX   /*!< Signal name */

/* GPIO_SD_B0_00 (number 48), RS485_EN2 */
/* Routed pin properties */
#define BOARD_INITPINS_RS485_EN2_PERIPHERAL                                GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_RS485_EN2_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RS485_EN2_CHANNEL                                     13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS485_EN2_GPIO                                      GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RS485_EN2_GPIO_PIN                                    13U   /*!< GPIO pin number */
#define BOARD_INITPINS_RS485_EN2_GPIO_PIN_MASK                       (1U << 13U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RS485_EN2_PORT                                      GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RS485_EN2_PIN                                         13U   /*!< PORT pin number */
#define BOARD_INITPINS_RS485_EN2_PIN_MASK                            (1U << 13U)   /*!< PORT pin mask */

/* GPIO_SD_B0_01 (number 47), FAN */
/* Routed pin properties */
#define BOARD_INITPINS_FAN_PERIPHERAL                                       TMR2   /*!< Peripheral name */
#define BOARD_INITPINS_FAN_SIGNAL                                   TIMER_OUTPUT   /*!< Signal name */
#define BOARD_INITPINS_FAN_CHANNEL                                            2U   /*!< Signal channel */

/* GPIO_EMC_02 (number 16), SEMC_D2/U14[5] */
/* Routed pin properties */
#define BOARD_INITPINS_IIC1_SCL_PERIPHERAL                                LPI2C1   /*!< Peripheral name */
#define BOARD_INITPINS_IIC1_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_EMC_03 (number 15), SEMC_D3/U14[7] */
/* Routed pin properties */
#define BOARD_INITPINS_IIC1_SDA_PERIPHERAL                                LPI2C1   /*!< Peripheral name */
#define BOARD_INITPINS_IIC1_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_SD_B1_01 (number 32), CAN1_RX/U9[4] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN1_RX_PERIPHERAL                                   CAN1   /*!< Peripheral name */
#define BOARD_INITPINS_CAN1_RX_SIGNAL                                         RX   /*!< Signal name */

/* GPIO_SD_B1_00 (number 33), CAN1_TX/U9[1] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN1_TX_PERIPHERAL                                   CAN1   /*!< Peripheral name */
#define BOARD_INITPINS_CAN1_TX_SIGNAL                                         TX   /*!< Signal name */

/* GPIO_EMC_09 (number 8), CAN2_RX */
/* Routed pin properties */
#define BOARD_INITPINS_CAN2_RX_PERIPHERAL                                   CAN2   /*!< Peripheral name */
#define BOARD_INITPINS_CAN2_RX_SIGNAL                                         RX   /*!< Signal name */

/* GPIO_EMC_08 (number 9), CAN2_TX */
/* Routed pin properties */
#define BOARD_INITPINS_CAN2_TX_PERIPHERAL                                   CAN2   /*!< Peripheral name */
#define BOARD_INITPINS_CAN2_TX_SIGNAL                                         TX   /*!< Signal name */

/* GPIO_AD_B0_02 (number 109), GND */
/* Routed pin properties */
#define BOARD_INITPINS_RS485_EN1_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_RS485_EN1_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RS485_EN1_CHANNEL                                      2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS485_EN1_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RS485_EN1_GPIO_PIN                                     2U   /*!< GPIO pin number */
#define BOARD_INITPINS_RS485_EN1_GPIO_PIN_MASK                        (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RS485_EN1_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RS485_EN1_PIN                                          2U   /*!< PORT pin number */
#define BOARD_INITPINS_RS485_EN1_PIN_MASK                             (1U << 2U)   /*!< PORT pin mask */

/* GPIO_SD_B0_06 (number 41), RS485_EN3 */
/* Routed pin properties */
#define BOARD_INITPINS_RS485_EN3_PERIPHERAL                                GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_RS485_EN3_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RS485_EN3_CHANNEL                                     19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS485_EN3_GPIO                                      GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RS485_EN3_GPIO_PIN                                    19U   /*!< GPIO pin number */
#define BOARD_INITPINS_RS485_EN3_GPIO_PIN_MASK                       (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RS485_EN3_PORT                                      GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RS485_EN3_PIN                                         19U   /*!< PORT pin number */
#define BOARD_INITPINS_RS485_EN3_PIN_MASK                            (1U << 19U)   /*!< PORT pin mask */

/* GPIO_SD_B1_04 (number 27), RS485_EN4 */
/* Routed pin properties */
#define BOARD_INITPINS_RS485_EN4_PERIPHERAL                                GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_RS485_EN4_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RS485_EN4_CHANNEL                                     24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS485_EN4_GPIO                                      GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RS485_EN4_GPIO_PIN                                    24U   /*!< GPIO pin number */
#define BOARD_INITPINS_RS485_EN4_GPIO_PIN_MASK                       (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RS485_EN4_PORT                                      GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RS485_EN4_PIN                                         24U   /*!< PORT pin number */
#define BOARD_INITPINS_RS485_EN4_PIN_MASK                            (1U << 24U)   /*!< PORT pin mask */

/* GPIO_EMC_40 (number 116), ENET_MDIO/U11[11] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_MDIO_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_MDIO_SIGNAL                                enet_mdio   /*!< Signal name */

/* GPIO_EMC_41 (number 115), ENET_MDC/U11[12] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_MDC_PERIPHERAL                                  ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_MDC_SIGNAL                                  enet_mdc   /*!< Signal name */

/* GPIO_AD_B1_08 (number 82), SEMC_A6/U14[31]/BT_CFG[4] */
/* Routed pin properties */
#define BOARD_INITPINS_UART2_TX_PERIPHERAL                               LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_UART2_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_AD_B1_09 (number 81), SEMC_A7/U14[32]/BT_CFG[5] */
/* Routed pin properties */
#define BOARD_INITPINS_UART2_RX_PERIPHERAL                               LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_UART2_RX_SIGNAL                                        RX   /*!< Signal name */

/* GPIO_AD_B0_08 (number 100), ENET_TX_CLK/U11[9] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TX_CLK_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TX_CLK_SIGNAL                           enet_ref_clk   /*!< Signal name */

/* GPIO_AD_B0_10 (number 98), ENET_RXD0/U11[16]/J19[6] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXD0_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_AD_B0_09 (number 99), ENET_RXD1/U11[15]/J17[3] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXD1_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_AD_B0_11 (number 97), ENET_CRS_DV/U11[18]/J19[3] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_CRS_DV_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_CRS_DV_SIGNAL                             enet_rx_en   /*!< Signal name */

/* GPIO_AD_B0_12 (number 96), ENET_RXER/U11[20]/J19[4] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXER_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXER_SIGNAL                               enet_rx_er   /*!< Signal name */

/* GPIO_AD_B0_14 (number 94), ENET_TXD0/U11[24]/J17[7] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXD0_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_AD_B0_15 (number 93), ENET_TXD1/U11[25]/J19[2] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXD1_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_AD_B0_13 (number 95), ENET_TXEN/U11[23]/J19[5] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXEN_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXEN_SIGNAL                               enet_tx_en   /*!< Signal name */

/* GPIO_AD_B0_04 (number 107), JTAG_TDO/J16[13]/ENET_RST/U11[32] */
/* Routed pin properties */
#define BOARD_INITPINS_PHY_RST_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_PHY_RST_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_PHY_RST_CHANNEL                                        4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PHY_RST_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_PHY_RST_GPIO_PIN                                       4U   /*!< GPIO pin number */
#define BOARD_INITPINS_PHY_RST_GPIO_PIN_MASK                          (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_PHY_RST_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_PHY_RST_PIN                                            4U   /*!< PORT pin number */
#define BOARD_INITPINS_PHY_RST_PIN_MASK                               (1U << 4U)   /*!< PORT pin mask */

/* GPIO_AD_B1_06 (number 84), ENET_INT/U11[21]/J17[8] */
/* Routed pin properties */
#define BOARD_INITPINS_PHY_INT_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_PHY_INT_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_PHY_INT_CHANNEL                                       22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PHY_INT_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_PHY_INT_GPIO_PIN                                      22U   /*!< GPIO pin number */
#define BOARD_INITPINS_PHY_INT_GPIO_PIN_MASK                         (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_PHY_INT_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_PHY_INT_PIN                                           22U   /*!< PORT pin number */
#define BOARD_INITPINS_PHY_INT_PIN_MASK                              (1U << 22U)   /*!< PORT pin mask */

/* GPIO_AD_B1_11 (number 79), USB_OTG1_ID/J18[2] */
/* Routed pin properties */
#define BOARD_INITPINS_ADCX_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADCX_SIGNAL                                            IN   /*!< Signal name */
#define BOARD_INITPINS_ADCX_CHANNEL                                          11U   /*!< Signal channel */

/* GPIO_AD_B1_10 (number 80), USB_OTG1_PWR/J18[1] */
/* Routed pin properties */
#define BOARD_INITPINS_ADCY_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADCY_SIGNAL                                            IN   /*!< Signal name */
#define BOARD_INITPINS_ADCY_CHANNEL                                          10U   /*!< Signal channel */

/* GPIO_AD_B1_12 (number 78), USB_OTG1_OC/J18[3] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_G1_T1_PERIPHERAL                                 ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_G1_T1_SIGNAL                                       IN   /*!< Signal name */
#define BOARD_INITPINS_ADC_G1_T1_CHANNEL                                     12U   /*!< Signal channel */

/* GPIO_AD_B1_13 (number 76), CAN_STBY/J18[4] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_G1_T2_PERIPHERAL                                 ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_G1_T2_SIGNAL                                       IN   /*!< Signal name */
#define BOARD_INITPINS_ADC_G1_T2_CHANNEL                                     13U   /*!< Signal channel */

/* GPIO_AD_B1_14 (number 75), I2C1_SCL/U10[17]/J18[6] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_G2_T1_PERIPHERAL                                 ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_G2_T1_SIGNAL                                       IN   /*!< Signal name */
#define BOARD_INITPINS_ADC_G2_T1_CHANNEL                                     14U   /*!< Signal channel */

/* GPIO_AD_B1_15 (number 74), I2C1_SDA/U10[18]/J18[5] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_G2_T2_PERIPHERAL                                 ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_G2_T2_SIGNAL                                       IN   /*!< Signal name */
#define BOARD_INITPINS_ADC_G2_T2_CHANNEL                                     15U   /*!< Signal channel */

/* GPIO_EMC_27 (number 129), K1 */
/* Routed pin properties */
#define BOARD_INITPINS_K1_PERIPHERAL                                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_K1_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K1_CHANNEL                                            27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K1_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K1_GPIO_PIN                                           27U   /*!< GPIO pin number */
#define BOARD_INITPINS_K1_GPIO_PIN_MASK                              (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K1_PORT                                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K1_PIN                                                27U   /*!< PORT pin number */
#define BOARD_INITPINS_K1_PIN_MASK                                   (1U << 27U)   /*!< PORT pin mask */

/* GPIO_EMC_26 (number 130), K2 */
/* Routed pin properties */
#define BOARD_INITPINS_K2_PERIPHERAL                                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_K2_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K2_CHANNEL                                            26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K2_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K2_GPIO_PIN                                           26U   /*!< GPIO pin number */
#define BOARD_INITPINS_K2_GPIO_PIN_MASK                              (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K2_PORT                                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K2_PIN                                                26U   /*!< PORT pin number */
#define BOARD_INITPINS_K2_PIN_MASK                                   (1U << 26U)   /*!< PORT pin mask */

/* GPIO_EMC_25 (number 131), K3 */
/* Routed pin properties */
#define BOARD_INITPINS_K3_PERIPHERAL                                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_K3_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K3_CHANNEL                                            25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K3_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K3_GPIO_PIN                                           25U   /*!< GPIO pin number */
#define BOARD_INITPINS_K3_GPIO_PIN_MASK                              (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K3_PORT                                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K3_PIN                                                25U   /*!< PORT pin number */
#define BOARD_INITPINS_K3_PIN_MASK                                   (1U << 25U)   /*!< PORT pin mask */

/* GPIO_EMC_24 (number 132), K4 */
/* Routed pin properties */
#define BOARD_INITPINS_K4_PERIPHERAL                                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_K4_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K4_CHANNEL                                            24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K4_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K4_GPIO_PIN                                           24U   /*!< GPIO pin number */
#define BOARD_INITPINS_K4_GPIO_PIN_MASK                              (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K4_PORT                                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K4_PIN                                                24U   /*!< PORT pin number */
#define BOARD_INITPINS_K4_PIN_MASK                                   (1U << 24U)   /*!< PORT pin mask */

/* GPIO_EMC_21 (number 137), K5 */
/* Routed pin properties */
#define BOARD_INITPINS_K5_PERIPHERAL                                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_K5_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K5_CHANNEL                                            21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K5_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K5_GPIO_PIN                                           21U   /*!< GPIO pin number */
#define BOARD_INITPINS_K5_GPIO_PIN_MASK                              (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K5_PORT                                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K5_PIN                                                21U   /*!< PORT pin number */
#define BOARD_INITPINS_K5_PIN_MASK                                   (1U << 21U)   /*!< PORT pin mask */

/* GPIO_EMC_20 (number 138), K6 */
/* Routed pin properties */
#define BOARD_INITPINS_K6_PERIPHERAL                                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_K6_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K6_CHANNEL                                            20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K6_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K6_GPIO_PIN                                           20U   /*!< GPIO pin number */
#define BOARD_INITPINS_K6_GPIO_PIN_MASK                              (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K6_PORT                                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K6_PIN                                                20U   /*!< PORT pin number */
#define BOARD_INITPINS_K6_PIN_MASK                                   (1U << 20U)   /*!< PORT pin mask */

/* GPIO_EMC_17 (number 141), K7 */
/* Routed pin properties */
#define BOARD_INITPINS_K7_PERIPHERAL                                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_K7_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K7_CHANNEL                                            17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K7_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K7_GPIO_PIN                                           17U   /*!< GPIO pin number */
#define BOARD_INITPINS_K7_GPIO_PIN_MASK                              (1U << 17U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K7_PORT                                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K7_PIN                                                17U   /*!< PORT pin number */
#define BOARD_INITPINS_K7_PIN_MASK                                   (1U << 17U)   /*!< PORT pin mask */

/* GPIO_EMC_16 (number 142), K8 */
/* Routed pin properties */
#define BOARD_INITPINS_K8_PERIPHERAL                                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_K8_SIGNAL                                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_K8_CHANNEL                                            16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K8_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K8_GPIO_PIN                                           16U   /*!< GPIO pin number */
#define BOARD_INITPINS_K8_GPIO_PIN_MASK                              (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_K8_PORT                                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_K8_PIN                                                16U   /*!< PORT pin number */
#define BOARD_INITPINS_K8_PIN_MASK                                   (1U << 16U)   /*!< PORT pin mask */

/* GPIO_AD_B1_00 (number 92), DI_FU1_FB */
/* Routed pin properties */
#define BOARD_INITPINS_DI_FU1_FB_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_DI_FU1_FB_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_FU1_FB_CHANNEL                                     16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_FU1_FB_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_FU1_FB_GPIO_PIN                                    16U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_FU1_FB_GPIO_PIN_MASK                       (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_FU1_FB_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_FU1_FB_PIN                                         16U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_FU1_FB_PIN_MASK                            (1U << 16U)   /*!< PORT pin mask */

/* GPIO_AD_B1_01 (number 91), DI_FU2_FB */
/* Routed pin properties */
#define BOARD_INITPINS_DI_FU2_FB_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_DI_FU2_FB_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_FU2_FB_CHANNEL                                     17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_FU2_FB_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_FU2_FB_GPIO_PIN                                    17U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_FU2_FB_GPIO_PIN_MASK                       (1U << 17U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_FU2_FB_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_FU2_FB_PIN                                         17U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_FU2_FB_PIN_MASK                            (1U << 17U)   /*!< PORT pin mask */

/* GPIO_AD_B1_02 (number 90), DI_K1_FB */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K1_FB_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K1_FB_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K1_FB_CHANNEL                                      18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K1_FB_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K1_FB_GPIO_PIN                                     18U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K1_FB_GPIO_PIN_MASK                        (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K1_FB_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K1_FB_PIN                                          18U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K1_FB_PIN_MASK                             (1U << 18U)   /*!< PORT pin mask */

/* GPIO_AD_B1_03 (number 89), DI_K2_FB */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K2_FB_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K2_FB_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K2_FB_CHANNEL                                      19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K2_FB_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K2_FB_GPIO_PIN                                     19U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K2_FB_GPIO_PIN_MASK                        (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K2_FB_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K2_FB_PIN                                          19U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K2_FB_PIN_MASK                             (1U << 19U)   /*!< PORT pin mask */

/* GPIO_AD_B1_04 (number 88), DI_K3_FB */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K3_FB_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K3_FB_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K3_FB_CHANNEL                                      20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K3_FB_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K3_FB_GPIO_PIN                                     20U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K3_FB_GPIO_PIN_MASK                        (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K3_FB_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K3_FB_PIN                                          20U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K3_FB_PIN_MASK                             (1U << 20U)   /*!< PORT pin mask */

/* GPIO_AD_B1_05 (number 87), DI_K4_FB */
/* Routed pin properties */
#define BOARD_INITPINS_DI_K4_FB_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_DI_K4_FB_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_K4_FB_CHANNEL                                      21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_K4_FB_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_K4_FB_GPIO_PIN                                     21U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_K4_FB_GPIO_PIN_MASK                        (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_K4_FB_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_K4_FB_PIN                                          21U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_K4_FB_PIN_MASK                             (1U << 21U)   /*!< PORT pin mask */

/* GPIO_SD_B0_02 (number 46), DI_GUN1_FB */
/* Routed pin properties */
#define BOARD_INITPINS_DI_GUN1_FB_PERIPHERAL                               GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_DI_GUN1_FB_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_GUN1_FB_CHANNEL                                    15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_GUN1_FB_GPIO                                     GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_GUN1_FB_GPIO_PIN                                   15U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_GUN1_FB_GPIO_PIN_MASK                      (1U << 15U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_GUN1_FB_PORT                                     GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_GUN1_FB_PIN                                        15U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_GUN1_FB_PIN_MASK                           (1U << 15U)   /*!< PORT pin mask */

/* GPIO_SD_B0_03 (number 45), DI_GUN2_FB */
/* Routed pin properties */
#define BOARD_INITPINS_DI_GUN2_FB_PERIPHERAL                               GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_DI_GUN2_FB_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_GUN2_FB_CHANNEL                                    16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_GUN2_FB_GPIO                                     GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_GUN2_FB_GPIO_PIN                                   16U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_GUN2_FB_GPIO_PIN_MASK                      (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_GUN2_FB_PORT                                     GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_GUN2_FB_PIN                                        16U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_GUN2_FB_PIN_MASK                           (1U << 16U)   /*!< PORT pin mask */

/* GPIO_AD_B1_07 (number 83), DI_MCB */
/* Routed pin properties */
#define BOARD_INITPINS_DI_MCB_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_DI_MCB_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_MCB_CHANNEL                                        23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_MCB_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_MCB_GPIO_PIN                                       23U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_MCB_GPIO_PIN_MASK                          (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_MCB_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_MCB_PIN                                            23U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_MCB_PIN_MASK                               (1U << 23U)   /*!< PORT pin mask */

/* GPIO_EMC_37 (number 119), DI_Door */
/* Routed pin properties */
#define BOARD_INITPINS_DI_Door_PERIPHERAL                                  GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_DI_Door_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_Door_CHANNEL                                        5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_Door_GPIO                                        GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_Door_GPIO_PIN                                       5U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_Door_GPIO_PIN_MASK                          (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_Door_PORT                                        GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_Door_PIN                                            5U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_Door_PIN_MASK                               (1U << 5U)   /*!< PORT pin mask */

/* GPIO_EMC_36 (number 120), DI_Water */
/* Routed pin properties */
#define BOARD_INITPINS_DI_Water_PERIPHERAL                                 GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_DI_Water_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_Water_CHANNEL                                       4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_Water_GPIO                                       GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_Water_GPIO_PIN                                      4U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_Water_GPIO_PIN_MASK                         (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_Water_PORT                                       GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_Water_PIN                                           4U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_Water_PIN_MASK                              (1U << 4U)   /*!< PORT pin mask */

/* GPIO_EMC_35 (number 121), DI_Hit */
/* Routed pin properties */
#define BOARD_INITPINS_DI_Hit_PERIPHERAL                                   GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_DI_Hit_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_Hit_CHANNEL                                         3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_Hit_GPIO                                         GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_Hit_GPIO_PIN                                        3U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_Hit_GPIO_PIN_MASK                           (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_Hit_PORT                                         GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_Hit_PIN                                             3U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_Hit_PIN_MASK                                (1U << 3U)   /*!< PORT pin mask */

/* GPIO_EMC_34 (number 122), SEMC_D10/U14[45] */
/* Routed pin properties */
#define BOARD_INITPINS_WDI_PFO_PERIPHERAL                                  GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_WDI_PFO_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_WDI_PFO_CHANNEL                                        2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_WDI_PFO_GPIO                                        GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_WDI_PFO_GPIO_PIN                                       2U   /*!< GPIO pin number */
#define BOARD_INITPINS_WDI_PFO_GPIO_PIN_MASK                          (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_WDI_PFO_PORT                                        GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_WDI_PFO_PIN                                            2U   /*!< PORT pin number */
#define BOARD_INITPINS_WDI_PFO_PIN_MASK                               (1U << 2U)   /*!< PORT pin mask */

/* GPIO_EMC_00 (number 18), DI_Scram */
/* Routed pin properties */
#define BOARD_INITPINS_DI_Scram_PERIPHERAL                                 GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_Scram_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_Scram_CHANNEL                                       0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_Scram_GPIO                                       GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_Scram_GPIO_PIN                                      0U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_Scram_GPIO_PIN_MASK                         (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_Scram_PORT                                       GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_Scram_PIN                                           0U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_Scram_PIN_MASK                              (1U << 0U)   /*!< PORT pin mask */

/* GPIO_EMC_01 (number 17), DI_SPD */
/* Routed pin properties */
#define BOARD_INITPINS_DI_SPD_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_DI_SPD_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_SPD_CHANNEL                                         1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_SPD_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_SPD_GPIO_PIN                                        1U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_SPD_GPIO_PIN_MASK                           (1U << 1U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DI_SPD_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DI_SPD_PIN                                             1U   /*!< PORT pin number */
#define BOARD_INITPINS_DI_SPD_PIN_MASK                                (1U << 1U)   /*!< PORT pin mask */

/* GPIO_AD_B0_03 (number 108), JTAG_TDI/J16[5]/WDOG_B */
/* Routed pin properties */
#define BOARD_INITPINS_WDOG_B_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_WDOG_B_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_WDOG_B_CHANNEL                                         3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_WDOG_B_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_WDOG_B_GPIO_PIN                                        3U   /*!< GPIO pin number */
#define BOARD_INITPINS_WDOG_B_GPIO_PIN_MASK                           (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_WDOG_B_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_WDOG_B_PIN                                             3U   /*!< PORT pin number */
#define BOARD_INITPINS_WDOG_B_PIN_MASK                                (1U << 3U)   /*!< PORT pin mask */

/* GPIO_EMC_04 (number 14), LED_OUT1 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_OUT1_PERIPHERAL                                  TMR1   /*!< Peripheral name */
#define BOARD_INITPINS_LED_OUT1_SIGNAL                              TIMER_OUTPUT   /*!< Signal name */
#define BOARD_INITPINS_LED_OUT1_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_05 (number 13), LED_OUT2 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_OUT2_PERIPHERAL                                  TMR1   /*!< Peripheral name */
#define BOARD_INITPINS_LED_OUT2_SIGNAL                              TIMER_OUTPUT   /*!< Signal name */
#define BOARD_INITPINS_LED_OUT2_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_10 (number 7), LED_OUT3 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_OUT3_PERIPHERAL                                  TMR1   /*!< Peripheral name */
#define BOARD_INITPINS_LED_OUT3_SIGNAL                              TIMER_OUTPUT   /*!< Signal name */
#define BOARD_INITPINS_LED_OUT3_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_11 (number 4), LED_OUT4 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_OUT4_PERIPHERAL                                  TMR1   /*!< Peripheral name */
#define BOARD_INITPINS_LED_OUT4_SIGNAL                              TIMER_OUTPUT   /*!< Signal name */
#define BOARD_INITPINS_LED_OUT4_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_EMC_18 (number 140), LED_OUT5 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_OUT5_PERIPHERAL                                  TMR2   /*!< Peripheral name */
#define BOARD_INITPINS_LED_OUT5_SIGNAL                              TIMER_OUTPUT   /*!< Signal name */
#define BOARD_INITPINS_LED_OUT5_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_19 (number 139), LED_OUT6 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_OUT6_PERIPHERAL                                  TMR2   /*!< Peripheral name */
#define BOARD_INITPINS_LED_OUT6_SIGNAL                              TIMER_OUTPUT   /*!< Signal name */
#define BOARD_INITPINS_LED_OUT6_CHANNEL                                       1U   /*!< Signal channel */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
