/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MIMXRT1021xxxxx
package_id: MIMXRT1021DAG5A
mcu_data: ksdk2_0
processor_version: 24.12.10
board: MIMXRT1020-EVK
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 8d0b2cc6-2af8-4c3e-8e51-760ce0081e33
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * MPU initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MPU'
- type: 'mpu_utility'
- mode: 'MPU'
- custom_name_enabled: 'false'
- type_id: 'mpu_utility'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'MPU'
- config_sets:
  - mpu_init:
    - mpuInit: 'disabled'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void MPU_init(void) {
} */

/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'edma_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableMinorLoopMapping: 'false'
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'true'
      - ERCA: 'fixedPriority'
      - enableDebugMode: 'false'
    - dma_table:
      - 0: []
      - 1: []
    - edma_channels: []
    - errInterruptConfig:
      - enableErrInterrupt: 'false'
      - errorInterrupt:
        - IRQn: 'DMA_ERROR_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t DMA0_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = true,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = false
};

static void DMA0_init(void) {
  /* DMA0 minor loop mapping */
  EDMA_EnableMinorLoopMapping(DMA0_DMA_BASEADDR, false);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * PDU_CAN initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PDU_CAN'
- type: 'flexcan'
- mode: 'interrupts'
- custom_name_enabled: 'true'
- type_id: 'flexcan_2.10.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CAN1'
- config_sets:
  - interruptsCfg:
    - messageBufferIrqs: '0xffffffff'
    - messageBufferIrqs2: '0x0000ffff'
    - interruptsEnable: 'kFLEXCAN_BusOffInterruptEnable kFLEXCAN_ErrorInterruptEnable'
    - enable_irq: 'true'
    - interrupt_shared:
      - IRQn: 'CAN1_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'true'
      - priority: '5'
      - enable_custom_name: 'true'
      - handler_custom_name: 'CAN1_IRQhandler'
  - fsl_flexcan:
    - can_config:
      - clockSource: 'kFLEXCAN_ClkSrcOsc'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - wakeupSrc: 'kFLEXCAN_WakeupSrcUnfiltered'
      - baudRate: '250000'
      - maxMbNum: '32'
      - enableLoopBack: 'false'
      - enableTimerSync: 'true'
      - enableSelfWakeup: 'false'
      - enableIndividMask: 'true'
      - disableSelfReception: 'true'
      - enableListenOnlyMode: 'false'
      - enableSupervisorMode: 'true'
      - timingConfig:
        - propSeg: '6'
        - phaseSeg1: '7'
        - phaseSeg2: '2'
        - rJumpwidth: '2'
        - bitTime: []
    - enableRxFIFO: 'false'
    - rxFIFO:
      - idFilterTable: ''
      - idFilterNum: 'num0'
      - idFilterType: 'kFLEXCAN_RxFifoFilterTypeA'
      - priority: 'kFLEXCAN_RxFifoPrioLow'
    - channels:
      - 0:
        - mbID: '0'
        - mbType: 'mbInactive'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 1:
        - mbID: '1'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 2:
        - mbID: '2'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 3:
        - mbID: '3'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 4:
        - mbID: '4'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 5:
        - mbID: '5'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 6:
        - mbID: '6'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 7:
        - mbID: '7'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 8:
        - mbID: '8'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 9:
        - mbID: '9'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 10:
        - mbID: '10'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 11:
        - mbID: '11'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 12:
        - mbID: '12'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 13:
        - mbID: '13'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 14:
        - mbID: '14'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 15:
        - mbID: '15'
        - mbType: 'mbTx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatStandard'
          - type: 'kFLEXCAN_FrameTypeData'
      - 16:
        - mbID: '16'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 17:
        - mbID: '17'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 18:
        - mbID: '18'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 19:
        - mbID: '19'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 20:
        - mbID: '20'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 21:
        - mbID: '21'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 22:
        - mbID: '22'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 23:
        - mbID: '23'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 24:
        - mbID: '24'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 25:
        - mbID: '25'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 26:
        - mbID: '26'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 27:
        - mbID: '27'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 28:
        - mbID: '28'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 29:
        - mbID: '29'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 30:
        - mbID: '30'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
      - 31:
        - mbID: '31'
        - mbType: 'mbRx'
        - rxMb:
          - id: '0'
          - format: 'kFLEXCAN_FrameFormatExtend'
          - type: 'kFLEXCAN_FrameTypeData'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const flexcan_config_t PDU_CAN_config = {
  .wakeupSrc = kFLEXCAN_WakeupSrcUnfiltered,
  .bitRate = 250000UL,
  .maxMbNum = 32U,
  .enableLoopBack = false,
  .enableTimerSync = true,
  .enableSelfWakeup = false,
  .enableIndividMask = true,
  .disableSelfReception = true,
  .enableListenOnlyMode = false,
  .enableSupervisorMode = true,
  .timingConfig = {
    .preDivider = 14,
    .propSeg = 5,
    .phaseSeg1 = 6,
    .phaseSeg2 = 1,
    .rJumpwidth = 1
  }
};
/* Message buffer 16 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_16 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 17 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_17 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 18 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_18 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 19 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_19 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 20 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_20 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 21 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_21 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 22 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_22 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 23 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_23 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 24 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_24 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 25 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_25 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 26 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_26 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 27 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_27 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 28 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_28 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 29 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_29 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 30 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_30 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};
/* Message buffer 31 configuration structure */
const flexcan_rx_mb_config_t PDU_CAN_rx_mb_config_31 = {
  .id = FLEXCAN_ID_EXT(0UL),
  .format = kFLEXCAN_FrameFormatExtend,
  .type = kFLEXCAN_FrameTypeData
};

static void PDU_CAN_init(void) {
  FLEXCAN_Init(PDU_CAN_PERIPHERAL, &PDU_CAN_config, PDU_CAN_CLOCK_SOURCE);
  /* Message buffer 1 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 1, true);
  /* Message buffer 2 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 2, true);
  /* Message buffer 3 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 3, true);
  /* Message buffer 4 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 4, true);
  /* Message buffer 5 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 5, true);
  /* Message buffer 6 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 6, true);
  /* Message buffer 7 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 7, true);
  /* Message buffer 8 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 8, true);
  /* Message buffer 9 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 9, true);
  /* Message buffer 10 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 10, true);
  /* Message buffer 11 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 11, true);
  /* Message buffer 12 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 12, true);
  /* Message buffer 13 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 13, true);
  /* Message buffer 14 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 14, true);
  /* Message buffer 15 initialization */
  FLEXCAN_SetTxMbConfig(PDU_CAN_PERIPHERAL, 15, true);
  /* Message buffer 16 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 16, &PDU_CAN_rx_mb_config_16, true);
  /* Message buffer 17 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 17, &PDU_CAN_rx_mb_config_17, true);
  /* Message buffer 18 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 18, &PDU_CAN_rx_mb_config_18, true);
  /* Message buffer 19 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 19, &PDU_CAN_rx_mb_config_19, true);
  /* Message buffer 20 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 20, &PDU_CAN_rx_mb_config_20, true);
  /* Message buffer 21 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 21, &PDU_CAN_rx_mb_config_21, true);
  /* Message buffer 22 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 22, &PDU_CAN_rx_mb_config_22, true);
  /* Message buffer 23 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 23, &PDU_CAN_rx_mb_config_23, true);
  /* Message buffer 24 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 24, &PDU_CAN_rx_mb_config_24, true);
  /* Message buffer 25 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 25, &PDU_CAN_rx_mb_config_25, true);
  /* Message buffer 26 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 26, &PDU_CAN_rx_mb_config_26, true);
  /* Message buffer 27 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 27, &PDU_CAN_rx_mb_config_27, true);
  /* Message buffer 28 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 28, &PDU_CAN_rx_mb_config_28, true);
  /* Message buffer 29 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 29, &PDU_CAN_rx_mb_config_29, true);
  /* Message buffer 30 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 30, &PDU_CAN_rx_mb_config_30, true);
  /* Message buffer 31 initialization */
  FLEXCAN_SetRxMbConfig(PDU_CAN_PERIPHERAL, 31, &PDU_CAN_rx_mb_config_31, true);
  /* Enable FlexCAN interrupts */
  FLEXCAN_EnableInterrupts(PDU_CAN_PERIPHERAL, kFLEXCAN_BusOffInterruptEnable | kFLEXCAN_ErrorInterruptEnable);
  /* Enable FlexCAN interrupts of message buffers */
  FLEXCAN_EnableMbInterrupts(PDU_CAN_PERIPHERAL, (0xFFFFULL << 32) | 0xFFFFFFFFULL);
  /* Interrupt vector CAN1_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(PDU_CAN_FLEXCAN_IRQN, PDU_CAN_FLEXCAN_IRQ_PRIORITY);
  /* Interrupt PDU_CAN_FLEXCAN_IRQN request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(PDU_CAN_FLEXCAN_IRQN); function call. */
}

/***********************************************************************************************************************
 * LPUART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART1'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.8.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART1'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '9600'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1726657927547'
        - eDMAn: '1'
        - eDMA_source: 'kDmaRequestMuxLPUART1Rx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'true'
          - enablePreemptAbility: 'false'
          - channelPriority: '4'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'true'
      - edma_tx_channel:
        - uid: '1726657927548'
        - eDMAn: '0'
        - eDMA_source: 'kDmaRequestMuxLPUART1Tx'
        - enableTriggerPIT: 'false'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'true'
          - enablePreemptAbility: 'false'
          - channelPriority: '3'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'LPUART_DmaCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART1_config = {
  .baudRate_Bps = 9600UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
edma_handle_t LPUART1_RX_Handle;
edma_handle_t LPUART1_TX_Handle;
lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;

static void LPUART1_init(void) {
  LPUART_Init(LPUART1_PERIPHERAL, &LPUART1_config, LPUART1_CLOCK_SOURCE);
  /* Set the source kDmaRequestMuxLPUART1Rx request in the DMAMUX */
  DMAMUX_SetSource(LPUART1_RX_DMAMUX_BASEADDR, LPUART1_RX_DMA_CHANNEL, LPUART1_RX_DMA_REQUEST);
  /* Enable the channel 1 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART1_RX_DMAMUX_BASEADDR, LPUART1_RX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxLPUART1Tx request in the DMAMUX */
  DMAMUX_SetSource(LPUART1_TX_DMAMUX_BASEADDR, LPUART1_TX_DMA_CHANNEL, LPUART1_TX_DMA_REQUEST);
  /* Enable the channel 0 in the DMAMUX */
  DMAMUX_EnableChannel(LPUART1_TX_DMAMUX_BASEADDR, LPUART1_TX_DMA_CHANNEL);
  /* Create the eDMA LPUART1_RX_Handle handle */
  EDMA_CreateHandle(&LPUART1_RX_Handle, LPUART1_RX_DMA_BASEADDR, LPUART1_RX_DMA_CHANNEL);
  /* Create the eDMA LPUART1_TX_Handle handle */
  EDMA_CreateHandle(&LPUART1_TX_Handle, LPUART1_TX_DMA_BASEADDR, LPUART1_TX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART1_PERIPHERAL, &LPUART1_LPUART_eDMA_Handle, LPUART_DmaCallback, NULL, &LPUART1_TX_Handle, &LPUART1_RX_Handle);
}

/***********************************************************************************************************************
 * ADC1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC1'
- type: 'adc_12b1msps_sar'
- mode: 'ADC_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'adc_12b1msps_sar_2.0.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC1'
- config_sets:
  - fsl_adc:
    - clockConfig:
      - clockSource: 'kADC_ClockSourceAD'
      - clockSourceFreq: 'custom:10 MHz'
      - clockDriver: 'kADC_ClockDriver1'
      - samplePeriodMode: 'kADC_SamplePeriodShort8Clocks'
      - enableAsynchronousClockOutput: 'true'
    - conversionConfig:
      - resolution: 'kADC_Resolution12Bit'
      - hardwareAverageMode: 'kADC_HardwareAverageCount8'
      - enableHardwareTrigger: 'software'
      - enableHighSpeed: 'false'
      - enableLowPower: 'false'
      - enableContinuousConversion: 'false'
      - enableOverWrite: 'true'
      - enableDma: 'false'
    - resultingTime: []
    - resultCorrection:
      - doAutoCalibration: 'false'
      - offset: '0'
    - hardwareCompareConfiguration:
      - hardwareCompareMode: 'disabled'
      - value1: '0'
      - value2: '0'
    - enableInterrupt: 'false'
    - adc_interrupt:
      - IRQn: 'ADC1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_channels_config:
      - 0:
        - channelNumber: 'IN.0'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
      - 1:
        - channelNumber: 'IN.2'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC1_config = {
  .enableOverWrite = true,
  .enableContinuousConversion = false,
  .enableHighSpeed = false,
  .enableLowPower = false,
  .enableLongSample = false,
  .enableAsynchronousClockOutput = true,
  .referenceVoltageSource = kADC_ReferenceVoltageSourceAlt0,
  .samplePeriodMode = kADC_SamplePeriodShort8Clocks,
  .clockSource = kADC_ClockSourceAD,
  .clockDriver = kADC_ClockDriver1,
  .resolution = kADC_Resolution12Bit
};
const adc_channel_config_t ADC1_channels_config[2] = {
  {
    .channelNumber = 0U,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = 2U,
    .enableInterruptOnConversionCompleted = false
  }
};
static void ADC1_init(void) {
  /* Initialize ADC1 peripheral. */
  ADC_Init(ADC1_PERIPHERAL, &ADC1_config);
  /* Configure ADC1 peripheral to average 8 conversions in one measurement. */
  ADC_SetHardwareAverageConfig(ADC1_PERIPHERAL, kADC_HardwareAverageCount8);
}

/***********************************************************************************************************************
 * EEPROM_I2C initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'EEPROM_I2C'
- type: 'lpi2c'
- mode: 'master'
- custom_name_enabled: 'true'
- type_id: 'lpi2c_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C3'
- config_sets:
  - main:
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
  - interrupt_vector: []
  - master:
    - mode: 'freertos'
    - config:
      - enableMaster: 'false'
      - enableDoze: 'false'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '100000'
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - edmaRequestSources: 'enableRx enableTx'
    - transfer:
      - enable_custom_handle: 'false'
      - flags: ''
      - slaveAddress: '80'
      - direction: 'kLPI2C_Write'
      - subaddress: '0'
      - subaddressSize: '2'
      - blocking_buffer: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t EEPROM_I2C_masterConfig = {
  .enableMaster = false,
  .enableDoze = false,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 100000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
lpi2c_master_transfer_t EEPROM_I2C_masterTransfer = {
  .flags = kLPI2C_TransferDefaultFlag,
  .slaveAddress = 80,
  .direction = kLPI2C_Write,
  .subaddress = 0,
  .subaddressSize = 2,
  .data = NULL,
  .dataSize = 0
};
lpi2c_rtos_handle_t EEPROM_I2C_masterHandle;

static void EEPROM_I2C_init(void) {
  LPI2C_RTOS_Init(&EEPROM_I2C_masterHandle, EEPROM_I2C_PERIPHERAL, &EEPROM_I2C_masterConfig, EEPROM_I2C_CLOCK_FREQ);
  /* Enable Leader eDMA request sources: Tx, Rx */
  LPI2C_MasterEnableDMA(EEPROM_I2C_PERIPHERAL, true, true);
}

/***********************************************************************************************************************
 * ADC2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC2'
- type: 'adc_12b1msps_sar'
- mode: 'ADC_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'adc_12b1msps_sar_2.0.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC2'
- config_sets:
  - fsl_adc:
    - clockConfig:
      - clockSource: 'kADC_ClockSourceAD'
      - clockSourceFreq: 'custom:10 MHz'
      - clockDriver: 'kADC_ClockDriver1'
      - samplePeriodMode: 'kADC_SamplePeriodShort8Clocks'
      - enableAsynchronousClockOutput: 'true'
    - conversionConfig:
      - resolution: 'kADC_Resolution12Bit'
      - hardwareAverageMode: 'kADC_HardwareAverageCount8'
      - enableHardwareTrigger: 'software'
      - enableHighSpeed: 'false'
      - enableLowPower: 'false'
      - enableContinuousConversion: 'false'
      - enableOverWrite: 'true'
      - enableDma: 'false'
    - resultingTime: []
    - resultCorrection:
      - doAutoCalibration: 'false'
      - offset: '0'
    - hardwareCompareConfiguration:
      - hardwareCompareMode: 'disabled'
      - value1: '0'
      - value2: '0'
    - enableInterrupt: 'false'
    - adc_interrupt:
      - IRQn: 'ADC2_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_channels_config:
      - 0:
        - channelNumber: 'IN.0'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
      - 1:
        - channelNumber: 'IN.1'
        - channelName: ''
        - channelGroup: '0'
        - initializeChannel: 'false'
        - enableInterruptOnConversionCompleted: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC2_config = {
  .enableOverWrite = true,
  .enableContinuousConversion = false,
  .enableHighSpeed = false,
  .enableLowPower = false,
  .enableLongSample = false,
  .enableAsynchronousClockOutput = true,
  .referenceVoltageSource = kADC_ReferenceVoltageSourceAlt0,
  .samplePeriodMode = kADC_SamplePeriodShort8Clocks,
  .clockSource = kADC_ClockSourceAD,
  .clockDriver = kADC_ClockDriver1,
  .resolution = kADC_Resolution12Bit
};
const adc_channel_config_t ADC2_channels_config[2] = {
  {
    .channelNumber = 0U,
    .enableInterruptOnConversionCompleted = false
  },
  {
    .channelNumber = 1U,
    .enableInterruptOnConversionCompleted = false
  }
};
static void ADC2_init(void) {
  /* Initialize ADC2 peripheral. */
  ADC_Init(ADC2_PERIPHERAL, &ADC2_config);
  /* Configure ADC2 peripheral to average 8 conversions in one measurement. */
  ADC_SetHardwareAverageConfig(ADC2_PERIPHERAL, kADC_HardwareAverageCount8);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  ARM_MPU_Disable();
  DMAMUX_Init(DMA0_DMAMUX_BASEADDR);
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);

  /* Initialize components */
  DMA0_init();
  PDU_CAN_init();
  LPUART1_init();
  ADC1_init();
  EEPROM_I2C_init();
  ADC2_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
