/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MIMXRT1021xxxxx
package_id: MIMXRT1021DAG5A
mcu_data: ksdk2_0
processor_version: 24.12.10
board: MIMXRT1020-EVK
pin_labels:
- {pin_num: '14', pin_signal: GPIO_EMC_04, label: DI_K5, identifier: DI_K5}
- {pin_num: '18', pin_signal: GPIO_EMC_00, label: DI_K1, identifier: DI_K1}
- {pin_num: '17', pin_signal: GPIO_EMC_01, label: DI_K2, identifier: DI_K2}
- {pin_num: '16', pin_signal: GPIO_EMC_02, label: DI_K3, identifier: DI_K3}
- {pin_num: '15', pin_signal: GPIO_EMC_03, label: DI_K4, identifier: DI_K4}
- {pin_num: '13', pin_signal: GPIO_EMC_05, label: DI_K6, identifier: DI_K6}
- {pin_num: '12', pin_signal: GPIO_EMC_06, label: DI_K7, identifier: DI_K7}
- {pin_num: '10', pin_signal: GPIO_EMC_07, label: DI_K8, identifier: DI_K8}
- {pin_num: '9', pin_signal: GPIO_EMC_08, label: DI_K9, identifier: DI_K9}
- {pin_num: '8', pin_signal: GPIO_EMC_09, label: DI_K10, identifier: DI_K10}
- {pin_num: '7', pin_signal: GPIO_EMC_10, label: DI_K11, identifier: DI_K11}
- {pin_num: '4', pin_signal: GPIO_EMC_11, label: DI_K12, identifier: DI_K12}
- {pin_num: '3', pin_signal: GPIO_EMC_12, label: DI_K13, identifier: DI_K13}
- {pin_num: '2', pin_signal: GPIO_EMC_13, label: DI_K14, identifier: DI_K14}
- {pin_num: '1', pin_signal: GPIO_EMC_14, label: DI_K15, identifier: DI_K15}
- {pin_num: '143', pin_signal: GPIO_EMC_15, label: DI_K16, identifier: DI_K16}
- {pin_num: '142', pin_signal: GPIO_EMC_16, label: K8, identifier: SEMC_A0;K8}
- {pin_num: '141', pin_signal: GPIO_EMC_17, label: K7, identifier: SEMC_A1;K7}
- {pin_num: '138', pin_signal: GPIO_EMC_20, label: B6, identifier: B6}
- {pin_num: '137', pin_signal: GPIO_EMC_21, label: B5, identifier: B5}
- {pin_num: '136', pin_signal: GPIO_EMC_22, label: 'SEMC_A6/U14[31]/BT_CFG[4]', identifier: UART2_TX}
- {pin_num: '133', pin_signal: GPIO_EMC_23, label: 'SEMC_A7/U14[32]/BT_CFG[5]', identifier: UART2_RX}
- {pin_num: '132', pin_signal: GPIO_EMC_24, label: B4, identifier: B4}
- {pin_num: '131', pin_signal: GPIO_EMC_25, label: B3, identifier: B3}
- {pin_num: '130', pin_signal: GPIO_EMC_26, label: B2, identifier: B2}
- {pin_num: '129', pin_signal: GPIO_EMC_27, label: B1, identifier: B1}
- {pin_num: '128', pin_signal: GPIO_EMC_28, label: IO_ADD1, identifier: IO_ADD1}
- {pin_num: '127', pin_signal: GPIO_EMC_29, label: IO_ADD2, identifier: SEMC_CKE;IO_ADD2}
- {pin_num: '126', pin_signal: GPIO_EMC_30, label: IO_ADD3, identifier: SEMC_CLK;IO_ADD3}
- {pin_num: '125', pin_signal: GPIO_EMC_31, label: IO_ADD4, identifier: SEMC_DM1;IO_ADD4}
- {pin_num: '124', pin_signal: GPIO_EMC_32, label: VER_SEL_1, identifier: VER_SEL_1}
- {pin_num: '123', pin_signal: GPIO_EMC_33, label: VER_SEL_2, identifier: VER_SEL_2}
- {pin_num: '122', pin_signal: GPIO_EMC_34, label: 'SEMC_D10/U14[45]', identifier: WDI_PFO}
- {pin_num: '121', pin_signal: GPIO_EMC_35, label: DI_Hit, identifier: SEMC_D11;DI_Hit}
- {pin_num: '120', pin_signal: GPIO_EMC_36, label: DI_Water, identifier: SEMC_D12;DI_Water}
- {pin_num: '119', pin_signal: GPIO_EMC_37, label: DI_Door, identifier: SEMC_D13;DI_Door}
- {pin_num: '118', pin_signal: GPIO_EMC_38, label: 'SEMC_D14/U14[51]', identifier: UART5_TX}
- {pin_num: '117', pin_signal: GPIO_EMC_39, label: 'SEMC_D15/U14[53]', identifier: UART5_RX}
- {pin_num: '109', pin_signal: GPIO_AD_B0_02, label: GND, identifier: RS485_EN1}
- {pin_num: '108', pin_signal: GPIO_AD_B0_03, label: 'JTAG_TDI/J16[5]/WDOG_B', identifier: WDOG_B}
- {pin_num: '107', pin_signal: GPIO_AD_B0_04, label: 'JTAG_TDO/J16[13]/ENET_RST/U11[32]', identifier: ENET_RST;PHY_RST}
- {pin_num: '106', pin_signal: GPIO_AD_B0_05, label: USER_LED, identifier: RUN_LED}
- {pin_num: '100', pin_signal: GPIO_AD_B0_08, label: 'ENET_TX_CLK/U11[9]', identifier: ENET_TX_CLK;LED3}
- {pin_num: '99', pin_signal: GPIO_AD_B0_09, label: 'ENET_RXD1/U11[15]/J17[3]', identifier: ENET_RXD1;LED2}
- {pin_num: '98', pin_signal: GPIO_AD_B0_10, label: 'ENET_RXD0/U11[16]/J19[6]', identifier: ENET_RXD0;LED1}
- {pin_num: '96', pin_signal: GPIO_AD_B0_12, label: DCN_TEMP, identifier: DCN_TEMP}
- {pin_num: '95', pin_signal: GPIO_AD_B0_13, label: DCP_TEMP, identifier: DCP_TEMP}
- {pin_num: '94', pin_signal: GPIO_AD_B0_14, label: PCB_TEM2, identifier: PCB_TEM2}
- {pin_num: '93', pin_signal: GPIO_AD_B0_15, label: PCB_TEM1, identifier: PCB_TEM1}
- {pin_num: '92', pin_signal: GPIO_AD_B1_00, label: K16, identifier: K16}
- {pin_num: '91', pin_signal: GPIO_AD_B1_01, label: K15, identifier: K15}
- {pin_num: '90', pin_signal: GPIO_AD_B1_02, label: K14, identifier: K14}
- {pin_num: '89', pin_signal: GPIO_AD_B1_03, label: K13, identifier: K13}
- {pin_num: '88', pin_signal: GPIO_AD_B1_04, label: K12, identifier: K12}
- {pin_num: '87', pin_signal: GPIO_AD_B1_05, label: K11, identifier: K11}
- {pin_num: '84', pin_signal: GPIO_AD_B1_06, label: K10, identifier: K10}
- {pin_num: '83', pin_signal: GPIO_AD_B1_07, label: K9, identifier: K9}
- {pin_num: '80', pin_signal: GPIO_AD_B1_10, label: K6, identifier: K6}
- {pin_num: '79', pin_signal: GPIO_AD_B1_11, label: K5, identifier: K5}
- {pin_num: '78', pin_signal: GPIO_AD_B1_12, label: K4, identifier: K4}
- {pin_num: '76', pin_signal: GPIO_AD_B1_13, label: K3, identifier: K3}
- {pin_num: '75', pin_signal: GPIO_AD_B1_14, label: K2, identifier: K2}
- {pin_num: '74', pin_signal: GPIO_AD_B1_15, label: K1, identifier: K1}
- {pin_num: '48', pin_signal: GPIO_SD_B0_00, label: 'SD1_D2/J15[1]', identifier: IIC3_SCL}
- {pin_num: '47', pin_signal: GPIO_SD_B0_01, label: 'SD1_D3/J15[2]', identifier: IIC3_SDA}
- {pin_num: '46', pin_signal: GPIO_SD_B0_02, label: DI_GUN1_FB, identifier: SD1_CMD;DI_GUN1_FB}
- {pin_num: '45', pin_signal: GPIO_SD_B0_03, label: DI_GUN2_FB, identifier: SD1_CLK;DI_GUN2_FB}
- {pin_num: '43', pin_signal: GPIO_SD_B0_04, label: 'SD1_D0/J15[7]', identifier: UART7_TX}
- {pin_num: '42', pin_signal: GPIO_SD_B0_05, label: 'SD1_D1/J15[8]', identifier: UART7_RX}
- {pin_num: '41', pin_signal: GPIO_SD_B0_06, label: RS485_EN3, identifier: RS485_EN2}
- {pin_num: '30', pin_signal: GPIO_SD_B1_02, label: I2C4_SCL, identifier: UART8_TX}
- {pin_num: '26', pin_signal: GPIO_SD_B1_05, label: RS485_EN2, identifier: RS485_EN3}
- {pin_num: '27', pin_signal: GPIO_SD_B1_04, label: RS485_EN4, identifier: RS485_EN4}
- {pin_num: '28', pin_signal: GPIO_SD_B1_03, label: I2C4_SDA, identifier: UART8_RX}
- {pin_num: '81', pin_signal: GPIO_AD_B1_09, label: K7, identifier: K7}
- {pin_num: '82', pin_signal: GPIO_AD_B1_08, label: K8, identifier: K8}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '105', peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_06, pull_keeper_enable: Disable}
  - {pin_num: '101', peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_07, pull_keeper_enable: Disable}
  - {pin_num: '48', peripheral: LPI2C3, signal: SCL, pin_signal: GPIO_SD_B0_00, software_input_on: Enable, open_drain: Enable, pull_keeper_select: Keeper, pull_keeper_enable: Enable,
    pull_up_down_config: Pull_Up_22K_Ohm}
  - {pin_num: '47', peripheral: LPI2C3, signal: SDA, pin_signal: GPIO_SD_B0_01, software_input_on: Enable, open_drain: Enable, pull_keeper_select: Keeper, pull_keeper_enable: Enable,
    pull_up_down_config: Pull_Up_22K_Ohm}
  - {pin_num: '32', peripheral: CAN1, signal: RX, pin_signal: GPIO_SD_B1_01, pull_keeper_enable: Disable}
  - {pin_num: '33', peripheral: CAN1, signal: TX, pin_signal: GPIO_SD_B1_00, pull_keeper_enable: Disable}
  - {pin_num: '109', peripheral: GPIO1, signal: 'gpio_io, 02', pin_signal: GPIO_AD_B0_02, direction: OUTPUT, drive_strength: R0_6, pull_keeper_select: Pull, pull_keeper_enable: Disable,
    pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '122', peripheral: GPIO3, signal: 'gpio_io, 02', pin_signal: GPIO_EMC_34, direction: INPUT, open_drain: Disable, pull_keeper_select: Pull, pull_up_down_config: Pull_Up_47K_Ohm}
  - {pin_num: '18', peripheral: GPIO2, signal: 'gpio_io, 00', pin_signal: GPIO_EMC_00, direction: INPUT}
  - {pin_num: '17', peripheral: GPIO2, signal: 'gpio_io, 01', pin_signal: GPIO_EMC_01, direction: INPUT}
  - {pin_num: '108', peripheral: GPIO1, signal: 'gpio_io, 03', pin_signal: GPIO_AD_B0_03, direction: OUTPUT, pull_keeper_select: Keeper}
  - {pin_num: '1', peripheral: GPIO2, signal: 'gpio_io, 14', pin_signal: GPIO_EMC_14, direction: INPUT}
  - {pin_num: '2', peripheral: GPIO2, signal: 'gpio_io, 13', pin_signal: GPIO_EMC_13, direction: INPUT}
  - {pin_num: '3', peripheral: GPIO2, signal: 'gpio_io, 12', pin_signal: GPIO_EMC_12, direction: INPUT}
  - {pin_num: '4', peripheral: GPIO2, signal: 'gpio_io, 11', pin_signal: GPIO_EMC_11, direction: INPUT}
  - {pin_num: '143', peripheral: GPIO2, signal: 'gpio_io, 15', pin_signal: GPIO_EMC_15, direction: INPUT}
  - {pin_num: '7', peripheral: GPIO2, signal: 'gpio_io, 10', pin_signal: GPIO_EMC_10, direction: INPUT}
  - {pin_num: '8', peripheral: GPIO2, signal: 'gpio_io, 09', pin_signal: GPIO_EMC_09, direction: INPUT}
  - {pin_num: '9', peripheral: GPIO2, signal: 'gpio_io, 08', pin_signal: GPIO_EMC_08, direction: INPUT}
  - {pin_num: '10', peripheral: GPIO2, signal: 'gpio_io, 07', pin_signal: GPIO_EMC_07, direction: INPUT}
  - {pin_num: '12', peripheral: GPIO2, signal: 'gpio_io, 06', pin_signal: GPIO_EMC_06, direction: INPUT}
  - {pin_num: '13', peripheral: GPIO2, signal: 'gpio_io, 05', pin_signal: GPIO_EMC_05, direction: INPUT}
  - {pin_num: '14', peripheral: GPIO2, signal: 'gpio_io, 04', pin_signal: GPIO_EMC_04, direction: INPUT}
  - {pin_num: '15', peripheral: GPIO2, signal: 'gpio_io, 03', pin_signal: GPIO_EMC_03, direction: INPUT}
  - {pin_num: '16', peripheral: GPIO2, signal: 'gpio_io, 02', pin_signal: GPIO_EMC_02, direction: INPUT}
  - {pin_num: '123', peripheral: GPIO3, signal: 'gpio_io, 01', pin_signal: GPIO_EMC_33, direction: INPUT}
  - {pin_num: '124', peripheral: GPIO3, signal: 'gpio_io, 00', pin_signal: GPIO_EMC_32, direction: INPUT}
  - {pin_num: '125', peripheral: GPIO2, signal: 'gpio_io, 31', pin_signal: GPIO_EMC_31, identifier: IO_ADD4, direction: INPUT}
  - {pin_num: '126', peripheral: GPIO2, signal: 'gpio_io, 30', pin_signal: GPIO_EMC_30, identifier: IO_ADD3, direction: INPUT}
  - {pin_num: '127', peripheral: GPIO2, signal: 'gpio_io, 29', pin_signal: GPIO_EMC_29, identifier: IO_ADD2, direction: INPUT}
  - {pin_num: '128', peripheral: GPIO2, signal: 'gpio_io, 28', pin_signal: GPIO_EMC_28, direction: INPUT}
  - {pin_num: '93', peripheral: ADC1, signal: 'IN, 2', pin_signal: GPIO_AD_B0_15}
  - {pin_num: '95', peripheral: ADC2, signal: 'IN, 0', pin_signal: GPIO_AD_B0_13}
  - {pin_num: '96', peripheral: ADC1, signal: 'IN, 0', pin_signal: GPIO_AD_B0_12}
  - {pin_num: '74', peripheral: GPIO1, signal: 'gpio_io, 31', pin_signal: GPIO_AD_B1_15, direction: OUTPUT}
  - {pin_num: '75', peripheral: GPIO1, signal: 'gpio_io, 30', pin_signal: GPIO_AD_B1_14, direction: OUTPUT}
  - {pin_num: '76', peripheral: GPIO1, signal: 'gpio_io, 29', pin_signal: GPIO_AD_B1_13, direction: OUTPUT}
  - {pin_num: '78', peripheral: GPIO1, signal: 'gpio_io, 28', pin_signal: GPIO_AD_B1_12, direction: OUTPUT}
  - {pin_num: '79', peripheral: GPIO1, signal: 'gpio_io, 27', pin_signal: GPIO_AD_B1_11, direction: OUTPUT}
  - {pin_num: '80', peripheral: GPIO1, signal: 'gpio_io, 26', pin_signal: GPIO_AD_B1_10, direction: OUTPUT}
  - {pin_num: '81', peripheral: GPIO1, signal: 'gpio_io, 25', pin_signal: GPIO_AD_B1_09, direction: OUTPUT}
  - {pin_num: '82', peripheral: GPIO1, signal: 'gpio_io, 24', pin_signal: GPIO_AD_B1_08, direction: OUTPUT}
  - {pin_num: '83', peripheral: GPIO1, signal: 'gpio_io, 23', pin_signal: GPIO_AD_B1_07, direction: OUTPUT}
  - {pin_num: '87', peripheral: GPIO1, signal: 'gpio_io, 21', pin_signal: GPIO_AD_B1_05, direction: OUTPUT}
  - {pin_num: '88', peripheral: GPIO1, signal: 'gpio_io, 20', pin_signal: GPIO_AD_B1_04, direction: OUTPUT}
  - {pin_num: '89', peripheral: GPIO1, signal: 'gpio_io, 19', pin_signal: GPIO_AD_B1_03, direction: OUTPUT}
  - {pin_num: '90', peripheral: GPIO1, signal: 'gpio_io, 18', pin_signal: GPIO_AD_B1_02, direction: OUTPUT}
  - {pin_num: '91', peripheral: GPIO1, signal: 'gpio_io, 17', pin_signal: GPIO_AD_B1_01, direction: OUTPUT}
  - {pin_num: '92', peripheral: GPIO1, signal: 'gpio_io, 16', pin_signal: GPIO_AD_B1_00, direction: OUTPUT}
  - {pin_num: '84', peripheral: GPIO1, signal: 'gpio_io, 22', pin_signal: GPIO_AD_B1_06, direction: OUTPUT}
  - {pin_num: '106', peripheral: GPIO1, signal: 'gpio_io, 05', pin_signal: GPIO_AD_B0_05, direction: OUTPUT}
  - {pin_num: '94', peripheral: ADC2, signal: 'IN, 1', pin_signal: GPIO_AD_B0_14}
  - {pin_num: '98', peripheral: GPIO1, signal: 'gpio_io, 10', pin_signal: GPIO_AD_B0_10, identifier: LED1, direction: OUTPUT}
  - {pin_num: '99', peripheral: GPIO1, signal: 'gpio_io, 09', pin_signal: GPIO_AD_B0_09, identifier: LED2, direction: OUTPUT}
  - {pin_num: '100', peripheral: GPIO1, signal: 'gpio_io, 08', pin_signal: GPIO_AD_B0_08, identifier: LED3, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of RS485_EN1 on GPIO_AD_B0_02 (pin 109) */
  gpio_pin_config_t RS485_EN1_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_02 (pin 109) */
  GPIO_PinInit(GPIO1, 2U, &RS485_EN1_config);

  /* GPIO configuration of WDOG_B on GPIO_AD_B0_03 (pin 108) */
  gpio_pin_config_t WDOG_B_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_03 (pin 108) */
  GPIO_PinInit(GPIO1, 3U, &WDOG_B_config);

  /* GPIO configuration of RUN_LED on GPIO_AD_B0_05 (pin 106) */
  gpio_pin_config_t RUN_LED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_05 (pin 106) */
  GPIO_PinInit(GPIO1, 5U, &RUN_LED_config);

  /* GPIO configuration of LED3 on GPIO_AD_B0_08 (pin 100) */
  gpio_pin_config_t LED3_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_08 (pin 100) */
  GPIO_PinInit(GPIO1, 8U, &LED3_config);

  /* GPIO configuration of LED2 on GPIO_AD_B0_09 (pin 99) */
  gpio_pin_config_t LED2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_09 (pin 99) */
  GPIO_PinInit(GPIO1, 9U, &LED2_config);

  /* GPIO configuration of LED1 on GPIO_AD_B0_10 (pin 98) */
  gpio_pin_config_t LED1_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_10 (pin 98) */
  GPIO_PinInit(GPIO1, 10U, &LED1_config);

  /* GPIO configuration of K16 on GPIO_AD_B1_00 (pin 92) */
  gpio_pin_config_t K16_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_00 (pin 92) */
  GPIO_PinInit(GPIO1, 16U, &K16_config);

  /* GPIO configuration of K15 on GPIO_AD_B1_01 (pin 91) */
  gpio_pin_config_t K15_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_01 (pin 91) */
  GPIO_PinInit(GPIO1, 17U, &K15_config);

  /* GPIO configuration of K14 on GPIO_AD_B1_02 (pin 90) */
  gpio_pin_config_t K14_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_02 (pin 90) */
  GPIO_PinInit(GPIO1, 18U, &K14_config);

  /* GPIO configuration of K13 on GPIO_AD_B1_03 (pin 89) */
  gpio_pin_config_t K13_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_03 (pin 89) */
  GPIO_PinInit(GPIO1, 19U, &K13_config);

  /* GPIO configuration of K12 on GPIO_AD_B1_04 (pin 88) */
  gpio_pin_config_t K12_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_04 (pin 88) */
  GPIO_PinInit(GPIO1, 20U, &K12_config);

  /* GPIO configuration of K11 on GPIO_AD_B1_05 (pin 87) */
  gpio_pin_config_t K11_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_05 (pin 87) */
  GPIO_PinInit(GPIO1, 21U, &K11_config);

  /* GPIO configuration of K10 on GPIO_AD_B1_06 (pin 84) */
  gpio_pin_config_t K10_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_06 (pin 84) */
  GPIO_PinInit(GPIO1, 22U, &K10_config);

  /* GPIO configuration of K9 on GPIO_AD_B1_07 (pin 83) */
  gpio_pin_config_t K9_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_07 (pin 83) */
  GPIO_PinInit(GPIO1, 23U, &K9_config);

  /* GPIO configuration of K8 on GPIO_AD_B1_08 (pin 82) */
  gpio_pin_config_t K8_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_08 (pin 82) */
  GPIO_PinInit(GPIO1, 24U, &K8_config);

  /* GPIO configuration of K7 on GPIO_AD_B1_09 (pin 81) */
  gpio_pin_config_t K7_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_09 (pin 81) */
  GPIO_PinInit(GPIO1, 25U, &K7_config);

  /* GPIO configuration of K6 on GPIO_AD_B1_10 (pin 80) */
  gpio_pin_config_t K6_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_10 (pin 80) */
  GPIO_PinInit(GPIO1, 26U, &K6_config);

  /* GPIO configuration of K5 on GPIO_AD_B1_11 (pin 79) */
  gpio_pin_config_t K5_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_11 (pin 79) */
  GPIO_PinInit(GPIO1, 27U, &K5_config);

  /* GPIO configuration of K4 on GPIO_AD_B1_12 (pin 78) */
  gpio_pin_config_t K4_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_12 (pin 78) */
  GPIO_PinInit(GPIO1, 28U, &K4_config);

  /* GPIO configuration of K3 on GPIO_AD_B1_13 (pin 76) */
  gpio_pin_config_t K3_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_13 (pin 76) */
  GPIO_PinInit(GPIO1, 29U, &K3_config);

  /* GPIO configuration of K2 on GPIO_AD_B1_14 (pin 75) */
  gpio_pin_config_t K2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_14 (pin 75) */
  GPIO_PinInit(GPIO1, 30U, &K2_config);

  /* GPIO configuration of K1 on GPIO_AD_B1_15 (pin 74) */
  gpio_pin_config_t K1_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_15 (pin 74) */
  GPIO_PinInit(GPIO1, 31U, &K1_config);

  /* GPIO configuration of DI_K1 on GPIO_EMC_00 (pin 18) */
  gpio_pin_config_t DI_K1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_00 (pin 18) */
  GPIO_PinInit(GPIO2, 0U, &DI_K1_config);

  /* GPIO configuration of DI_K2 on GPIO_EMC_01 (pin 17) */
  gpio_pin_config_t DI_K2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_01 (pin 17) */
  GPIO_PinInit(GPIO2, 1U, &DI_K2_config);

  /* GPIO configuration of DI_K3 on GPIO_EMC_02 (pin 16) */
  gpio_pin_config_t DI_K3_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_02 (pin 16) */
  GPIO_PinInit(GPIO2, 2U, &DI_K3_config);

  /* GPIO configuration of DI_K4 on GPIO_EMC_03 (pin 15) */
  gpio_pin_config_t DI_K4_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_03 (pin 15) */
  GPIO_PinInit(GPIO2, 3U, &DI_K4_config);

  /* GPIO configuration of DI_K5 on GPIO_EMC_04 (pin 14) */
  gpio_pin_config_t DI_K5_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_04 (pin 14) */
  GPIO_PinInit(GPIO2, 4U, &DI_K5_config);

  /* GPIO configuration of DI_K6 on GPIO_EMC_05 (pin 13) */
  gpio_pin_config_t DI_K6_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_05 (pin 13) */
  GPIO_PinInit(GPIO2, 5U, &DI_K6_config);

  /* GPIO configuration of DI_K7 on GPIO_EMC_06 (pin 12) */
  gpio_pin_config_t DI_K7_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_06 (pin 12) */
  GPIO_PinInit(GPIO2, 6U, &DI_K7_config);

  /* GPIO configuration of DI_K8 on GPIO_EMC_07 (pin 10) */
  gpio_pin_config_t DI_K8_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_07 (pin 10) */
  GPIO_PinInit(GPIO2, 7U, &DI_K8_config);

  /* GPIO configuration of DI_K9 on GPIO_EMC_08 (pin 9) */
  gpio_pin_config_t DI_K9_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_08 (pin 9) */
  GPIO_PinInit(GPIO2, 8U, &DI_K9_config);

  /* GPIO configuration of DI_K10 on GPIO_EMC_09 (pin 8) */
  gpio_pin_config_t DI_K10_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_09 (pin 8) */
  GPIO_PinInit(GPIO2, 9U, &DI_K10_config);

  /* GPIO configuration of DI_K11 on GPIO_EMC_10 (pin 7) */
  gpio_pin_config_t DI_K11_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_10 (pin 7) */
  GPIO_PinInit(GPIO2, 10U, &DI_K11_config);

  /* GPIO configuration of DI_K12 on GPIO_EMC_11 (pin 4) */
  gpio_pin_config_t DI_K12_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_11 (pin 4) */
  GPIO_PinInit(GPIO2, 11U, &DI_K12_config);

  /* GPIO configuration of DI_K13 on GPIO_EMC_12 (pin 3) */
  gpio_pin_config_t DI_K13_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_12 (pin 3) */
  GPIO_PinInit(GPIO2, 12U, &DI_K13_config);

  /* GPIO configuration of DI_K14 on GPIO_EMC_13 (pin 2) */
  gpio_pin_config_t DI_K14_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_13 (pin 2) */
  GPIO_PinInit(GPIO2, 13U, &DI_K14_config);

  /* GPIO configuration of DI_K15 on GPIO_EMC_14 (pin 1) */
  gpio_pin_config_t DI_K15_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_14 (pin 1) */
  GPIO_PinInit(GPIO2, 14U, &DI_K15_config);

  /* GPIO configuration of DI_K16 on GPIO_EMC_15 (pin 143) */
  gpio_pin_config_t DI_K16_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_15 (pin 143) */
  GPIO_PinInit(GPIO2, 15U, &DI_K16_config);

  /* GPIO configuration of IO_ADD1 on GPIO_EMC_28 (pin 128) */
  gpio_pin_config_t IO_ADD1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_28 (pin 128) */
  GPIO_PinInit(GPIO2, 28U, &IO_ADD1_config);

  /* GPIO configuration of IO_ADD2 on GPIO_EMC_29 (pin 127) */
  gpio_pin_config_t IO_ADD2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_29 (pin 127) */
  GPIO_PinInit(GPIO2, 29U, &IO_ADD2_config);

  /* GPIO configuration of IO_ADD3 on GPIO_EMC_30 (pin 126) */
  gpio_pin_config_t IO_ADD3_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_30 (pin 126) */
  GPIO_PinInit(GPIO2, 30U, &IO_ADD3_config);

  /* GPIO configuration of IO_ADD4 on GPIO_EMC_31 (pin 125) */
  gpio_pin_config_t IO_ADD4_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_31 (pin 125) */
  GPIO_PinInit(GPIO2, 31U, &IO_ADD4_config);

  /* GPIO configuration of VER_SEL_1 on GPIO_EMC_32 (pin 124) */
  gpio_pin_config_t VER_SEL_1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_32 (pin 124) */
  GPIO_PinInit(GPIO3, 0U, &VER_SEL_1_config);

  /* GPIO configuration of VER_SEL_2 on GPIO_EMC_33 (pin 123) */
  gpio_pin_config_t VER_SEL_2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_33 (pin 123) */
  GPIO_PinInit(GPIO3, 1U, &VER_SEL_2_config);

  /* GPIO configuration of WDI_PFO on GPIO_EMC_34 (pin 122) */
  gpio_pin_config_t WDI_PFO_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_34 (pin 122) */
  GPIO_PinInit(GPIO3, 2U, &WDI_PFO_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_05_GPIO1_IO05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_06_LPUART1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_07_LPUART1_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_08_GPIO1_IO08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_09_GPIO1_IO09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_10_GPIO1_IO10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_GPIO1_IO12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_GPIO1_IO13, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_14_GPIO1_IO14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_15_GPIO1_IO15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_00_GPIO1_IO16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_01_GPIO1_IO17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_GPIO1_IO18, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_GPIO1_IO19, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_04_GPIO1_IO20, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_05_GPIO1_IO21, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_GPIO1_IO24, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_09_GPIO1_IO25, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_GPIO1_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_GPIO1_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_12_GPIO1_IO28, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_13_GPIO1_IO29, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_14_GPIO1_IO30, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_15_GPIO1_IO31, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_00_GPIO2_IO00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_01_GPIO2_IO01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_02_GPIO2_IO02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_03_GPIO2_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_04_GPIO2_IO04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_05_GPIO2_IO05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_06_GPIO2_IO06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_07_GPIO2_IO07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_08_GPIO2_IO08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_09_GPIO2_IO09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_10_GPIO2_IO10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_11_GPIO2_IO11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_12_GPIO2_IO12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_13_GPIO2_IO13, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_14_GPIO2_IO14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_15_GPIO2_IO15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_28_GPIO2_IO28, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_29_GPIO2_IO29, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_30_GPIO2_IO30, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_31_GPIO2_IO31, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_32_GPIO3_IO00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_33_GPIO3_IO01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_34_GPIO3_IO02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_00_LPI2C3_SCL, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_01_LPI2C3_SDA, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_00_FLEXCAN1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_01_FLEXCAN1_RX, 0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0x20B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0x50A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_06_LPUART1_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_07_LPUART1_RX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_34_GPIO3_IO02, 0x70B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_00_LPI2C3_SCL, 0xD8B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_01_LPI2C3_SDA, 0xD8B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_00_FLEXCAN1_TX, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_01_FLEXCAN1_RX, 0xB0U); 
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
